import type {
  AuthoredEpisodeDefinition,
  EpisodeConcept,
  EpisodeKeyword,
} from './authored-episode-factory';

const g = (
  id: string,
  pattern: string,
  reading: string,
  meaning: string,
  example: string,
  exampleMeaning: string,
): EpisodeConcept => ({ id, pattern, reading, meaning, example, exampleMeaning });

const v = (id: string, japanese: string, reading: string, meaning: string): EpisodeKeyword => ({ id, japanese, reading, meaning });

type N5Seed = Omit<AuthoredEpisodeDefinition, 'level' | 'comprehension'> & {
  wrongDetails: [string, string];
};

function n5(seed: N5Seed): AuthoredEpisodeDefinition {
  const { wrongDetails, ...definition } = seed;
  return {
    ...definition,
    level: 'N5',
    comprehension: {
      prompt: 'What did Yuki mean?',
      correct: definition.dialogue[1].meaning ?? 'The second message gives the key detail.',
      distractors: wrongDetails,
      explanation: 'Right. The particles, time expression, and final verb all support that reading.',
    },
  };
}

/** Episodes 2–26 form the N5 half of the new fifty-episode course. */
export const n5EpisodeDefinitions: AuthoredEpisodeDefinition[] = [
  n5({
    number: 2,
    titleJapanese: '新宿で会おう', titleEnglish: 'Finding Each Other in Shinjuku',
    opening: 'Yuki is waiting outside the east exit, but Shinjuku Station has more exits than you expected.',
    concepts: [
      g('episode-2-demonstratives', 'これ・それ・あれ／この・その・あの', 'これ・それ・あれ', 'point to things near me, near you, or away from both of us', 'その出口[でぐち]じゃなくて、あの大[おお]きい時計[とけい]の下[した]だよ。', 'Not that exit—the place under that big clock over there.'),
      g('episode-2-question-words', 'どこ・どれ・どの', 'どこ・どれ・どの', 'ask which place, item, or noun', 'どの出口[でぐち]にいる？', 'Which exit are you at?'),
    ],
    curriculumGrammarIds: ['grammar-kore', 'grammar-sore', 'grammar-are', 'grammar-kono', 'grammar-sono', 'grammar-ano', 'grammar-koko', 'grammar-soko', 'grammar-asoko', 'grammar-doko', 'grammar-dore', 'grammar-dono'],
    keywords: [v('episode-2-vocab-deguchi', '出口', 'でぐち', 'exit'), v('episode-2-vocab-tokei', '時計', 'とけい', 'clock')],
    dialogue: [
      { text: 'いま、どこにいる？', meaning: 'Where are you now?' },
      { text: '東口[ひがしぐち]の近[ちか]くにいるよ。赤[あか]い時計[とけい]が見[み]える？', meaning: 'Yuki is near the east exit and asks whether you can see a red clock.' },
    ],
    wrongDetails: ['Yuki is inside a red train.', 'Yuki wants you to go to the west exit tomorrow.'],
    build: { prompt: 'Tell Yuki which exit you can see.', parts: ['あの', 'でぐちが', 'みえるよ'], answer: 'あの出口[でぐち]が見[み]えるよ。', meaning: 'I can see that exit over there.', explanation: 'Use あの before a noun that is away from both speakers.' },
    exam: { format: 'vocabulary-in-context', prompt: 'Choose the reply that matches the location.', context: 'ゆきさんはどこですか。', options: ['あの時計[とけい]です。', '東口[ひがしぐち]の近[ちか]くです。', 'この出口[でぐち]を食[た]べます。'], correctIndex: 1, explanation: 'A location question with どこ is answered by a place: 東口の近くです。' },
    continuation: { text: '見[み]つけた！こっち、こっち！', meaning: 'Found you! Over here!' },
    nextHook: 'Now you have to order at a busy café without losing your table.',
  }),
  n5({
    number: 3,
    titleJapanese: '小さなカフェ', titleEnglish: 'A Table at the Café',
    opening: 'The café is crowded. Yuki gets a table while you order at the counter.',
    concepts: [
      g('episode-3-particles', 'を・で・に', 'を・で・に', 'mark the object, action place, and destination or time', 'カフェでコーヒーを飲[の]みます。', 'I drink coffee at the café.'),
      g('episode-3-direction', 'へ行く／に行く', 'へいく／にいく', 'express movement toward a destination', '先[さき]に席[せき]へ行[い]ってるね。', 'I will go to the table first.'),
    ],
    curriculumGrammarIds: ['grammar-o', 'grammar-de-action-location-marker', 'grammar-de-means-marker', 'grammar-ni', 'grammar-he', 'grammar-heiku'],
    keywords: [v('episode-3-vocab-seki', '席', 'せき', 'seat'), v('episode-3-vocab-chuumon', '注文', 'ちゅうもん', 'order')],
    dialogue: [
      { text: '私[わたし]は席[せき]を取[と]っておくね。', meaning: 'Yuki will save a table.' },
      { text: 'カウンターで飲[の]み物[もの]を注文[ちゅうもん]してくれる？', meaning: 'Yuki asks you to order drinks at the counter.' },
    ],
    wrongDetails: ['Yuki asks you to drink outside.', 'Yuki has already paid at the station.'],
    build: { prompt: 'Say where you will order coffee.', parts: ['カウンターで', 'コーヒーを', 'ちゅうもんするね'], answer: 'カウンターでコーヒーを注文[ちゅうもん]するね。', meaning: 'I’ll order coffee at the counter.', explanation: 'で marks where the ordering happens; を marks what is ordered.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the particles that complete the sentence.', context: 'カフェ（　）お茶[ちゃ]（　）飲[の]みます。', options: ['に・が', 'で・を', 'を・で'], correctIndex: 1, explanation: 'The action location takes で, and the object of 飲みます takes を.' },
    continuation: { text: 'ありがとう。窓[まど]のそばの席[せき]にいるね。', meaning: 'Thanks. I’ll be at the table by the window.' },
    nextHook: 'At the table, Yuki introduces someone who will matter later in the story.',
  }),
  n5({
    number: 4,
    titleJapanese: 'ゆきの友達', titleEnglish: "Yuki's Friend",
    opening: 'A university student named Ren joins you. The conversation turns into a quick round of introductions.',
    concepts: [
      g('episode-4-topic-subject', 'は・が・も', 'は・が・も', 'mark a topic, identify a subject, and add “also”', '私[わたし]は学生[がくせい]です。れんさんも学生[がくせい]です。', 'I am a student. Ren is also a student.'),
      g('episode-4-existence', 'ある・いる', 'ある・いる', 'say that things or people exist', '妹[いもうと]が一人[ひとり]います。', 'I have one younger sister.'),
    ],
    curriculumGrammarIds: ['grammar-ha', 'grammar-ga-subject-marker', 'grammar-mo', 'grammar-no-possession-marker', 'grammar-gaaru', 'grammar-gaaru-noun', 'grammar-gairu', 'grammar-desu'],
    keywords: [v('episode-4-vocab-gakusei', '学生', 'がくせい', 'student'), v('episode-4-vocab-imouto', '妹', 'いもうと', 'younger sister')],
    dialogue: [
      { text: 'こちらは友達[ともだち]のれん。大学[だいがく]で日本語[にほんご]を勉強[べんきょう]してるよ。', meaning: 'This is Yuki’s friend Ren, who studies Japanese at university.' },
      { text: 'れんも外国[がいこく]に住[す]んだことがあるんだ。', meaning: 'Ren has also lived abroad.' },
    ],
    wrongDetails: ['Ren teaches at a foreign university.', 'Ren has never left Japan.'],
    build: { prompt: 'Introduce yourself and add that Ren is a student too.', parts: ['わたしは', 'がくせいです', 'れんさんも', 'がくせいです'], answer: '私[わたし]は学生[がくせい]です。れんさんも学生[がくせい]です。', meaning: 'I am a student. Ren is also a student.', explanation: 'は establishes your topic; も replaces は when you add matching information.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the natural particle.', context: 'だれ（　）ゆきさんですか。', options: ['を', 'が', 'で'], correctIndex: 1, explanation: 'In a question asking who has an identity or role, が marks the unknown subject.' },
    continuation: { text: '三人[さんにん]になったし、そろそろ町[まち]を歩[ある]こうか。', meaning: 'Now that there are three of us, shall we walk around town?' },
    nextHook: 'Ren has a plan, but the day’s timetable is tighter than it looks.',
  }),
  n5({
    number: 5,
    titleJapanese: '今日の予定', titleEnglish: "Today's Schedule",
    opening: 'Ren opens a map. There is time for one museum before dinner—if everyone reads the schedule correctly.',
    concepts: [
      g('episode-5-time', '時刻＋に', 'じこく＋に', 'mark the time when an event happens', '三時[さんじ]に美術館[びじゅつかん]へ行[い]きます。', 'We will go to the museum at three.'),
      g('episode-5-range', 'から・まで', 'から・まで', 'mark the beginning and end of a range', '美術館[びじゅつかん]は五時[ごじ]までです。', 'The museum is open until five.'),
    ],
    curriculumGrammarIds: ['grammar-ni', 'grammar-kara-starting-point-marker', 'grammar-noun-made', 'grammar-verb-made'],
    keywords: [v('episode-5-vocab-bijutsukan', '美術館', 'びじゅつかん', 'art museum'), v('episode-5-vocab-yotei', '予定', 'よてい', 'schedule')],
    dialogue: [
      { text: '美術館[びじゅつかん]は十時[じゅうじ]から五時[ごじ]までだよ。', meaning: 'The museum is open from ten until five.' },
      { text: 'いま二時半[にじはん]だから、三時[さんじ]に入[はい]ろう。', meaning: 'It is 2:30 now, so Yuki suggests entering at three.' },
    ],
    wrongDetails: ['The museum closes at 2:30.', 'Yuki wants to enter tomorrow morning.'],
    build: { prompt: 'Confirm the meeting time.', parts: ['さんじに', 'びじゅつかんで', 'あおう'], answer: '三時[さんじ]に美術館[びじゅつかん]で会[あ]おう。', meaning: 'Let’s meet at the museum at three.', explanation: 'に marks three as the meeting time; で marks the meeting place.' },
    exam: { format: 'information-retrieval', prompt: 'Choose the statement supported by the schedule.', context: '開館[かいかん]　十時[じゅうじ]―十七時[じゅうしちじ]', options: ['朝[あさ]九時[くじ]に入[はい]れます。', '午後[ごご]六時[ろくじ]まで見[み]られます。', '午後[ごご]四時[よじ]は開[あ]いています。'], correctIndex: 2, explanation: 'Four in the afternoon falls between 10:00 and 17:00.' },
    continuation: { text: 'その前[まえ]に、駅[えき]で切符[きっぷ]を買[か]おう。', meaning: 'Before that, let’s buy the tickets at the station.' },
    nextHook: 'Buying the tickets becomes your first chance to invite someone naturally.',
  }),
  n5({
    number: 6,
    titleJapanese: 'いっしょに行かない？', titleEnglish: 'An Invitation for Ren',
    opening: 'Ren is unsure whether he should join. Yuki nudges you to invite him yourself.',
    concepts: [
      g('episode-6-invitation', '～ませんか', '～ませんか', 'make a polite invitation', 'いっしょに美術館[びじゅつかん]へ行[い]きませんか。', 'Would you like to go to the museum together?'),
      g('episode-6-volition', '～ましょう／～ましょうか', '～ましょう／～ましょうか', 'suggest doing something or offer help', '切符[きっぷ]を買[か]いましょうか。', 'Shall I buy the tickets?'),
    ],
    curriculumGrammarIds: ['grammar-masenka', 'grammar-mashou', 'grammar-mashouka'],
    keywords: [v('episode-6-vocab-issho', '一緒', 'いっしょ', 'together'), v('episode-6-vocab-kippu', '切符', 'きっぷ', 'ticket')],
    dialogue: [
      { text: 'れんも誘[さそ]ってみようよ。', meaning: 'Yuki suggests inviting Ren too.' },
      { text: '「一緒[いっしょ]に行[い]きませんか」って言[い]えば自然[しぜん]だよ。', meaning: 'Yuki says “Would you like to go together?” is a natural invitation.' },
    ],
    wrongDetails: ['Yuki says Ren has already refused.', 'Yuki asks you to sell Ren a ticket.'],
    build: { prompt: 'Invite Ren politely.', parts: ['いっしょに', 'びじゅつかんへ', 'いきませんか'], answer: '一緒[いっしょ]に美術館[びじゅつかん]へ行[い]きませんか。', meaning: 'Would you like to go to the museum together?', explanation: 'ませんか is an invitation, not simply a negative question.' },
    exam: { format: 'appropriate-response', prompt: 'Choose the most natural response.', context: '一緒[いっしょ]に行[い]きませんか。', options: ['はい、ぜひ。', 'いいえ、行[い]きます。', '三人[さんにん]が切符[きっぷ]です。'], correctIndex: 0, explanation: 'はい、ぜひ accepts the invitation warmly and naturally.' },
    continuation: { text: 'いいね。じゃあ、三人[さんにん]で行[い]こう！', meaning: 'Great. Then let’s all go together!' },
    nextHook: 'On the train, a story about yesterday forces you to control verb tense.',
  }),
  n5({
    number: 7,
    titleJapanese: '昨日、何をした？', titleEnglish: 'What Happened Yesterday?',
    opening: 'The train is delayed. Ren fills the silence by asking about your first day in Japan.',
    concepts: [
      g('episode-7-verb-tense', '動詞の非過去・過去', 'どうしのひかこ・かこ', 'contrast present or future actions with completed actions', '昨日[きのう]、ホテルで休[やす]みました。', 'Yesterday, I rested at the hotel.'),
      g('episode-7-negative', '～ない・～なかった', '～ない・～なかった', 'form present and past negatives', '昨日[きのう]は外[そと]へ出[で]なかった。', 'I did not go outside yesterday.'),
    ],
    curriculumGrammarIds: ['grammar-verbsnon-past', 'grammar-u-verbdictionary', 'grammar-u-verbpast', 'grammar-u-verbnegative', 'grammar-u-verbnegative-past', 'grammar-ru-verbdictionary', 'grammar-ru-verbpast', 'grammar-ru-verbnegative', 'grammar-ru-verbnegative-past', 'grammar-suru', 'grammar-kuru'],
    keywords: [v('episode-7-vocab-kinou', '昨日', 'きのう', 'yesterday'), v('episode-7-vocab-yasumu', '休', 'やす', 'rest')],
    dialogue: [
      { text: '昨日[きのう]は何[なに]をしたの？', meaning: 'Ren asks what you did yesterday.' },
      { text: '私[わたし]は荷物[にもつ]を片[かた]づけて、夜[よる]は早[はや]く寝[ね]たよ。', meaning: 'Yuki unpacked and went to bed early.' },
    ],
    wrongDetails: ['Yuki will unpack tomorrow night.', 'Yuki stayed awake all night.'],
    build: { prompt: 'Say that you did not go out yesterday.', parts: ['きのうは', 'そとへ', 'でなかった'], answer: '昨日[きのう]は外[そと]へ出[で]なかった。', meaning: 'I did not go outside yesterday.', explanation: 'The past-negative ending なかった places the non-event in the completed past.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the correct past form.', context: '昨日[きのう]、写真[しゃしん]をたくさん（　）。', options: ['撮[と]る', '撮[と]った', '撮[と]らない'], correctIndex: 1, explanation: '昨日 requires the completed past form 撮った.' },
    continuation: { text: '次[つぎ]の休[やす]みは、もっと町[まち]を見[み]たいね。', meaning: 'On the next day off, I want to see more of the city.' },
    nextHook: 'At the museum, describing the art brings adjective forms into focus.',
  }),
  n5({
    number: 8,
    titleJapanese: 'どんな絵？', titleEnglish: 'What Kind of Painting?',
    opening: 'Inside the museum, the three of you react very differently to the same painting.',
    concepts: [
      g('episode-8-i-adjectives', 'い形容詞', 'いけいようし', 'describe nouns and make positive or negative predicates', 'この絵[え]は明[あか]るくないけど、おもしろい。', 'This painting is not bright, but it is interesting.'),
      g('episode-8-i-past', '～かった／～くなかった', '～かった／～くなかった', 'make past affirmative and negative i-adjectives', '昨日[きのう]の展示[てんじ]は長[なが]くなかった。', "Yesterday's exhibition was not long."),
    ],
    curriculumGrammarIds: ['grammar-i-adjectives', 'grammar-i-adjective-noun', 'grammar-i-adjectivepredicate', 'grammar-i-adjectiveskunai', 'grammar-i-adjectivepast', 'grammar-i-adjectivekunakatta', 'grammar-ii'],
    keywords: [v('episode-8-vocab-e', '絵', 'え', 'painting'), v('episode-8-vocab-tenji', '展示', 'てんじ', 'exhibition')],
    dialogue: [
      { text: 'この青[あお]い絵[え]、ちょっと怖[こわ]いね。', meaning: 'Yuki finds the blue painting a little scary.' },
      { text: 'でも、色[いろ]がきれいで、おもしろいと思[おも]う。', meaning: 'Even so, Yuki thinks its colors are beautiful and it is interesting.' },
    ],
    wrongDetails: ['Yuki thinks the painting is boring and cheap.', 'Yuki says the museum is closed.'],
    build: { prompt: 'Give a balanced reaction to the painting.', parts: ['このえは', 'あかるくないけど', 'おもしろい'], answer: 'この絵[え]は明[あか]るくないけど、おもしろい。', meaning: 'This painting is not bright, but it is interesting.', explanation: 'Drop い and add くない for the negative form; けど links a contrast.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the correct past-negative adjective.', context: '昨日[きのう]の映画[えいが]は（　）。', options: ['おもしろくなかったです', 'おもしろいじゃないです', 'おもしろいなかったです'], correctIndex: 0, explanation: 'The past negative of an i-adjective is ～くなかったです.' },
    continuation: { text: '次[つぎ]の部屋[へや]は静[しず]かで、ゆっくり見[み]られそう。', meaning: 'The next room is quiet, so it looks like we can take our time.' },
    nextHook: 'The quiet room introduces a different adjective family and its noun-like past forms.',
  }),
  n5({
    number: 9,
    titleJapanese: '静かな部屋', titleEnglish: 'The Quiet Gallery',
    opening: 'A staff member asks everyone to speak softly. Ren compares this room with the lively hall outside.',
    concepts: [
      g('episode-9-na-adjectives', 'な形容詞', 'なけいようし', 'use な before a noun and だ or です as a predicate', 'ここは静[しず]かな部屋[へや]です。', 'This is a quiet room.'),
      g('episode-9-noun-past', 'だった・じゃなかった', 'だった・じゃなかった', 'make casual past and past-negative noun or na-adjective statements', '前[まえ]の部屋[へや]は静[しず]かじゃなかった。', 'The previous room was not quiet.'),
    ],
    curriculumGrammarIds: ['grammar-na-adjectives', 'grammar-na-adjective-noun', 'grammar-na-adjectiveda', 'grammar-na', 'grammar-janai', 'grammar-datta', 'grammar-janakatta'],
    keywords: [v('episode-9-vocab-shizuka', '静', 'しず', 'quiet'), v('episode-9-vocab-heya', '部屋', 'へや', 'room')],
    dialogue: [
      { text: 'この部屋[へや]は本当[ほんとう]に静[しず]かだね。', meaning: 'Yuki says this room is really quiet.' },
      { text: 'さっきのホールはにぎやかだったから、ずいぶん違[ちが]うね。', meaning: 'The previous hall was lively, so this room feels very different.' },
    ],
    wrongDetails: ['The previous hall was closed.', 'Yuki thinks both rooms are equally noisy.'],
    build: { prompt: 'Describe the room politely.', parts: ['ここは', 'しずかな', 'へやです'], answer: 'ここは静[しず]かな部屋[へや]です。', meaning: 'This is a quiet room.', explanation: 'A na-adjective takes な directly before a noun.' },
    exam: { format: 'sentence-formation', prompt: 'Choose the natural sentence.', context: '前[まえ]の部屋[へや]について話[はな]します。', options: ['前[まえ]の部屋[へや]は静[しず]かなかった。', '前[まえ]の部屋[へや]は静[しず]かじゃなかった。', '前[まえ]の部屋[へや]は静[しず]かくないだった。'], correctIndex: 1, explanation: 'Na-adjectives pattern with noun-like じゃなかった in the past negative.' },
    continuation: { text: '外[そと]に出[で]たら、好[す]きな食[た]べ物[もの]の話[はなし]をしよう。', meaning: 'When we go outside, let’s talk about foods we like.' },
    nextHook: 'Dinner reveals what each friend likes, dislikes, and is good at making.',
  }),
  n5({
    number: 10,
    titleJapanese: '好きな味', titleEnglish: 'Flavors We Like',
    opening: 'At a small restaurant, the menu becomes a friendly argument about favorite foods and cooking skills.',
    concepts: [
      g('episode-10-likes', '～のが好き／きらい', '～のがすき／きらい', 'express liking or disliking an activity', '辛[から]い物[もの]を食[た]べるのが好[す]きです。', 'I like eating spicy food.'),
      g('episode-10-skill', '～のが上手／下手', '～のがじょうず／へた', 'say that someone is good or poor at an activity', 'れんは料理[りょうり]を作[つく]るのが上手[じょうず]です。', 'Ren is good at cooking.'),
    ],
    curriculumGrammarIds: ['grammar-好ki', 'grammar-kirai', 'grammar-nogasuki', 'grammar-nogajouzu', 'grammar-nogaheta', 'grammar-no-nominalizer'],
    keywords: [v('episode-10-vocab-ryouri', '料理', 'りょうり', 'cooking; cuisine'), v('episode-10-vocab-karai', '辛', 'から', 'spicy')],
    dialogue: [
      { text: '私[わたし]は辛[から]い物[もの]が好[す]きだけど、れんは苦手[にがて]なんだ。', meaning: 'Yuki likes spicy food, but Ren is not comfortable with it.' },
      { text: 'でも、れんは魚[さかな]を焼[や]くのが上手[じょうず]だよ。', meaning: 'Ren is good at grilling fish.' },
    ],
    wrongDetails: ['Ren hates cooking fish.', 'Yuki says everyone likes spicy food.'],
    build: { prompt: 'Say that Ren is good at cooking.', parts: ['れんは', 'りょうりをつくるのが', 'じょうずです'], answer: 'れんは料理[りょうり]を作[つく]るのが上手[じょうず]です。', meaning: 'Ren is good at cooking.', explanation: 'The nominalizer の turns 作る into the activity that 上手 describes.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the phrase that completes the meaning.', context: '私[わたし]は音楽[おんがく]を聞[き]く（　）好[す]きです。', options: ['のが', 'まで', 'だけを'], correctIndex: 0, explanation: 'の nominalizes 聞く, and が marks the thing liked.' },
    continuation: { text: '次[つぎ]は、三人[さんにん]でいちばん好[す]きな店[みせ]を決[き]めよう。', meaning: 'Next, let’s decide which shop the three of us like best.' },
    nextHook: 'Choosing one shop means comparing prices, distance, and taste.',
  }),
  n5({
    number: 11,
    titleJapanese: 'どちらがいい？', titleEnglish: 'Which One Is Better?',
    opening: 'Two dessert shops look equally tempting. The group compares them before choosing one.',
    concepts: [
      g('episode-11-comparison', 'AよりBのほうが', 'AよりBのほうが', 'compare two things', '駅前[えきまえ]の店[みせ]より、この店[みせ]のほうが安[やす]い。', 'This shop is cheaper than the one by the station.'),
      g('episode-11-superlative', '～の中で～がいちばん', '～のなかで～がいちばん', 'choose the highest degree within a group', 'この町[まち]の中[なか]で、ここがいちばん人気[にんき]です。', 'This is the most popular place in town.'),
    ],
    curriculumGrammarIds: ['grammar-yori-nohouga', 'grammar-nonakade-gaichiban', 'grammar-dore', 'grammar-dono'],
    keywords: [v('episode-11-vocab-yasui', '安', 'やす', 'inexpensive'), v('episode-11-vocab-ninki', '人気', 'にんき', 'popular')],
    dialogue: [
      { text: '駅前[えきまえ]の店[みせ]は近[ちか]いけど、少[すこ]し高[たか]いよ。', meaning: 'The station shop is close, but a little expensive.' },
      { text: '味[あじ]なら、川[かわ]のそばの店[みせ]のほうがいいと思[おも]う。', meaning: 'For taste, Yuki prefers the shop by the river.' },
    ],
    wrongDetails: ['The river shop is closer to the station.', 'Yuki says both shops are closed.'],
    build: { prompt: 'Compare the two shops by price.', parts: ['えきまえのみせより', 'このみせのほうが', 'やすい'], answer: '駅前[えきまえ]の店[みせ]より、この店[みせ]のほうが安[やす]い。', meaning: 'This shop is cheaper than the station shop.', explanation: 'The reference comes before より; the preferred item comes before のほうが.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the comparison frame.', context: '電車[でんしゃ]（　）バスのほうが速[はや]いです。', options: ['まで', 'より', 'だけ'], correctIndex: 1, explanation: 'より marks the item used as the comparison baseline.' },
    continuation: { text: 'じゃあ、川[かわ]のそばの店[みせ]に決[き]まり！', meaning: 'Then it’s settled—the shop by the river!' },
    nextHook: 'On the walk there, connected actions and descriptions make the story flow.',
  }),
  n5({
    number: 12,
    titleJapanese: '川まで歩いて', titleEnglish: 'Walking to the River',
    opening: 'The route winds through a lively shopping street. Yuki narrates each turn so nobody gets lost.',
    concepts: [
      g('episode-12-te-sequence', '動詞て形・～て、B', 'どうしてけい・～て、B', 'connect actions in sequence', '信号[しんごう]を渡[わた]って、右[みぎ]に曲[ま]がります。', 'Cross the light, then turn right.'),
      g('episode-12-adjective-link', '形容詞＋て／で', 'けいようし＋て／で', 'connect descriptions or give a cause', 'この道[みち]は広[ひろ]くて、歩[ある]きやすいです。', 'This road is wide and easy to walk on.'),
    ],
    curriculumGrammarIds: ['grammar-verb-te', 'grammar-verb-te-b', 'grammar-adjective-te', 'grammar-adjective-te-b', 'grammar-ga-contrast-conjunction', 'grammar-kedo', 'grammar-keredomo'],
    keywords: [v('episode-12-vocab-shingou', '信号', 'しんごう', 'traffic light'), v('episode-12-vocab-michi', '道', 'みち', 'road')],
    dialogue: [
      { text: 'この信号[しんごう]を渡[わた]って、商店街[しょうてんがい]をまっすぐ行[い]こう。', meaning: 'Cross this light and go straight through the shopping street.' },
      { text: '道[みち]が広[ひろ]くて、人[ひと]も多[おお]いから、はぐれないでね。', meaning: 'The road is wide and crowded, so Yuki says not to get separated.' },
    ],
    wrongDetails: ['The road is narrow and empty.', 'Yuki tells you to cross the river alone.'],
    build: { prompt: 'Put the route instructions in order.', parts: ['しんごうをわたって', 'みぎに', 'まがります'], answer: '信号[しんごう]を渡[わた]って、右[みぎ]に曲[ま]がります。', meaning: 'Cross the traffic light and turn right.', explanation: 'The te-form connects the first action to the next one.' },
    exam: { format: 'sentence-ordering', prompt: 'Choose the correctly connected description.', context: 'この公園[こうえん]は（　）。', options: ['静[しず]かくて、きれいです', '静[しず]かで、きれいです', '静[しず]かなて、きれいです'], correctIndex: 1, explanation: 'A na-adjective connects with で: 静かで、きれいです.' },
    continuation: { text: 'あ、向[む]こうに店[みせ]の看板[かんばん]が見[み]えた！', meaning: 'Oh, I can see the shop sign over there!' },
    nextHook: 'A crowded entrance brings requests, permission, and rules into the conversation.',
  }),
  n5({
    number: 13,
    titleJapanese: '店のルール', titleEnglish: 'Rules at the Door',
    opening: 'The shop has a waiting list and a few house rules. You need to understand what is allowed.',
    concepts: [
      g('episode-13-request', '～てください／～ないでください', '～てください／～ないでください', 'make affirmative and negative requests', 'ここに名前[なまえ]を書[か]いてください。', 'Please write your name here.'),
      g('episode-13-permission', '～てもいい／～てはいけない', '～てもいい／～てはいけない', 'give permission or prohibit an action', '外[そと]で待[ま]ってもいいです。', 'You may wait outside.'),
    ],
    curriculumGrammarIds: ['grammar-tekudasai', 'grammar-naidekudasai', 'grammar-temoii', 'grammar-tehaikenai', 'grammar-na'],
    keywords: [v('episode-13-vocab-namae', '名前', 'なまえ', 'name'), v('episode-13-vocab-matsu', '待', 'ま', 'wait')],
    dialogue: [
      { text: '入口[いりぐち]の紙[かみ]に名前[なまえ]を書[か]いてください。', meaning: 'Please write your name on the paper at the entrance.' },
      { text: '店[みせ]の中[なか]では電話[でんわ]で話[はな]してはいけないみたい。', meaning: 'It seems phone calls are not allowed inside.' },
    ],
    wrongDetails: ['You must call the shop from inside.', 'You should write the menu on the door.'],
    build: { prompt: 'Ask Ren not to make a phone call inside.', parts: ['なかでは', 'でんわを', 'しないでください'], answer: '中[なか]では電話[でんわ]をしないでください。', meaning: 'Please do not make phone calls inside.', explanation: 'Attach ないでください to the negative verb stem for a polite negative request.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the phrase that grants permission.', context: 'この席[せき]に座[すわ]って（　）ですか。', options: ['もいい', 'はいけない', 'ないで'], correctIndex: 0, explanation: '～てもいいですか asks whether an action is permitted.' },
    continuation: { text: '順番[じゅんばん]が来[く]るまで、外[そと]で待[ま]とう。', meaning: 'Let’s wait outside until our turn comes.' },
    nextHook: 'While waiting, you notice what everyone nearby is doing right now.',
  }),
  n5({
    number: 14,
    titleJapanese: '今、何してる？', titleEnglish: 'What Is Everyone Doing?',
    opening: 'People wait in different ways: reading, talking, and staring at the river.',
    concepts: [
      g('episode-14-progressive', '～ている（進行）', '～ている', 'describe an action in progress', 'れんは本[ほん]を読[よ]んでいます。', 'Ren is reading a book.'),
      g('episode-14-state', '～ている（状態・習慣）', '～ている', 'describe a resulting state or habitual action', 'ゆきは東京[とうきょう]に住[す]んでいます。', 'Yuki lives in Tokyo.'),
    ],
    curriculumGrammarIds: ['grammar-teiru1', 'grammar-teiru2', 'grammar-teiru3'],
    keywords: [v('episode-14-vocab-yomu', '読', 'よ', 'read'), v('episode-14-vocab-sumu', '住', 'す', 'live; reside')],
    dialogue: [
      { text: 'れんは何[なに]を読[よ]んでるの？', meaning: 'Yuki asks what Ren is reading.' },
      { text: '東京[とうきょう]に住[す]んでいる人[ひと]のブログだって。', meaning: 'It is a blog by someone who lives in Tokyo.' },
    ],
    wrongDetails: ['Ren is writing a letter about Osaka.', 'The blog belongs to someone visiting tomorrow.'],
    build: { prompt: 'Say what Ren is doing now.', parts: ['れんは', 'ほんを', 'よんでいます'], answer: 'れんは本[ほん]を読[よ]んでいます。', meaning: 'Ren is reading a book.', explanation: 'Context tells you whether ～ている means “doing now,” a state, or a habit.' },
    exam: { format: 'meaning-in-context', prompt: 'Choose the meaning of the sentence.', context: '田中[たなか]さんは結婚[けっこん]しています。', options: ['田中[たなか]さんは今[いま]、結婚式[けっこんしき]をしています。', '田中[たなか]さんは結婚[けっこん]している状態[じょうたい]です。', '田中[たなか]さんは結婚[けっこん]しません。'], correctIndex: 1, explanation: 'With 結婚する, ～ている normally describes the resulting state: being married.' },
    continuation: { text: '呼[よ]ばれたよ。入[はい]ってから、注文[ちゅうもん]を決[き]めよう。', meaning: 'They called us. After we go in, let’s decide what to order.' },
    nextHook: 'Sequence matters when the group plans what to do before and after dessert.',
  }),
  n5({
    number: 15,
    titleJapanese: '食べる前に', titleEnglish: 'Before the First Bite',
    opening: 'The desserts arrive looking too perfect to touch. Ren reaches for his spoon before Yuki can take a photo.',
    concepts: [
      g('episode-15-before', '辞書形＋前に', 'じしょけい＋まえに', 'say that one action happens before another', '食[た]べる前[まえ]に、写真[しゃしん]を撮[と]ろう。', 'Let’s take a photo before eating.'),
      g('episode-15-after', '～てから', '～てから', 'say that one action happens after another finishes', '写真[しゃしん]を撮[と]ってから、食[た]べます。', 'I will eat after taking a photo.'),
    ],
    curriculumGrammarIds: ['grammar-maeni', 'grammar-tekara'],
    keywords: [v('episode-15-vocab-mae', '前', 'まえ', 'before; front'), v('episode-15-vocab-shashin', '写真', 'しゃしん', 'photograph')],
    dialogue: [
      { text: '待[ま]って！食[た]べる前[まえ]に写真[しゃしん]を撮[と]りたい。', meaning: 'Yuki wants to take a photo before eating.' },
      { text: '写真[しゃしん]を撮[と]ってから、みんなで食[た]べよう。', meaning: 'Yuki suggests taking the photo first and then eating together.' },
    ],
    wrongDetails: ['Yuki wants a photo after everyone leaves.', 'Yuki tells Ren to eat alone now.'],
    build: { prompt: 'Put the actions in the right order.', parts: ['しゃしんをとってから', 'たべます'], answer: '写真[しゃしん]を撮[と]ってから、食[た]べます。', meaning: 'I will eat after taking a photo.', explanation: 'The action before てから is completed first.' },
    exam: { format: 'sentence-ordering', prompt: 'Choose the sentence matching “study before sleeping.”', context: '寝[ね]る・勉強[べんきょう]する', options: ['寝[ね]てから勉強[べんきょう]します。', '寝[ね]る前[まえ]に勉強[べんきょう]します。', '勉強[べんきょう]するまで寝[ね]ます。'], correctIndex: 1, explanation: 'The dictionary form plus 前に expresses doing the study before sleeping.' },
    continuation: { text: '食[た]べ終[お]わったら、次[つぎ]の週末[しゅうまつ]の話[はなし]をしよう。', meaning: 'When we finish eating, let’s talk about next weekend.' },
    nextHook: 'Everyone has something they want or intend to do next weekend.',
  }),
  n5({
    number: 16,
    titleJapanese: '週末にしたいこと', titleEnglish: 'Plans for the Weekend',
    opening: 'Each person proposes a different weekend plan: shopping, hiking, or visiting a temple.',
    concepts: [
      g('episode-16-desire', '～たい', '～たい', 'express what the speaker wants to do', '京都[きょうと]のお寺[てら]を見[み]たいです。', 'I want to see a temple in Kyoto.'),
      g('episode-16-intention', '～つもり／動詞ます形＋に行く', '～つもり／～にいく', 'state an intention or go somewhere for a purpose', '週末[しゅうまつ]は靴[くつ]を買[か]いに行[い]くつもりです。', 'I intend to go buy shoes this weekend.'),
    ],
    curriculumGrammarIds: ['grammar-tai', 'grammar-tsumorida', 'grammar-verb-niiku'],
    keywords: [v('episode-16-vocab-shuumatsu', '週末', 'しゅうまつ', 'weekend'), v('episode-16-vocab-tera', '寺', 'てら', 'Buddhist temple')],
    dialogue: [
      { text: '週末[しゅうまつ]、何[なに]をしたい？', meaning: 'Yuki asks what you want to do this weekend.' },
      { text: 'れんは新[あたら]しい靴[くつ]を買[か]いに行[い]くつもりだって。', meaning: 'Ren intends to go buy new shoes.' },
    ],
    wrongDetails: ['Ren already sold his shoes.', 'Yuki asks what you did last weekend.'],
    build: { prompt: 'State Ren’s weekend intention.', parts: ['しゅうまつは', 'くつをかいにいく', 'つもりです'], answer: '週末[しゅうまつ]は靴[くつ]を買[か]いに行[い]くつもりです。', meaning: 'I intend to go buy shoes this weekend.', explanation: 'The ます-stem 買い plus に行く gives the purpose; つもり states intention.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the purpose construction.', context: '図書館[としょかん]へ本[ほん]を（　）行[い]きます。', options: ['借[か]りに', '借[か]りて', '借[か]りたいを'], correctIndex: 0, explanation: 'Use the verb stem 借り + に行く to express going in order to borrow.' },
    continuation: { text: '私[わたし]は山[やま]にも行[い]ってみたいな。', meaning: 'I would also like to try going to the mountains.' },
    nextHook: 'Past experiences help the group choose a weekend plan.',
  }),
  n5({
    number: 17,
    titleJapanese: '行ったことある？', titleEnglish: 'Have You Ever Been?',
    opening: 'The friends compare places they have visited and the kinds of things they do on trips.',
    concepts: [
      g('episode-17-experience', '～たことがある', '～たことがある', 'talk about past experience', '富士山[ふじさん]を見[み]たことがあります。', 'I have seen Mount Fuji.'),
      g('episode-17-examples', '～たり～たりする', '～たり～たりする', 'list representative activities', '旅行[りょこう]では写真[しゃしん]を撮[と]ったり、温泉[おんせん]に入[はい]ったりします。', 'On trips I do things like take photos and visit hot springs.'),
    ],
    curriculumGrammarIds: ['grammar-takotogaaru', 'grammar-tari-tarisuru'],
    keywords: [v('episode-17-vocab-ryokou', '旅行', 'りょこう', 'travel'), v('episode-17-vocab-onsen', '温泉', 'おんせん', 'hot spring')],
    dialogue: [
      { text: '箱根[はこね]に行[い]ったことある？', meaning: 'Yuki asks whether you have ever been to Hakone.' },
      { text: '温泉[おんせん]に入[はい]ったり、山[やま]を歩[ある]いたりできるよ。', meaning: 'In Hakone, you can do things like visit hot springs and hike.' },
    ],
    wrongDetails: ['Hakone only has beaches.', 'Yuki says hiking is forbidden there.'],
    build: { prompt: 'Describe two typical travel activities.', parts: ['りょこうでは', 'しゃしんをとったり', 'おんせんにはいったりします'], answer: '旅行[りょこう]では写真[しゃしん]を撮[と]ったり、温泉[おんせん]に入[はい]ったりします。', meaning: 'On trips, I do things like take photos and visit hot springs.', explanation: 'The たり forms give examples; the list is not necessarily complete.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the experience form.', context: '日本[にほん]の映画[えいが]を見[み]た（　）ありますか。', options: ['ことが', 'ものを', 'ので'], correctIndex: 0, explanation: 'Past form + ことがある asks about life experience.' },
    continuation: { text: 'じゃあ、箱根[はこね]を週末[しゅうまつ]の候補[こうほ]にしよう。', meaning: 'Then let’s make Hakone one of the weekend options.' },
    nextHook: 'A sudden change of weather forces everyone to explain reasons clearly.',
  }),
  n5({
    number: 18,
    titleJapanese: '雨だから', titleEnglish: 'Because of the Rain',
    opening: 'Rain starts before the group reaches the station. Everyone explains what should change and why.',
    concepts: [
      g('episode-18-reason', '～から／～ので', '～から／～ので', 'give a reason; ので often sounds softer', '雨[あめ]が降[ふ]っているので、電車[でんしゃ]で帰[かえ]ります。', 'Because it is raining, I will go home by train.'),
      g('episode-18-explanation', '～んです', '～んです', 'give background or ask for an explanation', '傘[かさ]を持[も]っていないんです。', 'The thing is, I do not have an umbrella.'),
    ],
    curriculumGrammarIds: ['grammar-kara-reason-conjunction', 'grammar-node', 'grammar-ndesu', 'grammar-no-explanatory-nominalizer'],
    keywords: [v('episode-18-vocab-ame', '雨', 'あめ', 'rain'), v('episode-18-vocab-kasa', '傘', 'かさ', 'umbrella')],
    dialogue: [
      { text: '急[きゅう]に雨[あめ]が強[つよ]くなったね。', meaning: 'The rain suddenly became heavy.' },
      { text: '傘[かさ]を一本[いっぽん]しか持[も]っていないから、駅[えき]まで走[はし]ろう。', meaning: 'Yuki has only one umbrella, so she suggests running to the station.' },
    ],
    wrongDetails: ['Yuki has three umbrellas.', 'Yuki wants to wait at the museum until tomorrow.'],
    build: { prompt: 'Explain softly why you will take the train.', parts: ['あめがふっているので', 'でんしゃで', 'かえります'], answer: '雨[あめ]が降[ふ]っているので、電車[でんしゃ]で帰[かえ]ります。', meaning: 'Because it is raining, I will go home by train.', explanation: 'ので connects the situation to its consequence with a neutral, explanatory tone.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the natural explanation.', context: 'どうして遅[おく]れたんですか。', options: ['電車[でんしゃ]が遅[おく]れたんです。', '電車[でんしゃ]を遅[おく]れます。', '電車[でんしゃ]で遅[おく]れないですか。'], correctIndex: 0, explanation: '～んです supplies the requested background explanation.' },
    continuation: { text: 'れんが駅[えき]で新[あたら]しい傘[かさ]を買[か]ってくれたよ。', meaning: 'Ren bought us a new umbrella at the station.' },
    nextHook: 'Ren’s kindness leads naturally into giving and receiving expressions.',
  }),
  n5({
    number: 19,
    titleJapanese: '傘のお礼', titleEnglish: 'A Thank-You for the Umbrella',
    opening: 'Safe under the new umbrella, the group talks about small favors and who benefits from them.',
    concepts: [
      g('episode-19-giving', 'あげる・くれる', 'あげる・くれる', 'distinguish giving outward from giving to the speaker’s side', 'れんが私[わたし]たちに傘[かさ]をくれました。', 'Ren gave us an umbrella.'),
      g('episode-19-receiving', 'もらう', 'もらう', 'describe receiving something from someone', 'れんに傘[かさ]をもらいました。', 'We received an umbrella from Ren.'),
    ],
    curriculumGrammarIds: ['grammar-ageru', 'grammar-kureru', 'grammar-morau'],
    keywords: [v('episode-19-vocab-orei', 'お礼', 'おれい', 'thanks; return favor'), v('episode-19-vocab-kasa', '傘', 'かさ', 'umbrella')],
    dialogue: [
      { text: 'れんが傘[かさ]を買[か]ってくれて、助[たす]かったね。', meaning: 'Ren buying the umbrella really helped us.' },
      { text: '今度[こんど]、私[わたし]たちがれんにお礼[れい]をあげよう。', meaning: 'Yuki suggests giving Ren a thank-you gift next time.' },
    ],
    wrongDetails: ['Ren borrowed an umbrella from Yuki.', 'Yuki wants Ren to buy another umbrella tonight.'],
    build: { prompt: 'Describe receiving the umbrella from Ren.', parts: ['れんに', 'かさを', 'もらいました'], answer: 'れんに傘[かさ]をもらいました。', meaning: 'I received an umbrella from Ren.', explanation: 'With もらう, the giver can be marked by に or から.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the giver-viewpoint verb.', context: '友達[ともだち]が私[わたし]に本[ほん]を（　）。', options: ['あげました', 'くれました', 'もらいました'], correctIndex: 1, explanation: 'The friend gives toward 私, so くれました matches the speaker’s viewpoint.' },
    continuation: { text: '風邪[かぜ]をひかないように、早[はや]く帰[かえ]ったほうがいいよ。', meaning: 'We should get home early so we do not catch a cold.' },
    nextHook: 'Health advice introduces obligations, prohibitions, and what is better to do.',
  }),
  n5({
    number: 20,
    titleJapanese: '風邪をひかないで', titleEnglish: 'Do Not Catch a Cold',
    opening: 'You sneeze on the platform. Yuki gives practical advice while Ren checks the train time.',
    concepts: [
      g('episode-20-obligation', '～なくてはいけない／～なくちゃ', '～なくてはいけない／～なくちゃ', 'express obligation in formal and casual speech', '薬[くすり]を飲[の]まなくてはいけません。', 'You must take medicine.'),
      g('episode-20-advice', '～たほうがいい／～ないほうがいい', '～たほうがいい／～ないほうがいい', 'give positive or negative advice', '今日[きょう]は早[はや]く寝[ね]たほうがいいよ。', 'You should go to bed early today.'),
    ],
    curriculumGrammarIds: ['grammar-nakutehaikenai', 'grammar-nakutehanaranai', 'grammar-nakucha', 'grammar-tahougaii', 'grammar-naihougaii'],
    keywords: [v('episode-20-vocab-kusuri', '薬', 'くすり', 'medicine'), v('episode-20-vocab-kaze', '風邪', 'かぜ', 'a cold')],
    dialogue: [
      { text: '大丈夫[だいじょうぶ]？さっきから何度[なんど]もくしゃみしてるよ。', meaning: 'Yuki asks if you are okay because you keep sneezing.' },
      { text: '今夜[こんや]は無理[むり]をしないで、早[はや]く寝[ね]たほうがいい。', meaning: 'Yuki advises you not to overdo it and to sleep early tonight.' },
    ],
    wrongDetails: ['Yuki tells you to exercise all night.', 'Yuki says the last train has already left.'],
    build: { prompt: 'Give gentle health advice.', parts: ['きょうは', 'はやく', 'ねたほうがいいよ'], answer: '今日[きょう]は早[はや]く寝[ね]たほうがいいよ。', meaning: 'You should sleep early today.', explanation: 'Past plain form + ほうがいい gives a concrete recommendation.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the form expressing obligation.', context: '明日[あした]までに宿題[しゅくだい]を（　）。', options: ['しなくてはいけません', 'しないほうがいいです', 'してもいいです'], correctIndex: 0, explanation: 'A deadline plus ～なくてはいけません expresses something that must be done.' },
    continuation: { text: '家[いえ]に着[つ]いたら、もう一度[いちど]連絡[れんらく]してね。', meaning: 'Message me again when you get home.' },
    nextHook: 'Back home, “already” and “not yet” return in a review conversation.',
  }),
  n5({
    number: 21,
    titleJapanese: 'もう着いた？', titleEnglish: 'Home Yet?',
    opening: 'Yuki checks that everyone arrived safely. The exchange revisits a key contrast from Episode 1 at a higher speed.',
    concepts: [
      g('episode-21-already', 'もう＋肯定', 'もう＋こうてい', 'say that something has already happened', 'もう家[いえ]に着[つ]いたよ。', 'I already arrived home.'),
      g('episode-21-not-yet', 'まだ＋否定', 'まだ＋ひてい', 'say that something has not happened yet', 'れんはまだ着[つ]いていません。', 'Ren has not arrived yet.'),
    ],
    curriculumGrammarIds: ['grammar-mou', 'grammar-mada', 'grammar-mada-teimasen'],
    keywords: [v('episode-21-vocab-tsuku', '着', 'つ', 'arrive'), v('episode-21-vocab-renraku', '連絡', 'れんらく', 'contact')],
    dialogue: [
      { text: 'もう家[いえ]に着[つ]いた？', meaning: 'Yuki asks whether you are home already.' },
      { text: 'れんからはまだ連絡[れんらく]が来[き]てないんだ。', meaning: 'Yuki has not heard from Ren yet.' },
    ],
    wrongDetails: ['Ren called twice already.', 'Yuki is still at the museum.'],
    build: { prompt: 'Tell Yuki you are already home.', parts: ['うん', 'もういえに', 'ついたよ'], answer: 'うん、もう家[いえ]に着[つ]いたよ。', meaning: 'Yeah, I’m already home.', explanation: 'もう naturally pairs with an affirmative completed form.' },
    exam: { format: 'appropriate-response', prompt: 'Choose the natural answer.', context: 'もう晩[ばん]ご飯[はん]を食[た]べましたか。', options: ['はい、もう食[た]べました。', 'はい、まだ食[た]べません。', 'いいえ、もう食[た]べませんでした。'], correctIndex: 0, explanation: 'The affirmative answer repeats もう with the completed past.' },
    continuation: { text: 'れんも今[いま]着[つ]いたって。これで安心[あんしん]だね。', meaning: 'Ren says he just arrived too. Now we can relax.' },
    nextHook: 'The next morning, shopping quantities and limits become essential.',
  }),
  n5({
    number: 22,
    titleJapanese: 'これだけください', titleEnglish: 'Just These, Please',
    opening: 'You shop for breakfast at a neighborhood market and must understand quantities, limits, and approximate amounts.',
    concepts: [
      g('episode-22-limits', 'だけ・まで', 'だけ・まで', 'express “only” and an endpoint', 'パンは二[ふた]つだけ買[か]います。', 'I will buy only two breads.'),
      g('episode-22-approximation', 'くらい・たくさん', 'くらい・たくさん', 'express an approximate amount or a large quantity', 'りんごを五[いつ]つくらい買[か]いました。', 'I bought about five apples.'),
    ],
    curriculumGrammarIds: ['grammar-dake', 'grammar-kurai1', 'grammar-takusan', 'grammar-noun-made'],
    keywords: [v('episode-22-vocab-kau', '買', 'か', 'buy'), v('episode-22-vocab-hitotsu', '一', 'ひと', 'one item')],
    dialogue: [
      { text: '朝[あさ]ご飯[はん]は軽[かる]くていいから、パンは二[ふた]つだけにしよう。', meaning: 'A light breakfast is enough, so Yuki suggests buying only two breads.' },
      { text: '果物[くだもの]は三日分[みっかぶん]くらい買[か]っておきたいね。', meaning: 'Yuki wants roughly three days’ worth of fruit.' },
    ],
    wrongDetails: ['Yuki wants twenty breads.', 'Yuki says fruit cannot be stored.'],
    build: { prompt: 'Ask for only these items.', parts: ['これだけ', 'ください'], answer: 'これだけください。', meaning: 'Just these, please.', explanation: 'だけ follows the noun or amount it limits.' },
    exam: { format: 'vocabulary-cloze', prompt: 'Choose the approximate amount.', context: '駅[えき]まで十分[じゅっぷん]（　）です。', options: ['くらい', 'だけを', 'たくさんに'], correctIndex: 0, explanation: 'くらい follows a quantity to mean “about.”' },
    continuation: { text: '買[か]い物[もの]が終[お]わったら、赤[あか]いのを一[ひと]つ分[わ]けてあげるね。', meaning: 'After shopping, I’ll share one of the red ones with you.' },
    nextHook: 'Choosing “the red one” reveals how Japanese turns descriptions into noun-like phrases.',
  }),
  n5({
    number: 23,
    titleJapanese: '赤いのはどれ？', titleEnglish: 'Which One Is Red?',
    opening: 'At the fruit stand, the seller points to several varieties without repeating their names.',
    concepts: [
      g('episode-23-nominalizer', '～の（名詞化）', '～の', 'replace a known noun or nominalize an action', '赤[あか]いのを一[ひと]つください。', 'Please give me one red one.'),
      g('episode-23-focus', '形容詞＋のは', 'けいようし＋のは', 'make a description the topic', '甘[あま]いのは、このりんごです。', 'The sweet one is this apple.'),
    ],
    curriculumGrammarIds: ['grammar-no-nominalizer', 'grammar-adjective-noha', 'grammar-no-possession-marker'],
    keywords: [v('episode-23-vocab-akai', '赤', 'あか', 'red'), v('episode-23-vocab-amai', '甘', 'あま', 'sweet')],
    dialogue: [
      { text: '赤[あか]いのと青[あお]いの、どっちが甘[あま]いですか。', meaning: 'You ask whether the red or green kind is sweeter.' },
      { text: '甘[あま]いのは赤[あか]いほうですよ。', meaning: 'The seller says the red ones are sweeter.' },
    ],
    wrongDetails: ['The green ones are the sweetest.', 'The seller has no apples today.'],
    build: { prompt: 'Ask for one red one.', parts: ['あかいのを', 'ひとつ', 'ください'], answer: '赤[あか]いのを一[ひと]つください。', meaning: 'Please give me one red one.', explanation: 'の replaces the understood noun りんご and prevents unnecessary repetition.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the nominalizer.', context: '私[わたし]が買[か]った（　）はこれです。', options: ['の', 'まで', 'へ'], correctIndex: 0, explanation: 'の turns 買った into “the one that I bought.”' },
    continuation: { text: '袋[ふくろ]を持[も]っている人[ひと]が、先[さき]に帰[かえ]ったよ。', meaning: 'The person carrying the bag went home first.' },
    nextHook: 'Finding that person requires reading a relative clause before the noun.',
  }),
  n5({
    number: 24,
    titleJapanese: '袋を持っている人', titleEnglish: 'The Person With the Bag',
    opening: 'A bag was left behind. The friends identify its owner by describing people and things precisely.',
    concepts: [
      g('episode-24-relative', '普通形＋名詞', 'ふつうけい＋めいし', 'modify a noun with a clause placed before it', 'あそこにいる人[ひと]は店員[てんいん]です。', 'The person over there is a shop clerk.'),
      g('episode-24-relative-state', '～た／～ている＋名詞', '～た／～ている＋めいし', 'describe a noun by a completed action or continuing state', '袋[ふくろ]を持[も]っていた人[ひと]を見[み]ました。', 'I saw the person who was carrying the bag.'),
    ],
    curriculumGrammarIds: ['grammar-verb-ta-teiru-noun', 'grammar-gaaru-noun'],
    keywords: [v('episode-24-vocab-fukuro', '袋', 'ふくろ', 'bag'), v('episode-24-vocab-tenin', '店員', 'てんいん', 'shop clerk')],
    dialogue: [
      { text: 'さっき、この袋[ふくろ]を持[も]っていた人[ひと]を見[み]た？', meaning: 'Yuki asks whether you saw the person who had this bag.' },
      { text: '青[あお]い帽子[ぼうし]をかぶっていた人[ひと]なら、駅[えき]のほうへ行[い]ったよ。', meaning: 'The person in a blue hat went toward the station.' },
    ],
    wrongDetails: ['A station worker brought the bag tomorrow.', 'The person in the red hat entered the shop.'],
    build: { prompt: 'Identify the person you saw.', parts: ['ふくろを', 'もっていたひとを', 'みました'], answer: '袋[ふくろ]を持[も]っていた人[ひと]を見[み]ました。', meaning: 'I saw the person who was carrying the bag.', explanation: 'The whole clause 袋を持っていた comes before and modifies 人.' },
    exam: { format: 'sentence-ordering', prompt: 'Choose the natural noun-modifying order.', context: 'これは（　）本[ほん]です。', options: ['昨日[きのう]買[か]った', '買[か]った昨日[きのう]を', '昨日[きのう]を買[か]います'], correctIndex: 0, explanation: 'A relative clause directly precedes the noun without の.' },
    continuation: { text: '駅員[えきいん]さんに聞[き]いたら、持[も]ち主[ぬし]が見[み]つかったって。', meaning: 'After asking the station staff, Yuki heard that the owner was found.' },
    nextHook: 'Reported speech and casual quotation let the good news travel quickly.',
  }),
  n5({
    number: 25,
    titleJapanese: '見つかったって', titleEnglish: 'They Found the Owner',
    opening: 'Yuki relays what the station worker said, while Ren checks whether everyone understood the message.',
    concepts: [
      g('episode-25-quotation', '～と＋言う／思う', '～と＋いう／おもう', 'mark quoted content before a reporting or thinking verb', '駅員[えきいん]さんは「見[み]つかりました」と言[い]いました。', 'The station worker said, “It was found.”'),
      g('episode-25-casual-quote', '～って', '～って', 'mark a casual quotation or reported statement', '持[も]ち主[ぬし]が見[み]つかったって。', 'They say the owner was found.'),
    ],
    curriculumGrammarIds: ['grammar-to-quotation-marker', 'grammar-tte', 'grammar-darou', 'grammar-deshou'],
    keywords: [v('episode-25-vocab-ekiin', '駅員', 'えきいん', 'station employee'), v('episode-25-vocab-mochinushi', '持', 'も', 'owner; holder')],
    dialogue: [
      { text: '駅員[えきいん]さんが「もう大丈夫[だいじょうぶ]です」って言[い]ってたよ。', meaning: 'The station worker said everything is okay now.' },
      { text: '持[も]ち主[ぬし]が見[み]つかったって聞[き]いて、安心[あんしん]した。', meaning: 'Yuki felt relieved to hear that the owner was found.' },
    ],
    wrongDetails: ['The station worker lost another bag.', 'Yuki thinks the owner will never come.'],
    build: { prompt: 'Report the station worker’s words politely.', parts: ['えきいんさんは', 'みつかりましたと', 'いいました'], answer: '駅員[えきいん]さんは「見[み]つかりました」と言[い]いました。', meaning: 'The station worker said, “It was found.”', explanation: 'と closes the quoted content before 言いました.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the quotation marker.', context: '明日[あした]は雨[あめ]だ（　）思[おも]います。', options: ['に', 'と', 'で'], correctIndex: 1, explanation: 'A plain-form thought is followed by と before 思います.' },
    continuation: { text: 'これで今日[きょう]の事件[じけん]は終[お]わり。明日[あした]は試験[しけん]みたいに復習[ふくしゅう]しよう。', meaning: 'That ends today’s incident. Tomorrow, let’s review as if it were an exam.' },
    nextHook: 'The N5 finale combines kanji, vocabulary, grammar, reading, and listening-style tasks.',
  }),
  n5({
    number: 26,
    titleJapanese: 'N5への挑戦', titleEnglish: 'The N5 Challenge',
    opening: 'Yuki turns a day around town into a calm N5 rehearsal. Every clue comes from language you met in the story.',
    concepts: [
      g('episode-26-question-words', '誰・誰か・何か', 'だれ・だれか・なにか', 'distinguish an open question from an unspecified person or thing', '誰[だれ]かが入口[いりぐち]で待[ま]っています。', 'Someone is waiting at the entrance.'),
      g('episode-26-listing', 'と・や・か', 'と・や・か', 'make complete lists, sample lists, or alternatives', 'パンや果物[くだもの]を買[か]います。', 'I buy things such as bread and fruit.'),
    ],
    curriculumGrammarIds: ['grammar-誰', 'grammar-誰ka', 'grammar-nanika', 'grammar-to-and-marker', 'grammar-to-accompaniment-marker', 'grammar-ya', 'grammar-ka-alternative-marker', 'grammar-ka-question-marker', 'grammar-yo', 'grammar-ne', 'grammar-nisuru', 'grammar-ninaru', 'grammar-sugiru', 'grammar-kekkou'],
    keywords: [v('episode-26-vocab-shiken', '試験', 'しけん', 'exam'), v('episode-26-vocab-fukushuu', '復習', 'ふくしゅう', 'review')],
    dialogue: [
      { text: '今日[きょう]はN5の問題[もんだい]を少[すこ]しずつ解[と]いてみよう。', meaning: 'Today, Yuki suggests solving N5 questions little by little.' },
      { text: '漢字[かんじ]だけじゃなくて、文法[ぶんぽう]や読解[どっかい]も出[で]るよ。', meaning: 'The practice includes not only kanji but also grammar and reading.' },
    ],
    wrongDetails: ['The practice contains only kanji.', 'Yuki has canceled the study session.'],
    build: { prompt: 'Say that someone is waiting at the entrance.', parts: ['だれかが', 'いりぐちで', 'まっています'], answer: '誰[だれ]かが入口[いりぐち]で待[ま]っています。', meaning: 'Someone is waiting at the entrance.', explanation: '誰か is an unspecified person; 誰 alone asks “who?”' },
    exam: { format: 'integrated-short-reading', prompt: 'Choose what you should do first.', context: '図書館[としょかん]は九時[くじ]に開[あ]きます。入口[いりぐち]でゆきさんと会[あ]ってから、一緒[いっしょ]に入[はい]ります。', options: ['九時[くじ]前[まえ]に一人[ひとり]で入[はい]ります。', '入口[いりぐち]でゆきさんに会[あ]います。', '図書館[としょかん]で朝[あさ]ご飯[はん]を作[つく]ります。'], correctIndex: 1, explanation: 'The passage explicitly says to meet Yuki at the entrance before entering together.' },
    continuation: { text: 'N5の土台[どだい]はできたね。次[つぎ]は、もっと長[なが]い話[はなし]や細[こま]かい気持[きも]ちを日本語[にほんご]で伝[つた]えよう。', meaning: 'Your N5 foundation is ready. Next we will express longer stories and finer feelings in Japanese.' },
    nextHook: 'The N4 arc begins with moving into a new apartment and describing choices in greater detail.',
  }),
];
