import type {
  AuthoredEpisodeDefinition,
  EpisodeConcept,
  EpisodeKeyword,
} from './authored-episode-factory';

const g = (
  id: string,
  pattern: string,
  reading: string,
  meaning: string,
  example: string,
  exampleMeaning: string,
): EpisodeConcept => ({ id, pattern, reading, meaning, example, exampleMeaning });

const v = (id: string, japanese: string, reading: string, meaning: string): EpisodeKeyword => ({ id, japanese, reading, meaning });

type N4Seed = Omit<AuthoredEpisodeDefinition, 'level' | 'comprehension'> & { wrongDetails: [string, string] };

function n4(seed: N4Seed): AuthoredEpisodeDefinition {
  const { wrongDetails, ...definition } = seed;
  return {
    ...definition,
    level: 'N4',
    comprehension: {
      prompt: 'Which interpretation fits the conversation?',
      correct: definition.dialogue[1].meaning ?? 'The second message gives the key detail.',
      distractors: wrongDetails,
      explanation: 'Correct. The connective, viewpoint, and final predicate support this interpretation.',
    },
  };
}

/** Episodes 27–51 form the N4 half of the new fifty-episode course. */
export const n4EpisodeDefinitions: AuthoredEpisodeDefinition[] = [
  n4({
    number: 27,
    titleJapanese: '新しい部屋', titleEnglish: 'A New Apartment',
    opening: 'You are ready to leave the temporary room. Yuki and Ren help compare two apartments.',
    concepts: [
      g('episode-27-nominalization', '～こと・～さ', '～こと・～さ', 'turn an action into a noun or an adjective into a measurable quality', '駅[えき]に近[ちか]いことが大切[たいせつ]です。', 'Being close to the station is important.'),
      g('episode-27-focus', '～のは～だ', '～のは～だ', 'focus or identify information about a nominalized clause', '気[き]になるのは家賃[やちん]の高[たか]さです。', 'What concerns me is how high the rent is.'),
    ],
    curriculumGrammarIds: ['grammar-n4-koto-nominalizer', 'grammar-n4-sa-nominalizer', 'grammar-n4-nowa-da'],
    keywords: [v('episode-27-vocab-yachin', '家賃', 'やちん', 'rent'), v('episode-27-vocab-taisetstu', '大切', 'たいせつ', 'important')],
    dialogue: [
      { text: '一人[ひとり]で住[す]むなら、駅[えき]に近[ちか]いことも大切[たいせつ]だよ。', meaning: 'For living alone, being near the station is also important.' },
      { text: 'でも、気[き]になるのは家賃[やちん]の高[たか]さだね。', meaning: 'The concern is how high the rent is.' },
    ],
    wrongDetails: ['The apartment is free.', 'Yuki only cares about the color of the walls.'],
    build: { prompt: 'State what concerns you.', parts: ['きになるのは', 'やちんのたかさです'], answer: '気[き]になるのは家賃[やちん]の高[たか]さです。', meaning: 'What concerns me is how high the rent is.', explanation: 'のは presents the focused topic; ～さ turns 高い into the noun “height/degree.”' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the nominalized quality.', context: 'この部屋[へや]の明[あか]る（　）が好[す]きです。', options: ['さ', 'こと', 'ので'], correctIndex: 0, explanation: 'The adjective stem 明る + さ names the degree or quality of brightness.' },
    continuation: { text: '「青葉[あおば]ハイツ」という建物[たてもの]も見[み]に行[い]こう。', meaning: 'Let’s also look at a building called Aoba Heights.' },
    nextHook: 'Names, opinions, and reported information guide the next apartment visit.',
  }),
  n4({
    number: 28,
    titleJapanese: '青葉ハイツという所', titleEnglish: 'A Place Called Aoba Heights',
    opening: 'The group reads a listing and compares what the agent says with what a neighbor has heard.',
    concepts: [
      g('episode-28-quotation', '～という／～ということ', '～という／～ということ', 'name something or package quoted information', '青葉[あおば]ハイツという建物[たてもの]です。', 'It is a building called Aoba Heights.'),
      g('episode-28-reporting', '～と思う・～と聞く・～と言われている', '～とおもう・～ときく・～といわれている', 'express an opinion or report information with different evidence', 'この辺[へん]は静[しず]かだと聞[き]きました。', 'I heard this neighborhood is quiet.'),
    ],
    curriculumGrammarIds: ['grammar-n4-to-iu', 'grammar-n4-to-iu-koto', 'grammar-n4-to-omou', 'grammar-n4-to-kiku', 'grammar-n4-to-iwarete-iru', 'grammar-n4-ka-dou-ka'],
    keywords: [v('episode-28-vocab-tatemono', '建物', 'たてもの', 'building'), v('episode-28-vocab-fudousan', '不動産', 'ふどうさん', 'real estate')],
    dialogue: [
      { text: '不動産屋[ふどうさんや]さんは、買[か]い物[もの]に便利[べんり]だと言[い]ってたよ。', meaning: 'The agent said the area is convenient for shopping.' },
      { text: '近所[きんじょ]の人[ひと]からも、夜[よる]は静[しず]かだと聞[き]いた。', meaning: 'Yuki also heard from a neighbor that it is quiet at night.' },
    ],
    wrongDetails: ['The agent warned that no shops are nearby.', 'The neighbor said nights are extremely noisy.'],
    build: { prompt: 'Report what you heard about the area.', parts: ['このへんは', 'しずかだと', 'ききました'], answer: 'この辺[へん]は静[しず]かだと聞[き]きました。', meaning: 'I heard this neighborhood is quiet.', explanation: 'The plain statement 静かだ is quoted with と before 聞きました.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the embedded whether form.', context: '駅[えき]から近[ちか]い（　）調[しら]べます。', options: ['かどうか', 'という人[ひと]', 'と思[おも]うを'], correctIndex: 0, explanation: '～かどうか embeds a yes/no question: whether it is close.' },
    continuation: { text: '返事[へんじ]は明日[あした]までにすればいいって。', meaning: 'They said you can reply by tomorrow.' },
    nextHook: 'A deadline and a busy day bring time-span expressions into play.',
  }),
  n4({
    number: 29,
    titleJapanese: '返事は明日までに', titleEnglish: 'An Answer by Tomorrow',
    opening: 'You need to decide on the apartment while still handling work and errands.',
    concepts: [
      g('episode-29-time-span', '～間／～間に', '～あいだ／～あいだに', 'contrast an action throughout a period with an event inside it', '昼休[ひるやす]みの間[あいだ]に電話[でんわ]します。', 'I will call during the lunch break.'),
      g('episode-29-sequence-deadline', '～後で・～頃・～までに・～ながら', '～あとで・～ごろ・～までに・～ながら', 'sequence events, give approximate times and deadlines, or overlap actions', '仕事[しごと]が終[お]わった後[あと]で、六時[ろくじ]頃[ごろ]に返事[へんじ]します。', 'After work, I will reply around six.'),
    ],
    curriculumGrammarIds: ['grammar-n4-aida', 'grammar-n4-aida-ni', 'grammar-n4-ato-de', 'grammar-n4-koro', 'grammar-n4-made-ni', 'grammar-n4-nagara', 'grammar-n4-koto-ga-aru-occasional', 'grammar-n4-ta-bakari'],
    keywords: [v('episode-29-vocab-hiruyasumi', '昼休', 'ひるやす', 'lunch break'), v('episode-29-vocab-henji', '返事', 'へんじ', 'reply')],
    dialogue: [
      { text: '昼休[ひるやす]みの間[あいだ]に契約[けいやく]の条件[じょうけん]を確認[かくにん]しておくね。', meaning: 'Yuki will check the contract terms during lunch.' },
      { text: 'あなたは仕事[しごと]が終[お]わった後[あと]で、六時[ろくじ]頃[ごろ]に返事[へんじ]できる？', meaning: 'Yuki asks whether you can reply around six after work.' },
    ],
    wrongDetails: ['Yuki needs the reply before lunch starts.', 'The contract has already been canceled.'],
    build: { prompt: 'Promise a reply around six after work.', parts: ['しごとがおわったあとで', 'ろくじごろに', 'へんじします'], answer: '仕事[しごと]が終[お]わった後[あと]で、六時[ろくじ]頃[ごろ]に返事[へんじ]します。', meaning: 'After work, I will reply around six.', explanation: '後で gives the sequence; 頃 softens the clock time to “around.”' },
    exam: { format: 'grammar-contrast', prompt: 'Choose the sentence where one event occurs within the period.', context: '母[はは]が料理[りょうり]をしている（　）、電話[でんわ]が鳴[な]りました。', options: ['間[あいだ]', '間[あいだ]に', 'までに'], correctIndex: 1, explanation: 'The call is a punctual event inside the longer cooking period, so 間に is required.' },
    continuation: { text: '引[ひ]っ越[こ]しを手伝[てつだ]ってくれる人[ひと]も探[さが]さないとね。', meaning: 'We also need to find someone who will help with the move.' },
    nextHook: 'Asking for and receiving favors becomes the center of the move.',
  }),
  n4({
    number: 30,
    titleJapanese: '手伝ってくれる？', titleEnglish: 'Will You Help Me Move?',
    opening: 'Ren offers a van, Yuki offers to pack dishes, and you learn to keep the direction of favors clear.',
    concepts: [
      g('episode-30-benefactive', '～てあげる・～てくれる・～てもらう', '～てあげる・～てくれる・～てもらう', 'show who performs an action and who benefits', 'れんが車[くるま]を出[だ]してくれます。', 'Ren will bring his car for us.'),
      g('episode-30-polite-request', '～ていただけませんか', '～ていただけませんか', 'make a respectful, indirect request', 'この箱[はこ]を運[はこ]んでいただけませんか。', 'Could you please carry this box?'),
    ],
    curriculumGrammarIds: ['grammar-n4-te-ageru', 'grammar-n4-te-kureru', 'grammar-n4-te-morau', 'grammar-n4-te-itadakemasen-ka', 'grammar-n4-te-yaru'],
    keywords: [v('episode-30-vocab-hako', '箱', 'はこ', 'box'), v('episode-30-vocab-hakobu', '運', 'はこ', 'carry; transport')],
    dialogue: [
      { text: 'れんが車[くるま]を出[だ]してくれることになったよ。', meaning: 'It has been decided that Ren will provide his car for the move.' },
      { text: '私[わたし]は食器[しょっき]を包[つつ]んであげるね。', meaning: 'Yuki will wrap the dishes for you.' },
    ],
    wrongDetails: ['Ren wants you to lend him a car.', 'Yuki asks you to buy new dishes.'],
    build: { prompt: 'Ask politely for help with a box.', parts: ['このはこを', 'はこんで', 'いただけませんか'], answer: 'この箱[はこ]を運[はこ]んでいただけませんか。', meaning: 'Could you please carry this box?', explanation: '～ていただけませんか frames the favor as something you would gratefully receive.' },
    exam: { format: 'viewpoint-choice', prompt: 'Choose the sentence from the speaker-beneficiary viewpoint.', context: '友達[ともだち]が私[わたし]の荷物[にもつ]を持[も]ちました。', options: ['友達[ともだち]に持[も]ってあげました。', '友達[ともだち]が持[も]ってくれました。', '友達[ともだち]を持[も]ってもらいました。'], correctIndex: 1, explanation: 'The friend acts for the speaker, so ～てくれました is the natural viewpoint.' },
    continuation: { text: '明日[あした]の朝[あさ]、七時[しちじ]から荷造[にづく]りを始[はじ]めよう。', meaning: 'Let’s start packing at seven tomorrow morning.' },
    nextHook: 'The move unfolds through beginnings, sudden starts, continuations, and finishes.',
  }),
  n4({
    number: 31,
    titleJapanese: '引っ越し開始', titleEnglish: 'Moving Day Begins',
    opening: 'Boxes fill the room. The work starts calmly, then rain suddenly begins outside.',
    concepts: [
      g('episode-31-phase-start', '～始める・～出す', '～はじめる・～だす', 'distinguish a deliberate beginning from a sudden onset', '七時[しちじ]に荷物[にもつ]を運[はこ]び始[はじ]めました。', 'We began moving the luggage at seven.'),
      g('episode-31-phase-duration', '～続ける・～終わる', '～つづける・～おわる', 'express continuing or finishing an action', '全部[ぜんぶ]の箱[はこ]を運[はこ]び終[お]わりました。', 'We finished carrying all the boxes.'),
    ],
    curriculumGrammarIds: ['grammar-n4-hajimeru', 'grammar-n4-dasu', 'grammar-n4-owaru', 'grammar-n4-tsuzukeru'],
    keywords: [v('episode-31-vocab-nimotsu', '荷物', 'にもつ', 'luggage'), v('episode-31-vocab-zenbu', '全部', 'ぜんぶ', 'all')],
    dialogue: [
      { text: '荷物[にもつ]を運[はこ]び始[はじ]めたとたん、雨[あめ]が降[ふ]り出[だ]したね。', meaning: 'Just as the move began, it suddenly started raining.' },
      { text: 'でも、三人[さんにん]で運[はこ]び続[つづ]けたから、昼[ひる]前[まえ]に終[お]わったよ。', meaning: 'Because the three kept going, they finished before noon.' },
    ],
    wrongDetails: ['They stopped before carrying any boxes.', 'The move took until midnight.'],
    build: { prompt: 'Say that all the carrying is finished.', parts: ['ぜんぶのはこを', 'はこびおわりました'], answer: '全部[ぜんぶ]の箱[はこ]を運[はこ]び終[お]わりました。', meaning: 'We finished carrying all the boxes.', explanation: 'Attach 終わる to the ます-stem 運び to mark completion of that action.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose the sudden-onset expression.', context: '赤[あか]ちゃんが急[きゅう]に泣[な]き（　）。', options: ['始[はじ]めました', '出[だ]しました', '終[お]わりました'], correctIndex: 1, explanation: '～出す is especially natural for an abrupt, noticeable beginning.' },
    continuation: { text: '家具[かぐ]を置[お]く前[まえ]に、配置[はいち]を考[かんが]えておこう。', meaning: 'Before placing the furniture, let’s plan the layout in advance.' },
    nextHook: 'Preparation, trying things, and resulting states shape the new room.',
  }),
  n4({
    number: 32,
    titleJapanese: '部屋を整えておく', titleEnglish: 'Getting the Room Ready',
    opening: 'You test several furniture layouts and prepare the apartment before unpacking everything.',
    concepts: [
      g('episode-32-prep-try', '～ておく・～てみる', '～ておく・～てみる', 'do something in advance or try an action', '机[つくえ]を窓[まど]の近[ちか]くに置[お]いてみます。', 'I will try placing the desk near the window.'),
      g('episode-32-result', '～てしまう・～てある・～まま', '～てしまう・～てある・～まま', 'express completion or regret, a prepared result, or an unchanged state', '窓[まど]は開[あ]けたままにしないで。', 'Do not leave the window open.'),
    ],
    curriculumGrammarIds: ['grammar-n4-te-oku', 'grammar-n4-te-miru', 'grammar-n4-te-shimau', 'grammar-n4-te-aru', 'grammar-n4-mama'],
    keywords: [v('episode-32-vocab-tsukue', '机', 'つくえ', 'desk'), v('episode-32-vocab-mado', '窓', 'まど', 'window')],
    dialogue: [
      { text: '大[おお]きい家具[かぐ]を入[い]れる前[まえ]に、床[ゆか]を掃除[そうじ]しておこう。', meaning: 'Let’s clean the floor in advance before bringing in large furniture.' },
      { text: 'カーテンはもう掛[か]けてあるから、今夜[こんや]から住[す]めるよ。', meaning: 'The curtains have already been put up, so the room is ready to live in tonight.' },
    ],
    wrongDetails: ['The room cannot be used for another month.', 'Yuki says to remove all the curtains.'],
    build: { prompt: 'Suggest trying the desk by the window.', parts: ['つくえを', 'まどのちかくに', 'おいてみます'], answer: '机[つくえ]を窓[まど]の近[ちか]くに置[お]いてみます。', meaning: 'I will try placing the desk near the window.', explanation: '～てみる means trying an action to see its result.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the prepared-result form.', context: '会議[かいぎ]の資料[しりょう]は机[つくえ]に置[お]いて（　）。', options: ['あります', 'います', 'しまいますか'], correctIndex: 0, explanation: '～てある describes an intentional action whose result remains.' },
    continuation: { text: '足[た]りない物[もの]を買[か]ってきて、少[すこ]しずつ暮[く]らしやすくしていこう。', meaning: 'Let’s buy what is missing and gradually make the place easier to live in.' },
    nextHook: 'Movement toward the present and future, plus “just now” phases, carry the story forward.',
  }),
  n4({
    number: 33,
    titleJapanese: '今ちょうど出るところ', titleEnglish: 'Just About to Leave',
    opening: 'You head out for household supplies while messages track actions before, during, and just after they happen.',
    concepts: [
      g('episode-33-directional-aspect', '～てくる・～ていく', '～てくる・～ていく', 'show an action linked to coming back or a change continuing forward', '近[ちか]くの店[みせ]で電球[でんきゅう]を買[か]ってきます。', 'I will go buy a light bulb nearby and come back.'),
      g('episode-33-tokoro', '～ところ・～ているところ・～たところ', '～ところ・～ているところ・～たところ', 'locate an action just before, during, or just after it', '今[いま]、家[いえ]を出[で]るところです。', 'I am just about to leave home.'),
    ],
    curriculumGrammarIds: ['grammar-n4-te-kuru', 'grammar-n4-te-iku', 'grammar-n4-tokoro', 'grammar-n4-teiru-tokoro', 'grammar-n4-ta-tokoro'],
    keywords: [v('episode-33-vocab-denkyuu', '電球', 'でんきゅう', 'light bulb'), v('episode-33-vocab-choudo', '今', 'いま', 'now')],
    dialogue: [
      { text: 'いま、どこ？もう店[みせ]に着[つ]いた？', meaning: 'Yuki asks where you are and whether you reached the shop.' },
      { text: 'まだ。ちょうど家[いえ]を出[で]るところ。', meaning: 'You have not left yet; you are just about to go.' },
    ],
    wrongDetails: ['You have just returned from the shop.', 'You are currently paying at the register.'],
    build: { prompt: 'Say you will buy a bulb and return.', parts: ['ちかくのみせで', 'でんきゅうを', 'かってきます'], answer: '近[ちか]くの店[みせ]で電球[でんきゅう]を買[か]ってきます。', meaning: 'I will go buy a light bulb nearby and come back.', explanation: '～てくる combines the errand with movement back toward the reference point.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose “in the middle of doing.”', context: 'いま、晩[ばん]ご飯[はん]を（　）ところです。', options: ['作[つく]る', '作[つく]っている', '作[つく]った'], correctIndex: 1, explanation: '～ているところ pinpoints an action in progress right now.' },
    continuation: { text: '雨[あめ]が降[ふ]ったら、無理[むり]に出[で]なくてもいいよ。', meaning: 'If it rains, you do not have to force yourself to go out.' },
    nextHook: 'Different kinds of “if” determine what happens when conditions change.',
  }),
  n4({
    number: 34,
    titleJapanese: '雨ならどうする？', titleEnglish: 'What If It Rains?',
    opening: 'The sky darkens again. The friends compare general rules, hypothetical plans, and advice tied to conditions.',
    concepts: [
      g('episode-34-conditionals', '～ば・～たら・～と・～なら', '～ば・～たら・～と・～なら', 'choose a conditional based on logic, sequence, automatic result, or a stated premise', '雨[あめ]が降[ふ]ったら、明日[あした]買[か]いに行[い]きます。', 'If it rains, I will go buy it tomorrow.'),
      g('episode-34-case', '～場合は', '～ばあいは', 'state what to do in a particular case', '遅[おく]れる場合[ばあい]は、連絡[れんらく]してください。', 'If you will be late, please contact me.'),
    ],
    curriculumGrammarIds: ['grammar-n4-ba', 'grammar-n4-tara', 'grammar-n4-to-conditional', 'grammar-n4-nara', 'grammar-n4-baai-wa'],
    keywords: [v('episode-34-vocab-baai', '場合', 'ばあい', 'case; situation'), v('episode-34-vocab-okureru', '遅', 'おく', 'be late')],
    dialogue: [
      { text: '雨[あめ]なら、駅前[えきまえ]の店[みせ]に変[か]えようか。', meaning: 'If rain is the situation, Yuki suggests switching to the station shop.' },
      { text: 'あの店[みせ]なら、駅[えき]を出[で]るとすぐ見[み]つかるよ。', meaning: 'That shop is visible as soon as you leave the station.' },
    ],
    wrongDetails: ['The shop is far from every station.', 'Yuki wants to wait outside regardless of rain.'],
    build: { prompt: 'State the plan if it rains.', parts: ['あめがふったら', 'あした', 'かいにいきます'], answer: '雨[あめ]が降[ふ]ったら、明日[あした]買[か]いに行[い]きます。', meaning: 'If it rains, I will go buy it tomorrow.', explanation: '～たら works naturally for a future condition followed by a chosen action.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose the automatic-result conditional.', context: 'このボタンを押[お]す（　）、ドアが開[あ]きます。', options: ['なら', 'と', 'たらどう'], correctIndex: 1, explanation: '～と is natural for a repeatable or automatic result.' },
    continuation: { text: '迷[まよ]ったら、店員[てんいん]さんに聞[き]いたらどう？', meaning: 'If you are unsure, why not ask a clerk?' },
    nextHook: 'Concession and advice help when a plan does not go smoothly.',
  }),
  n4({
    number: 35,
    titleJapanese: '聞いてみたら？', titleEnglish: 'Why Not Ask?',
    opening: 'The exact light bulb is not on the shelf. You need advice even if asking feels awkward.',
    concepts: [
      g('episode-35-concession', '～ても', '～ても', 'say that a result holds even under a condition', '高[たか]くても、長[なが]く使[つか]える物[もの]がいいです。', 'Even if it is expensive, I want something that lasts.'),
      g('episode-35-advice', '～たらどう／～たらいいですか', '～たらどう／～たらいいですか', 'offer advice or ask what action would be good', 'どれを選[えら]んだらいいですか。', 'Which one should I choose?'),
    ],
    curriculumGrammarIds: ['grammar-n4-temo-concession', 'grammar-n4-tara-dou', 'grammar-n4-tara-ii-desu-ka'],
    keywords: [v('episode-35-vocab-erabu', '選', 'えら', 'choose'), v('episode-35-vocab-tsukaeru', '使', 'つか', 'use')],
    dialogue: [
      { text: '店員[てんいん]さんに写真[しゃしん]を見[み]せたらどう？', meaning: 'Yuki suggests showing the photo to a clerk.' },
      { text: '形[かたち]が同[おな]じでも、明[あか]るさが違[ちが]うことがあるからね。', meaning: 'Even with the same shape, brightness can differ.' },
    ],
    wrongDetails: ['All bulbs with the same shape have identical brightness.', 'Yuki tells you to hide the photo.'],
    build: { prompt: 'Ask the clerk which item you should choose.', parts: ['どれを', 'えらんだら', 'いいですか'], answer: 'どれを選[えら]んだらいいですか。', meaning: 'Which one should I choose?', explanation: 'Question word + ～たらいいですか asks for practical guidance.' },
    exam: { format: 'appropriate-response', prompt: 'Choose the natural advice.', context: '道[みち]が分[わ]からないんです。', options: ['地図[ちず]を見[み]たらどうですか。', '道[みち]でも分[わ]かります。', '分[わ]からなくても道[みち]でした。'], correctIndex: 0, explanation: '～たらどうですか offers a reasonable action in response to the problem.' },
    continuation: { text: '帰[かえ]ったら、説明書[せつめいしょ]も読[よ]んでほしいな。', meaning: 'When you get home, I would like you to read the instructions too.' },
    nextHook: 'Instructions distinguish what is necessary, compulsory, optional, and requested.',
  }),
  n4({
    number: 36,
    titleJapanese: '説明書を読んで', titleEnglish: 'Read the Instructions',
    opening: 'The bulb has safety instructions. Some actions are required; others are simply recommended.',
    concepts: [
      g('episode-36-duty', '～必要がある・～なければならない・～なくてもいい', '～ひつようがある・～なければならない・～なくてもいい', 'distinguish need, obligation, and lack of obligation', '電源[でんげん]を切[き]らなければなりません。', 'You must turn off the power.'),
      g('episode-36-directives', '～なさい・～てほしい', '～なさい・～てほしい', 'give a firm instruction or express a wish for someone’s action', '説明書[せつめいしょ]を読[よ]んでほしい。', 'I want you to read the instructions.'),
    ],
    curriculumGrammarIds: ['grammar-n4-hitsuyou-ga-aru', 'grammar-n4-nakereba-naranai', 'grammar-n4-nakutemo-ii', 'grammar-n4-nasai', 'grammar-n4-te-hoshii'],
    keywords: [v('episode-36-vocab-dengen', '電源', 'でんげん', 'power supply'), v('episode-36-vocab-setsumeisho', '説明書', 'せつめいしょ', 'instruction manual')],
    dialogue: [
      { text: '電球[でんきゅう]を替[か]える前[まえ]に、電源[でんげん]を切[き]らなければならないよ。', meaning: 'You must switch off the power before replacing the bulb.' },
      { text: '難[むずか]しい道具[どうぐ]は使[つか]わなくてもいいみたい。', meaning: 'It seems no difficult tools are needed.' },
    ],
    wrongDetails: ['The power must stay on.', 'Special professional tools are required.'],
    build: { prompt: 'State the safety obligation.', parts: ['でんげんを', 'きらなければ', 'なりません'], answer: '電源[でんげん]を切[き]らなければなりません。', meaning: 'You must turn off the power.', explanation: '～なければならない literally frames not doing it as unacceptable.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose “do not have to.”', context: '明日[あした]は休[やす]みなので、早[はや]く起[お]き（　）。', options: ['なければなりません', 'なくてもいいです', 'なさい'], correctIndex: 1, explanation: '～なくてもいい removes the obligation to get up early.' },
    continuation: { text: '部屋[へや]が整[ととの]ったら、みんなを夕食[ゆうしょく]に招待[しょうたい]しようと思[おも]う。', meaning: 'Once the room is ready, I am thinking of inviting everyone to dinner.' },
    nextHook: 'Plans become decisions, schedules, and outcomes decided by other people.',
  }),
  n4({
    number: 37,
    titleJapanese: '夕食会を開こう', titleEnglish: 'Let’s Have a Dinner Party',
    opening: 'The friends choose a date, make personal decisions, and accept what the building rules decide for them.',
    concepts: [
      g('episode-37-decisions', '意向形・～ことにする・～ようと思う', 'いこうけい・～ことにする・～ようとおもう', 'propose an action and express a personal decision or intention', '土曜日[どようび]に夕食会[ゆうしょくかい]を開[ひら]こうと思[おも]います。', 'I am thinking of holding a dinner party on Saturday.'),
      g('episode-37-arrangements', '～ことになる・～予定だ', '～ことになる・～よていだ', 'express an externally decided outcome or schedule', '七時[しちじ]に始[はじ]めることになりました。', 'It has been decided that we will start at seven.'),
    ],
    curriculumGrammarIds: ['grammar-n4-volitional-form', 'grammar-n4-koto-ni-suru', 'grammar-n4-koto-ni-naru', 'grammar-n4-yotei-da', 'grammar-n4-you-to-omou'],
    keywords: [v('episode-37-vocab-yuushokukai', '夕食会', 'ゆうしょくかい', 'dinner party'), v('episode-37-vocab-shoutai', '招待', 'しょうたい', 'invitation')],
    dialogue: [
      { text: '土曜日[どようび]に夕食会[ゆうしょくかい]を開[ひら]くことにしたよ。', meaning: 'You decided to hold a dinner party on Saturday.' },
      { text: '建物[たてもの]の決[き]まりで、九時[くじ]までに終[お]わることになってる。', meaning: 'Building rules require the party to end by nine.' },
    ],
    wrongDetails: ['The party can continue all night.', 'The landlord chose Friday morning.'],
    build: { prompt: 'State your intention for Saturday.', parts: ['どようびに', 'ゆうしょくかいをひらこうと', 'おもいます'], answer: '土曜日[どようび]に夕食会[ゆうしょくかい]を開[ひら]こうと思[おも]います。', meaning: 'I am thinking of holding a dinner party on Saturday.', explanation: 'Volitional form + と思う presents a considered intention.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose the externally decided outcome.', context: '会議[かいぎ]は来週[らいしゅう]行[おこな]う（　）。', options: ['ことにしました', 'ことになりました', 'ようと思[おも]いました'], correctIndex: 1, explanation: 'ことになる presents an arrangement not framed as the speaker’s personal choice.' },
    continuation: { text: 'れんなら料理[りょうり]を手伝[てつだ]ってくれるはずだよ。', meaning: 'Ren should be willing to help cook.' },
    nextHook: 'Predictions range from confident expectation to uncertainty and impossibility.',
  }),
  n4({
    number: 38,
    titleJapanese: '来てくれるはず', titleEnglish: 'He Should Be Able to Come',
    opening: 'Invitations go out. The group reasons about who should come and who might be busy.',
    concepts: [
      g('episode-38-expectation', '～はずだ／～はずがない', '～はずだ／～はずがない', 'state a reasoned expectation or strong impossibility', 'れんは今日[きょう]休[やす]みだから、来[こ]られるはずです。', 'Ren is off today, so he should be able to come.'),
      g('episode-38-possibility', '～かもしれない', '～かもしれない', 'express a real but uncertain possibility', '仕事[しごと]が長引[ながび]くかもしれません。', 'Work might run late.'),
    ],
    curriculumGrammarIds: ['grammar-n4-hazu-da', 'grammar-n4-hazu-ga-nai', 'grammar-n4-kamo-shirenai'],
    keywords: [v('episode-38-vocab-nagabiku', '長引', 'ながび', 'run long'), v('episode-38-vocab-yoyaku', '予約', 'よやく', 'reservation')],
    dialogue: [
      { text: 'れんは土曜日[どようび]が休[やす]みだから、来[こ]られるはずだよ。', meaning: 'Ren should be able to come because Saturday is his day off.' },
      { text: 'でも、急[きゅう]な仕事[しごと]が入[はい]るかもしれないって。', meaning: 'There might still be an unexpected work assignment.' },
    ],
    wrongDetails: ['Ren has definitely refused.', 'Ren moved overseas yesterday.'],
    build: { prompt: 'Express a reasoned expectation.', parts: ['れんはきょうやすみだから', 'こられるはずです'], answer: 'れんは今日[きょう]休[やす]みだから、来[こ]られるはずです。', meaning: 'Ren is off today, so he should be able to come.', explanation: 'はず is based on evidence or logic, not merely a personal hope.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose the uncertain prediction.', context: '午後[ごご]は雪[ゆき]が降[ふ]る（　）。', options: ['はずがありません', 'かもしれません', 'ことにします'], correctIndex: 1, explanation: 'かもしれません signals uncertainty rather than a firm expectation.' },
    continuation: { text: '天気予報[てんきよほう]では、夕方[ゆうがた]から雪[ゆき]だそうだよ。', meaning: 'The forecast says it will snow from evening.' },
    nextHook: 'Hearsay and appearances must stay distinct when the weather changes.',
  }),
  n4({
    number: 39,
    titleJapanese: '雪が降りそう', titleEnglish: 'It Looks Like Snow',
    opening: 'The forecast, the clouds, and casual rumors provide three different kinds of evidence.',
    concepts: [
      g('episode-39-evidence', '～そうだ（伝聞）・～らしい', '～そうだ・～らしい', 'report what was heard or what is apparently true', '予報[よほう]では、今夜[こんや]は雪[ゆき]だそうです。', 'The forecast says it will snow tonight.'),
      g('episode-39-appearance', '～そうだ（様態）・～ようだ・～みたいだ・～に見える', '～そうだ・～ようだ・～みたいだ・～にみえる', 'describe an appearance or inference from evidence', '空[そら]が暗[くら]くて、雪[ゆき]が降[ふ]りそうです。', 'The sky is dark; it looks like it will snow.'),
    ],
    curriculumGrammarIds: ['grammar-n4-souda-hearsay', 'grammar-n4-souda-appearance', 'grammar-n4-rashii', 'grammar-n4-youda-similarity', 'grammar-n4-mitai-da', 'grammar-n4-ni-mieru'],
    keywords: [v('episode-39-vocab-yohou', '予報', 'よほう', 'forecast'), v('episode-39-vocab-sora', '空', 'そら', 'sky')],
    dialogue: [
      { text: '天気予報[てんきよほう]によると、今夜[こんや]は雪[ゆき]だそうだよ。', meaning: 'According to the forecast, it will snow tonight.' },
      { text: '空[そら]も暗[くら]くなってきたし、本当[ほんとう]に降[ふ]りそう。', meaning: 'The darkening sky also makes snow look likely.' },
    ],
    wrongDetails: ['Yuki personally saw snow yesterday.', 'The sky is clearing and the forecast promises sun.'],
    build: { prompt: 'Describe what the sky suggests.', parts: ['そらがくらくて', 'ゆきが', 'ふりそうです'], answer: '空[そら]が暗[くら]くて、雪[ゆき]が降[ふ]りそうです。', meaning: 'The sky is dark, and it looks like it will snow.', explanation: 'Verb stem + そう describes an appearance based on what you can observe.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose hearsay rather than visible appearance.', context: 'ニュースによると、電車[でんしゃ]が止[と]まった（　）。', options: ['そうです', 'そうな電車[でんしゃ]です', 'ように見[み]えます'], correctIndex: 0, explanation: 'A named information source plus plain form + そうです marks hearsay.' },
    continuation: { text: '雪[ゆき]でも来[こ]られる人[ひと]だけで、温[あたた]かい料理[りょうり]を作[つく]ろう。', meaning: 'Even if it snows, let’s cook something warm with whoever can come.' },
    nextHook: 'Ability and potential forms decide what each guest can contribute.',
  }),
  n4({
    number: 40,
    titleJapanese: '何ができる？', titleEnglish: 'What Can Everyone Do?',
    opening: 'The guest list is set. Each person volunteers a task based on what they can do.',
    concepts: [
      g('episode-40-ability', '～ことができる', '～ことができる', 'express ability with a nominalized dictionary-form verb', 'れんは魚[さかな]を焼[や]くことができます。', 'Ren can grill fish.'),
      g('episode-40-potential', '可能形', 'かのうけい', 'express that an action is possible directly on the verb', 'この台所[だいどころ]なら、三人[さんにん]で料理[りょうり]できます。', 'In this kitchen, three people can cook together.'),
    ],
    curriculumGrammarIds: ['grammar-n4-koto-ga-dekiru', 'grammar-n4-potential-form'],
    keywords: [v('episode-40-vocab-daigokoro', '台所', 'だいどころ', 'kitchen'), v('episode-40-vocab-yaku', '焼', 'や', 'grill; bake')],
    dialogue: [{ text: 'れんは魚[さかな]を焼[や]けるし、ゆきはデザートを作[つく]れるよ。', meaning: 'Ren can grill fish, and Yuki can make dessert.' }, { text: '私[わたし]はまだ難[むずか]しい料理[りょうり]はできないけど、野菜[やさい]なら切[き]れる。', meaning: 'You cannot cook difficult dishes yet, but you can cut vegetables.' }],
    wrongDetails: ['Nobody can prepare any food.', 'Yuki asks you to repair the kitchen.'],
    build: { prompt: 'State Ren’s cooking ability.', parts: ['れんは', 'さかなをやくことが', 'できます'], answer: 'れんは魚[さかな]を焼[や]くことができます。', meaning: 'Ren can grill fish.', explanation: 'Dictionary form + ことができる is a neutral, explicit way to state ability.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the potential form.', context: 'この漢字[かんじ]が（　）か。', options: ['読[よ]めます', '読[よ]みます', '読[よ]ませます'], correctIndex: 0, explanation: '読めます is the polite potential form: “can read.”' },
    continuation: { text: '料理[りょうり]を作[つく]っている間[あいだ]に、宅配便[たくはいびん]が届[とど]いた。', meaning: 'A delivery arrived while everyone was cooking.' },
    nextHook: 'The delivery notice describes actions from the receiver’s viewpoint.',
  }),
  n4({
    number: 41,
    titleJapanese: '荷物が届けられた', titleEnglish: 'A Package Was Delivered',
    opening: 'A package arrives without a clear sender. The notice uses passive forms throughout.',
    concepts: [
      g('episode-41-passive-event', '受身形', 'うけみけい', 'describe an event from the person or thing affected by it', '荷物[にもつ]は午後[ごご]三時[さんじ]に届[とど]けられました。', 'The package was delivered at three.'),
      g('episode-41-adversity', '迷惑の受身', 'めいわくのうけみ', 'show that someone was negatively affected by another person’s action', '雨[あめ]に降[ふ]られて、服[ふく]がぬれました。', 'I got caught in the rain and my clothes got wet.'),
    ],
    curriculumGrammarIds: ['grammar-n4-passive-form'],
    keywords: [v('episode-41-vocab-nimotsu', '荷物', 'にもつ', 'package; luggage'), v('episode-41-vocab-todokeru', '届', 'とど', 'deliver; reach')],
    dialogue: [{ text: 'この荷物[にもつ]、だれから送[おく]られたんだろう。', meaning: 'Yuki wonders who sent the package.' }, { text: '伝票[でんぴょう]には、昨日[きのう]大阪[おおさか]から発送[はっそう]されたと書[か]いてある。', meaning: 'The slip says it was shipped from Osaka yesterday.' }],
    wrongDetails: ['The package was shipped to Osaka next week.', 'The slip has no shipping information.'],
    build: { prompt: 'Report the delivery time in passive form.', parts: ['にもつは', 'ごごさんじに', 'とどけられました'], answer: '荷物[にもつ]は午後[ごご]三時[さんじ]に届[とど]けられました。', meaning: 'The package was delivered at three.', explanation: 'The passive keeps 荷物 as the topic and presents what happened to it.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the passive form.', context: '先生[せんせい]に名前[なまえ]を（　）。', options: ['呼[よ]ばれました', '呼[よ]びました', '呼[よ]ばせました'], correctIndex: 0, explanation: '呼ばれました means “was called” from the affected person’s viewpoint.' },
    continuation: { text: '中[なか]には、会社[かいしゃ]で使[つか]う新[あたら]しい道具[どうぐ]が入[はい]っていた。', meaning: 'Inside was a new tool used at work.' },
    nextHook: 'Workplace instructions introduce making, letting, and being forced to act.',
  }),
  n4({
    number: 42,
    titleJapanese: 'やらされる仕事', titleEnglish: 'The Task Nobody Wanted',
    opening: 'At work, a supervisor assigns an unpopular setup task and later allows you to try something new.',
    concepts: [
      g('episode-42-causative', '使役形・～させてください', 'しえきけい・～させてください', 'make or let someone act, or ask permission to do something', '今日[きょう]は私[わたし]に準備[じゅんび]をさせてください。', 'Please let me handle the preparation today.'),
      g('episode-42-causative-passive', '使役受身形', 'しえきうけみけい', 'say that someone was made or forced to act', '上司[じょうし]に残業[ざんぎょう]させられました。', 'I was made to work overtime by my boss.'),
    ],
    curriculumGrammarIds: ['grammar-n4-causative-form', 'grammar-n4-causative-passive-form', 'grammar-n4-sasete-kudasai'],
    keywords: [v('episode-42-vocab-junbi', '準備', 'じゅんび', 'preparation'), v('episode-42-vocab-zangyou', '残業', 'ざんぎょう', 'overtime')],
    dialogue: [{ text: '昨日[きのう]は部長[ぶちょう]に会議室[かいぎしつ]を片[かた]づけさせられたよ。', meaning: 'Yuki was made to clean the meeting room yesterday.' }, { text: '今日[きょう]は新[あたら]しい機械[きかい]を使[つか]わせてもらえるらしい。', meaning: 'Today, it seems Yuki will be allowed to use the new machine.' }],
    wrongDetails: ['Yuki chose to clean for fun.', 'The new machine has been thrown away.'],
    build: { prompt: 'Ask to handle today’s preparation.', parts: ['きょうは', 'わたしにじゅんびを', 'させてください'], answer: '今日[きょう]は私[わたし]に準備[じゅんび]をさせてください。', meaning: 'Please let me handle the preparation today.', explanation: '～させてください asks the listener to allow the speaker’s action.' },
    exam: { format: 'form-choice', prompt: 'Choose the causative-passive form.', context: '子供[こども]の時[とき]、毎日[まいにち]野菜[やさい]を（　）。', options: ['食[た]べさせられました', '食[た]べられました', '食[た]べさせました'], correctIndex: 0, explanation: '食べさせられました means “was made to eat.”' },
    continuation: { text: '機械[きかい]のスイッチが勝手[かって]に入[はい]ったのか、だれかが入[い]れたのか調[しら]べよう。', meaning: 'Let’s check whether the machine switched on by itself or someone switched it on.' },
    nextHook: 'Transitive and intransitive verbs reveal whether a change happened or someone caused it.',
  }),
  n4({
    number: 43,
    titleJapanese: 'ドアが開いている', titleEnglish: 'The Door Is Open',
    opening: 'A workplace mystery depends on the difference between a resulting state and a deliberate action.',
    concepts: [
      g('episode-43-transitivity', '自動詞と他動詞', 'じどうしとたどうし', 'distinguish a change or state from an action on an object', 'ドアが開[あ]いています。', 'The door is open.'),
      g('episode-43-agentive', '～が／～を＋動詞', '～が／～を＋どうし', 'choose particles that match intransitive or transitive verbs', 'だれかがドアを開[あ]けました。', 'Someone opened the door.'),
    ],
    curriculumGrammarIds: ['grammar-n4-transitive-intransitive-verbs'],
    keywords: [v('episode-43-vocab-doa', 'ドア', 'ドア', 'door'), v('episode-43-vocab-katte', '勝手', 'かって', 'without permission; on its own')],
    dialogue: [{ text: '朝[あさ]来[き]たら、会議室[かいぎしつ]の窓[まど]が開[あ]いていた。', meaning: 'When Yuki arrived, the meeting-room window was open.' }, { text: 'でも、だれが窓[まど]を開[あ]けたのかは分[わ]からない。', meaning: 'Nobody knows who opened it.' }],
    wrongDetails: ['Yuki definitely opened the window.', 'The window is broken and cannot open.'],
    build: { prompt: 'Describe the deliberate action.', parts: ['だれかが', 'ドアを', 'あけました'], answer: 'だれかがドアを開[あ]けました。', meaning: 'Someone opened the door.', explanation: '他動詞 開ける takes an agent and an object marked with を.' },
    exam: { format: 'particle-and-verb', prompt: 'Choose the natural pair.', context: '電気[でんき]（　）消[き]えました。', options: ['が', 'を', 'に'], correctIndex: 0, explanation: '消える is intransitive, so the thing that went out is marked by が.' },
    continuation: { text: '防犯[ぼうはん]のために、帰[かえ]る前[まえ]に窓[まど]を確認[かくにん]しよう。', meaning: 'For security, let’s check the windows before leaving.' },
    nextHook: 'Purpose expressions clarify goals, desired results, and intended uses.',
  }),
  n4({
    number: 44,
    titleJapanese: '安全のために', titleEnglish: 'For Everyone’s Safety',
    opening: 'The team writes a short security guide for the office.',
    concepts: [
      g('episode-44-purpose', '～ために・～ように', '～ために・～ように', 'express a controllable purpose or a desired result', '安全[あんぜん]のために、窓[まど]を確認[かくにん]します。', 'We check the windows for safety.'),
      g('episode-44-use', '～のに・～から作る', '～のに・～からつくる', 'describe an intended use or the material something is made from', 'この道具[どうぐ]は箱[はこ]を開[あ]けるのに使[つか]います。', 'This tool is used for opening boxes.'),
    ],
    curriculumGrammarIds: ['grammar-n4-tame-ni-purpose', 'grammar-n4-you-ni-purpose', 'grammar-n4-noni-purpose', 'grammar-n4-kara-tsukuru'],
    keywords: [v('episode-44-vocab-anzen', '安全', 'あんぜん', 'safety'), v('episode-44-vocab-dougu', '道具', 'どうぐ', 'tool')],
    dialogue: [{ text: '忘[わす]れないように、出口[でぐち]のそばに注意[ちゅうい]を書[か]いておこう。', meaning: 'Let’s write a reminder by the exit so nobody forgets.' }, { text: '新人[しんじん]にも分[わ]かるように、簡単[かんたん]な言葉[ことば]を使[つか]おう。', meaning: 'Let’s use simple words so new employees can understand.' }],
    wrongDetails: ['The guide should use difficult technical language.', 'The reminder will be hidden in a drawer.'],
    build: { prompt: 'State the safety purpose.', parts: ['あんぜんのために', 'まどを', 'かくにんします'], answer: '安全[あんぜん]のために、窓[まど]を確認[かくにん]します。', meaning: 'We check the windows for safety.', explanation: 'Noun + のために expresses a purpose or benefit.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose the desired-result expression.', context: '忘[わす]れない（　）、メモします。', options: ['ように', 'ためを', 'のに作[つく]る'], correctIndex: 0, explanation: '～ように suits a desired state such as not forgetting.' },
    continuation: { text: 'この習慣[しゅうかん]を続[つづ]ければ、自然[しぜん]に確認[かくにん]できるようになるよ。', meaning: 'If we keep this habit, checking will become automatic.' },
    nextHook: 'Deliberate changes and gradual new abilities shape better habits.',
  }),
  n4({
    number: 45,
    titleJapanese: '少しずつ慣れていく', titleEnglish: 'Getting Used to It',
    opening: 'After several weeks, the apartment and workplace both feel easier to manage.',
    concepts: [
      g('episode-45-change', '～くする・～ようになる', '～くする・～ようになる', 'cause an adjective change or come to a new ability or habit', '毎朝[まいあさ]、早[はや]く起[お]きられるようになりました。', 'I became able to get up early every morning.'),
      g('episode-45-effort', '～ようにする', '～ようにする', 'make a deliberate, repeated effort', '毎日[まいにち]、日本語[にほんご]で日記[にっき]を書[か]くようにしています。', 'I make a point of writing a diary in Japanese every day.'),
    ],
    curriculumGrammarIds: ['grammar-n4-ku-suru', 'grammar-n4-you-ni-naru', 'grammar-n4-you-ni-suru'],
    keywords: [v('episode-45-vocab-shuukan', '習慣', 'しゅうかん', 'habit'), v('episode-45-vocab-nikki', '日記', 'にっき', 'diary')],
    dialogue: [{ text: '前[まえ]より早[はや]く起[お]きられるようになったね。', meaning: 'You have become able to get up earlier than before.' }, { text: '夜[よる]はスマホを見[み]すぎないようにしてるんだ。', meaning: 'You make an effort not to look at your phone too much at night.' }],
    wrongDetails: ['You now stay up later every night.', 'Yuki says habits can never change.'],
    build: { prompt: 'Describe your deliberate study habit.', parts: ['まいにち', 'にほんごでにっきをかくように', 'しています'], answer: '毎日[まいにち]、日本語[にほんご]で日記[にっき]を書[か]くようにしています。', meaning: 'I make a point of writing a diary in Japanese every day.', explanation: '～ようにしている presents an ongoing intentional habit.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose an acquired ability.', context: '日本語[にほんご]の新聞[しんぶん]が少[すこ]し（　）。', options: ['読[よ]めるようになりました', '読[よ]むようにしました', '読[よ]みやすくしました'], correctIndex: 0, explanation: 'Potential form + ようになる describes becoming able to read.' },
    continuation: { text: '毎日[まいにち]十分[じゅっぷん]だけでも、続[つづ]けるほど力[ちから]がつくよ。', meaning: 'Even ten minutes a day builds ability the more you continue.' },
    nextHook: 'Limits, extent, and emphatic quantities sharpen how you read N4 sentences.',
  }),
  n4({
    number: 46,
    titleJapanese: '十分だけでも', titleEnglish: 'Even Just Ten Minutes',
    opening: 'Yuki helps you design a realistic study routine without exaggerating what one session can do.',
    concepts: [
      g('episode-46-extent', '～ほど・～だけで', '～ほど・～だけで', 'express degree or that one condition alone is enough', '名前[なまえ]を聞[き]くだけで、顔[かお]を思[おも]い出[だ]せます。', 'Just hearing the name is enough to remember the face.'),
      g('episode-46-limits', '～しか～ない・～ばかり・数量＋も', '～しか～ない・～ばかり・すうりょう＋も', 'mark a strict limit, an excessive concentration, or a surprisingly large amount', '昨日[きのう]は五時間[ごじかん]も勉強[べんきょう]しました。', 'I studied for as many as five hours yesterday.'),
    ],
    curriculumGrammarIds: ['grammar-n4-hodo', 'grammar-n4-dake-de', 'grammar-n4-shika-nai', 'grammar-n4-bakari', 'grammar-n4-mo-quantity-emphasis'],
    keywords: [v('episode-46-vocab-chikara', '力', 'ちから', 'ability; strength'), v('episode-46-vocab-jikan', '時間', 'じかん', 'time; hours')],
    dialogue: [{ text: '忙[いそが]しい日[ひ]は、単語[たんご]を十個[じゅっこ]覚[おぼ]えるだけでもいいよ。', meaning: 'On busy days, even learning just ten words is fine.' }, { text: '一日[いちにち]しかできなくても、何[なに]もしないよりはいい。', meaning: 'Even if you can do only one day, it is better than nothing.' }],
    wrongDetails: ['You must study five hours every day.', 'Learning ten words has no value.'],
    build: { prompt: 'Express that hearing the name alone is enough.', parts: ['なまえをきくだけで', 'かおを', 'おもいだせます'], answer: '名前[なまえ]を聞[き]くだけで、顔[かお]を思[おも]い出[だ]せます。', meaning: 'Just hearing the name is enough to remember the face.', explanation: 'だけで isolates a sufficient condition.' },
    exam: { format: 'grammar-cloze', prompt: 'Choose the strict-limit construction.', context: '財布[さいふ]に千円[せんえん]（　）ありません。', options: ['しか', 'も', 'ほどが'], correctIndex: 0, explanation: 'しか pairs with a negative predicate: only 1,000 yen.' },
    continuation: { text: '文法[ぶんぽう]とか読解[どっかい]とか、日[ひ]によって内容[ないよう]を変[か]えてみよう。', meaning: 'Let’s vary the content by day—grammar, reading, and so on.' },
    nextHook: 'Natural example lists and casual alternatives keep repetition varied.',
  }),
  n4({
    number: 47,
    titleJapanese: '文法とか読解とか', titleEnglish: 'Grammar, Reading, and So On',
    opening: 'A weekly plan groups study activities without pretending the list is complete.',
    concepts: [
      g('episode-47-examples', '～など・～とか～とか', '～など・～とか～とか', 'give non-exhaustive examples in neutral or casual style', '週末[しゅうまつ]は文法[ぶんぽう]とか読解[どっかい]とかを復習[ふくしゅう]します。', 'On weekends I review things like grammar and reading.'),
      g('episode-47-suggestion', '～でも', '～でも', 'offer one representative option without insisting on it', '休憩[きゅうけい]にお茶[ちゃ]でも飲[の]みませんか。', 'Would you like tea or something during the break?'),
    ],
    curriculumGrammarIds: ['grammar-n4-nado', 'grammar-n4-demo-alternatives', 'grammar-n4-toka-toka'],
    keywords: [v('episode-47-vocab-dokkai', '読解', 'どっかい', 'reading comprehension'), v('episode-47-vocab-kyuukei', '休憩', 'きゅうけい', 'break')],
    dialogue: [{ text: '平日[へいじつ]は単語[たんご]や漢字[かんじ]など、短[みじか]い練習[れんしゅう]がよさそう。', meaning: 'Short practice such as vocabulary and kanji seems good for weekdays.' }, { text: '週末[しゅうまつ]は読解[どっかい]とか聴解[ちょうかい]とか、時間[じかん]がかかる物[もの]をやろう。', meaning: 'On weekends, let’s do longer tasks like reading and listening.' }],
    wrongDetails: ['Weekdays are reserved for full mock exams only.', 'Listening practice has been removed.'],
    build: { prompt: 'Give casual examples of weekend study.', parts: ['しゅうまつは', 'ぶんぽうとかどっかいとかを', 'ふくしゅうします'], answer: '週末[しゅうまつ]は文法[ぶんぽう]とか読解[どっかい]とかを復習[ふくしゅう]します。', meaning: 'On weekends I review things like grammar and reading.', explanation: 'とか repeats after each example and sounds conversational.' },
    exam: { format: 'appropriate-response', prompt: 'Choose the casual suggestion.', context: 'ちょっと休[やす]みたいですね。', options: ['お茶[ちゃ]でも飲[の]みませんか。', 'お茶[ちゃ]しか飲[の]みません。', 'お茶[ちゃ]ほど休[やす]みます。'], correctIndex: 0, explanation: 'Noun + でも offers an example option: tea or something like that.' },
    continuation: { text: '外[そと]からいい匂[にお]いがする。少[すこ]し休[やす]もうか。', meaning: 'Something smells good outside. Shall we take a short break?' },
    nextHook: 'Senses and outward signs reveal feelings without quoting inner thoughts directly.',
  }),
  n4({
    number: 48,
    titleJapanese: 'いい匂いがする', titleEnglish: 'Something Smells Good',
    opening: 'At a bakery, the group describes smells and notices how other people seem to feel.',
    concepts: [
      g('episode-48-senses', '～がする', '～がする', 'report a perceived smell, sound, taste, or bodily feeling', 'パンのいい匂[にお]いがします。', 'There is a nice smell of bread.'),
      g('episode-48-outward-feeling', '～がる・～がり・～たがる', '～がる・～がり・～たがる', 'describe outward signs of another person’s feeling or desire', '子供[こども]がケーキを食[た]べたがっています。', 'The child is showing that they want to eat cake.'),
    ],
    curriculumGrammarIds: ['grammar-n4-ga-suru-senses', 'grammar-n4-garu', 'grammar-n4-gari', 'grammar-n4-tagaru'],
    keywords: [v('episode-48-vocab-nioi', '匂', 'にお', 'smell'), v('episode-48-vocab-kodomo', '子供', 'こども', 'child')],
    dialogue: [{ text: '焼[や]きたてのパンの匂[にお]いがするね。', meaning: 'It smells like freshly baked bread.' }, { text: 'れんも入[はい]りたがってるけど、時間[じかん]は大丈夫[だいじょうぶ]かな。', meaning: 'Ren seems to want to go in, but Yuki wonders whether there is time.' }],
    wrongDetails: ['Ren says the bakery smells terrible.', 'The bakery has already closed for a year.'],
    build: { prompt: 'Describe the smell naturally.', parts: ['パンの', 'いいにおいが', 'します'], answer: 'パンのいい匂[にお]いがします。', meaning: 'There is a nice smell of bread.', explanation: 'Smell, sound, taste, and felt sensations commonly take がする.' },
    exam: { format: 'grammar-cloze', prompt: 'Describe another person’s visible desire.', context: '弟[おとうと]は新[あたら]しいゲームを（　）。', options: ['ほしいです', '買[か]いたがっています', '買[か]いたいと思[おも]います'], correctIndex: 1, explanation: '～たがっている reports outward signs of someone else’s desire.' },
    continuation: { text: '説明[せつめい]が小[ちい]さくて読[よ]みにくいけど、注文[ちゅうもん]はしやすそう。', meaning: 'The explanation is hard to read, but ordering looks easy.' },
    nextHook: 'Ease and difficulty expressions help evaluate signs, forms, and actions.',
  }),
  n4({
    number: 49,
    titleJapanese: '読みにくいメニュー', titleEnglish: 'A Hard-to-Read Menu',
    opening: 'The menu uses tiny print and unfamiliar names, but the ordering system itself is simple.',
    concepts: [
      g('episode-49-ease', '～やすい・～にくい', '～やすい・～にくい', 'describe objective ease or difficulty of doing an action', 'この画面[がめん]は使[つか]いやすいです。', 'This screen is easy to use.'),
      g('episode-49-difficulty', '～づらい・なかなか～ない', '～づらい・なかなか～ない', 'express personal or emotional difficulty, or something not happening easily', '店員[てんいん]さんが忙[いそが]しそうで、話[はな]しかけづらいです。', 'The clerk looks busy, so it is hard to approach them.'),
    ],
    curriculumGrammarIds: ['grammar-n4-nakanaka-nai', 'grammar-n4-nikui', 'grammar-n4-yasui', 'grammar-n4-zurai'],
    keywords: [v('episode-49-vocab-gamen', '画面', 'がめん', 'screen'), v('episode-49-vocab-tenin', '店員', 'てんいん', 'clerk')],
    dialogue: [{ text: '字[じ]が小[ちい]さくて読[よ]みにくいけど、写真[しゃしん]があるから選[えら]びやすいね。', meaning: 'The small print is hard to read, but photos make choosing easy.' }, { text: '店員[てんいん]さんが忙[いそが]しそうで、質問[しつもん]しづらいな。', meaning: 'The clerk looks busy, which makes it uncomfortable to ask.' }],
    wrongDetails: ['The menu has no pictures.', 'The clerk is waiting with nothing to do.'],
    build: { prompt: 'Describe the screen’s usability.', parts: ['このがめんは', 'つかいやすいです'], answer: 'この画面[がめん]は使[つか]いやすいです。', meaning: 'This screen is easy to use.', explanation: 'Attach やすい to the ます-stem to describe ease.' },
    exam: { format: 'grammar-contrast', prompt: 'Choose personal reluctance or difficulty.', context: '先輩[せんぱい]にはこの話[はなし]を（　）。', options: ['言[い]いづらいです', '言[い]いやすいです', '言[い]うそうです'], correctIndex: 0, explanation: '～づらい often includes the speaker’s emotional or situational burden.' },
    continuation: { text: '高[たか]かったのに、おいしかったし、来[き]てよかったね。', meaning: 'Although it was expensive, it was delicious, and I’m glad we came.' },
    nextHook: 'Contrast, accumulated reasons, and reflective reactions support nuanced opinions.',
  }),
  n4({
    number: 50,
    titleJapanese: '高かったのに', titleEnglish: 'Even Though It Was Expensive',
    opening: 'After the bakery visit, everyone gives a nuanced review instead of a simple good-or-bad answer.',
    concepts: [
      g('episode-50-contrast', '～のに・～し・それでも', '～のに・～し・それでも', 'express an unexpected contrast, accumulate reasons, or continue despite one', '高[たか]かったのに、また行[い]きたいです。', 'Even though it was expensive, I want to go again.'),
      g('episode-50-reflection', '～かな・～かしら・～ではないか', '～かな・～かしら・～ではないか', 'wonder to oneself or invite agreement with an opinion', 'あの店[みせ]は町[まち]でいちばん人気[にんき]なのではないかな。', 'I wonder if that shop might be the most popular in town.'),
    ],
    curriculumGrammarIds: ['grammar-n4-noni-contrast', 'grammar-n4-shi', 'grammar-n4-sore-demo', 'grammar-n4-dewa-nai-ka', 'grammar-n4-kashira', 'grammar-n4-kai-question', 'grammar-n4-kana'],
    keywords: [v('episode-50-vocab-kansou', '感想', 'かんそう', 'impression'), v('episode-50-vocab-ninki', '人気', 'にんき', 'popular')],
    dialogue: [{ text: '少[すこ]し高[たか]かったのに、店[みせ]の外[そと]まで人[ひと]が並[なら]んでたね。', meaning: 'Even though it was expensive, people lined up outside.' }, { text: '味[あじ]もいいし、店員[てんいん]さんも親切[しんせつ]だからではないかな。', meaning: 'Perhaps it is because the food is good and the staff are kind.' }],
    wrongDetails: ['The shop was empty because the food was bad.', 'Yuki refuses to give any opinion.'],
    build: { prompt: 'Express an unexpected contrast.', parts: ['たかかったのに', 'また', 'いきたいです'], answer: '高[たか]かったのに、また行[い]きたいです。', meaning: 'Even though it was expensive, I want to go again.', explanation: '～のに presents the following result as contrary to expectation.' },
    exam: { format: 'grammar-cloze', prompt: 'Accumulate two supporting reasons.', context: 'この町[まち]は交通[こうつう]も便利[べんり]だ（　）、店[みせ]も多[おお]いです。', options: ['し', 'のに', 'かな'], correctIndex: 0, explanation: '～し lists one reason alongside another.' },
    continuation: { text: '次[つぎ]はいよいよN4の総合[そうごう]問題[もんだい]だよ。', meaning: 'Next comes the full N4 integrated challenge.' },
    nextHook: 'The finale combines casual, polite, and formal Japanese with every major JLPT task family.',
  }),
  n4({
    number: 51,
    titleJapanese: 'N4への挑戦', titleEnglish: 'The N4 Challenge',
    opening: 'The story closes with a realistic rehearsal: notices, conversations, workplace language, and a short reading under time pressure.',
    concepts: [
      g('episode-51-polite-register', '尊敬語', 'そんけいご', 'raise the subject with common honorific verbs and patterns', '先生[せんせい]はもう会場[かいじょう]にいらっしゃいます。', 'The teacher is already at the venue.'),
      g('episode-51-humble-register', '謙譲語・丁寧語', 'けんじょうご・ていねいご', 'lower the speaker’s action or use formal service language', '資料[しりょう]は私[わたし]がお持[も]ちいたします。', 'I will carry the materials.'),
    ],
    curriculumGrammarIds: ['grammar-n4-de-gozaimasu', 'grammar-n4-gozaimasu', 'grammar-n4-irassharu', 'grammar-n4-nasaru', 'grammar-n4-o-ni-naru', 'grammar-n4-itasu', 'grammar-n4-o-kudasai', 'grammar-n4-te-sumimasen', 'grammar-n4-te-yokatta', 'grammar-n4-to-ittemo-ii', 'grammar-n4-te-de-cause'],
    keywords: [v('episode-51-vocab-kaijou', '会場', 'かいじょう', 'venue'), v('episode-51-vocab-shiryou', '資料', 'しりょう', 'materials')],
    dialogue: [{ text: '受付[うけつけ]の方[かた]が「先生[せんせい]はもういらっしゃいます」と言[い]ってたよ。', meaning: 'The receptionist said the teacher is already present.' }, { text: '資料[しりょう]を持[も]ってきてくれて、助[たす]かった。間[ま]に合[あ]ってよかったね。', meaning: 'The materials arrived in time, which was a relief.' }],
    wrongDetails: ['The teacher canceled the event.', 'The materials were intentionally left at home.'],
    build: { prompt: 'Offer to carry the materials humbly.', parts: ['しりょうは', 'わたしが', 'おもちいたします'], answer: '資料[しりょう]は私[わたし]がお持[も]ちいたします。', meaning: 'I will carry the materials.', explanation: 'お + verb stem + いたします presents the speaker’s action humbly.' },
    exam: { format: 'integrated-information-retrieval', prompt: 'Choose what a participant should do.', context: '受付[うけつけ]は九時[くじ]からでございます。参加者[さんかしゃ]は会場[かいじょう]に入[はい]る前[まえ]に、二階[にかい]で名前[なまえ]をお書[か]きください。', options: ['九時[くじ]前[まえ]に会場[かいじょう]へ入[はい]ります。', '二階[にかい]で名前[なまえ]を書[か]きます。', '受付[うけつけ]で資料[しりょう]を作[つく]ります。'], correctIndex: 1, explanation: 'The notice instructs participants to write their name on the second floor before entering.' },
    continuation: { text: 'ここまで続[つづ]けてきた力[ちから]は、本番[ほんばん]でもきっと使[つか]えるよ。次[つぎ]は弱[よわ]い所[ところ]を一緒[いっしょ]に復習[ふくしゅう]しよう。', meaning: 'The ability you built will serve you on the real test. Next, we will review your weak areas together.' },
    nextHook: 'The story course is complete; adaptive review can now target the learner’s weakest items.',
  }),
];
