import type { LearningContentCollections } from '../learning-content/schemas';
import { sha256Text, stableStringify } from '../../utils/deterministic-hash';
import { assessmentPlatformResultSchema, type AssessmentAnswerInput, type AssessmentPlatformResult, type AssessmentSnapshot, type ReadinessEstimate } from './platform-schemas';

function percentage(correct: number, total: number): number { return total ? Math.round((correct / total) * 10_000) / 100 : 0; }
function readinessEstimate(overall: number, domainPercentages: number[], evidenceQuestionCount: number, fullMockEquivalentCount: number): ReadinessEstimate {
  const majorDomainBelowThreshold = domainPercentages.some((value) => value < 50); const evidenceSufficient = evidenceQuestionCount >= 180 || fullMockEquivalentCount >= 2; let label: ReadinessEstimate['label'] = overall < 45 ? 'Needs foundation' : overall < 60 ? 'Developing' : overall < 75 ? 'Approaching target' : overall < 88 ? 'Likely ready' : 'Strongly ready';
  if (!evidenceSufficient && (label === 'Strongly ready' || label === 'Likely ready')) label = 'Approaching target'; if (majorDomainBelowThreshold && label === 'Strongly ready') label = 'Likely ready';
  return { label, percentage: overall, evidenceSufficient, evidenceQuestionCount, fullMockEquivalentCount, majorDomainBelowThreshold, explanation: evidenceSufficient ? 'Estimate uses sufficient question volume and domain evidence.' : 'More evidence is required before showing a strong readiness label.' };
}

export function scorePlatformAssessment(snapshot: AssessmentSnapshot, responses: readonly AssessmentAnswerInput[], content: LearningContentCollections, evidence = { priorQuestionCount: 0, priorFullMockCount: 0 }): AssessmentPlatformResult {
  const questionById = new Map(content.questions.map((question) => [question.id, question])); const relationships = new Map<string, typeof content.questionTargetRelationships>(); for (const relationship of content.questionTargetRelationships) relationships.set(relationship.questionId, [...(relationships.get(relationship.questionId) ?? []), relationship]); const responseByQuestion = new Map(responses.map((response) => [response.questionId, response])); const sectionByPlacement = new Map(snapshot.sections.flatMap((section) => section.questionPlacementIds.map((id) => [id, section.id] as const)));
  const answers = snapshot.questionPlacements.map((placement) => { const question = questionById.get(placement.questionId); if (!question || question.responseType === 'text-input') throw new Error(`Cannot score missing or non-select question ${placement.questionId}.`); const response = responseByQuestion.get(placement.questionId); const correctOptionId = question.correctOptionIds[0]; const unanswered = !response?.selectedOptionId; const correct = response?.selectedOptionId === correctOptionId; const targetIds = (relationships.get(question.id) ?? []).map(({ targetId }) => targetId); const supportTag = question.tags.find((tag) => tag.startsWith('support-turn-')); const supportingReferenceIds = placement.parentId && supportTag ? [`${placement.parentId}:${supportTag}`] : placement.parentId ? [placement.parentId] : question.stimulusReferences.map(({ id }) => id); return { questionId: question.id, selectedOptionId: response?.selectedOptionId ?? null, correctOptionId, correct, unanswered, pointsEarned: correct ? snapshot.scoringRule.ordinaryQuestionPoints : 0, pointsAvailable: snapshot.scoringRule.ordinaryQuestionPoints, domain: placement.domain, questionType: placement.questionType, difficultyRank: question.difficulty.rank, targetIds, parentId: placement.parentId, supportingReferenceIds, explanation: question.explanation, reviewRecommendation: correct ? 'Continue normal spaced review.' : `Review the explanation and a related ${placement.domain} target before retrying.`, lifecycle: question.releaseReady ? 'release' as const : 'development-only' as const, sectionId: sectionByPlacement.get(placement.id) ?? '' }; });
  const aggregate = (key: string, selected: typeof answers, weight = 1) => { const correct = selected.filter((answer) => answer.correct).length; const unanswered = selected.filter((answer) => answer.unanswered).length; const total = selected.length; const rawScore = selected.reduce((sum, answer) => sum + answer.pointsEarned, 0); return { key, correct, incorrect: total - correct - unanswered, unanswered, total, rawScore, weightedScore: rawScore * weight, percentage: percentage(correct, total) }; };
  const sectionResults = snapshot.sections.map((section) => aggregate(section.id, answers.filter(({ sectionId }) => sectionId === section.id))); const domains = [...new Set(answers.map(({ domain }) => domain))].sort(); const domainResults = domains.map((domain) => aggregate(domain, answers.filter((answer) => answer.domain === domain), snapshot.scoringRule.domainWeights[domain] ?? 1)); const targets = [...new Set(answers.flatMap(({ targetIds }) => targetIds))].sort(); const targetResults = targets.map((target) => aggregate(target, answers.filter(({ targetIds }) => targetIds.includes(target)))); const correctCount = answers.filter(({ correct }) => correct).length; const unansweredCount = answers.filter(({ unanswered }) => unanswered).length; const rawScore = answers.reduce((sum, answer) => sum + answer.pointsEarned, 0); const weightedScore = domainResults.reduce((sum, result) => sum + result.weightedScore, 0); const overallPercentage = percentage(correctCount, answers.length); const readiness = readinessEstimate(overallPercentage, domainResults.map((result) => result.percentage), evidence.priorQuestionCount + answers.length, evidence.priorFullMockCount + (snapshot.assessmentType === 'full-mock' ? 1 : 0)); const timeUsedSeconds = responses.reduce((sum, response) => sum + response.timeUsedSeconds, 0); const base = { schemaVersion: 1 as const, id: `assessment-result-${sha256Text(`${snapshot.id}\0${stableStringify(responses)}`).slice(0, 16)}`, assessmentId: snapshot.id, rawScore, weightedScore, percentage: overallPercentage, correctCount, incorrectCount: answers.length - correctCount - unansweredCount, unansweredCount, completionStatus: unansweredCount === answers.length ? 'not-started' as const : unansweredCount ? 'in-progress' as const : 'completed' as const, timeUsedSeconds, sectionResults, domainResults, targetResults, answers: answers.map(({ sectionId: _sectionId, ...answer }) => answer), readiness, label: 'JapanGo assessment result' as const }; return assessmentPlatformResultSchema.parse({ ...base, checksum: `sha256:${sha256Text(stableStringify(base))}` });
}
