import { z } from 'zod';

export const assessmentTypeSchema = z.enum([
  'full-mock', 'section-exam', 'quick-practice', 'daily-challenge', 'weak-area', 'mixed-review',
  'curriculum-unit-test', 'grammar-mastery', 'vocabulary-mastery', 'kanji-mastery', 'reading-practice', 'listening-practice',
]);
export const assessmentDomainSchema = z.enum(['vocabulary', 'kanji', 'grammar', 'reading', 'listening']);
export const assessmentLifecycleModeSchema = z.enum(['development', 'release']);
export const assessmentDifficultyDistributionSchema = z.object({ easy: z.number().min(0).max(1), medium: z.number().min(0).max(1), hard: z.number().min(0).max(1) }).strict().refine((value) => Math.abs(value.easy + value.medium + value.hard - 1) < 0.001, 'Difficulty distribution must total 1.');
export const assessmentDomainQuotaSchema = z.object({ domain: assessmentDomainSchema, minimum: z.number().int().nonnegative(), preferred: z.number().int().nonnegative(), maximum: z.number().int().nonnegative() }).strict().refine((value) => value.minimum <= value.preferred && value.preferred <= value.maximum, 'Domain quota must be ordered.');
export const assessmentParentQuotaSchema = z.object({ parentType: z.enum(['reading-passage', 'listening-activity']), format: z.string().min(1), count: z.number().int().nonnegative() }).strict();
export const assessmentSectionBlueprintSchema = z.object({ id: z.string().regex(/^assessment-section-blueprint-[a-z0-9-]+$/u), title: z.string().min(1), order: z.number().int().positive(), domains: z.array(assessmentDomainSchema).min(1), questionCount: z.number().int().positive(), recommendedMinutes: z.number().int().positive(), domainQuotas: z.array(assessmentDomainQuotaSchema).min(1), parentQuotas: z.array(assessmentParentQuotaSchema), difficultyDistribution: assessmentDifficultyDistributionSchema }).strict();
export const assessmentBlueprintSchema = z.object({ schemaVersion: z.literal(1), id: z.string().regex(/^assessment-blueprint-[a-z0-9-]+$/u), assessmentType: assessmentTypeSchema, level: z.enum(['N5', 'N4']), title: z.string().min(1), intendedUse: z.string().min(1), defaultQuestionCount: z.number().int().positive(), defaultTimeLimitMinutes: z.number().int().positive().nullable(), sections: z.array(assessmentSectionBlueprintSchema).min(1), targetLimits: z.object({ grammar: z.number().int().positive(), vocabulary: z.number().int().positive(), kanji: z.number().int().positive() }).strict(), completionRule: z.literal('all-placed-questions-answered-or-time-expired'), resultMode: z.enum(['full', 'compact']), releaseReady: z.boolean() }).strict();
export const assessmentPresetSchema = z.object({ schemaVersion: z.literal(1), id: z.string().regex(/^assessment-preset-[a-z0-9-]+$/u), assessmentType: assessmentTypeSchema, title: z.string().min(1), supportedLevels: z.array(z.enum(['N5', 'N4'])).min(1), defaultQuestionCount: z.number().int().positive(), defaultTimeLimitMinutes: z.number().int().positive().nullable(), domains: z.array(assessmentDomainSchema).min(1), difficultyDistribution: assessmentDifficultyDistributionSchema, selectionRules: z.array(z.string().min(1)).min(1), duplicateRules: z.array(z.string().min(1)).min(1), releaseReady: z.boolean() }).strict();
export const assessmentGenerationConfigSchema = z.object({ assessmentType: assessmentTypeSchema, level: z.enum(['N5', 'N4']), seed: z.string().min(1), lifecycleMode: assessmentLifecycleModeSchema, questionCount: z.number().int().positive().optional(), domains: z.array(assessmentDomainSchema).optional(), sectionIds: z.array(z.string()).optional(), curriculumUnitIds: z.array(z.string()).optional(), grammarTargetIds: z.array(z.string()).optional(), vocabularyTargetIds: z.array(z.string()).optional(), kanjiTargetIds: z.array(z.string()).optional(), excludedQuestionIds: z.array(z.string()).optional(), previouslySeenQuestionIds: z.array(z.string()).optional(), recentlySeenQuestionIds: z.array(z.string()).optional(), recentPassageIds: z.array(z.string()).optional(), recentListeningActivityIds: z.array(z.string()).optional(), weakTargetIds: z.array(z.string()).optional(), masteredTargetIds: z.array(z.string()).optional(), remediationMode: z.boolean().default(false), strictTimeLimit: z.boolean().default(false), resultMode: z.enum(['full', 'compact']).default('full') }).strict();
export const assessmentQuestionPlacementSchema = z.object({ id: z.string().regex(/^assessment-placement-question-[a-z0-9-]+$/u), sectionId: z.string().min(1), questionId: z.string().min(1), position: z.number().int().positive(), domain: assessmentDomainSchema, questionType: z.string().min(1), parentType: z.enum(['reading-passage', 'listening-activity']).nullable(), parentId: z.string().min(1).nullable(), primaryTargetId: z.string().min(1).nullable(), estimatedSeconds: z.number().int().positive() }).strict();
export const assessmentParentPlacementSchema = z.object({ id: z.string().regex(/^assessment-placement-parent-[a-z0-9-]+$/u), sectionId: z.string().min(1), parentType: z.enum(['reading-passage', 'listening-activity']), parentId: z.string().min(1), position: z.number().int().positive(), questionIds: z.array(z.string().min(1)).min(1) }).strict();
export const assessmentSectionSchema = z.object({ id: z.string().regex(/^assessment-section-[a-z0-9-]+$/u), blueprintSectionId: z.string().min(1), title: z.string().min(1), order: z.number().int().positive(), recommendedMinutes: z.number().int().positive(), strictTimeLimit: z.boolean(), questionPlacementIds: z.array(z.string()).min(1), parentPlacementIds: z.array(z.string()) }).strict();
export const assessmentConstraintRelaxationSchema = z.object({ order: z.number().int().positive(), constraint: z.enum(['unseen-preference', 'recent-question-exclusion', 'target-repetition-soft-limit', 'difficulty-tolerance', 'question-type-quota', 'parent-exposure-preference', 'requested-size']), reason: z.string().min(1), effect: z.string().min(1) }).strict();
export const assessmentScoringRuleSchema = z.object({ id: z.string().regex(/^assessment-scoring-[a-z0-9-]+$/u), ordinaryQuestionPoints: z.number().positive(), unansweredPoints: z.literal(0), negativeMarking: z.literal(false), domainWeights: z.partialRecord(assessmentDomainSchema, z.number().positive()), label: z.literal('JapanGo raw score') }).strict();
export const assessmentTimingRuleSchema = z.object({ id: z.string().regex(/^assessment-timing-[a-z0-9-]+$/u), mode: z.enum(['none', 'recommended', 'strict']), totalMinutes: z.number().int().positive().nullable(), sectionTransitionsSeconds: z.number().int().nonnegative(), playbackAndReplayIncluded: z.boolean(), resumable: z.boolean() }).strict();
export const assessmentSnapshotSchema = z.object({ schemaVersion: z.literal(1), id: z.string().regex(/^assessment-snapshot-[a-z0-9-]+$/u), assessmentType: assessmentTypeSchema, level: z.enum(['N5', 'N4']), seed: z.string().min(1), contentVersion: z.string().min(1), pipelineVersion: z.string().min(1), generationTimestamp: z.string().datetime(), lifecycleMode: assessmentLifecycleModeSchema, blueprintId: z.string().min(1), configuration: assessmentGenerationConfigSchema, sections: z.array(assessmentSectionSchema).min(1), questionPlacements: z.array(assessmentQuestionPlacementSchema).min(1), parentPlacements: z.array(assessmentParentPlacementSchema), scoringRule: assessmentScoringRuleSchema, timingRule: assessmentTimingRuleSchema, relaxedConstraints: z.array(assessmentConstraintRelaxationSchema), checksum: z.string().regex(/^sha256:[a-f0-9]{64}$/u), releaseReady: z.boolean() }).strict();
export const assessmentCollectionsSchema = z.object({ schemaVersion: z.literal(1), blueprints: z.array(assessmentBlueprintSchema), presets: z.array(assessmentPresetSchema), bundledExams: z.array(assessmentSnapshotSchema), sampleSnapshots: z.array(assessmentSnapshotSchema) }).strict();

export const assessmentExposureInputSchema = z.object({ questionExposure: z.record(z.string(), z.object({ count: z.number().int().nonnegative(), lastSeenAt: z.string().datetime().nullable(), correctCount: z.number().int().nonnegative(), incorrectCount: z.number().int().nonnegative(), confidence: z.number().min(0).max(100), masteryStatus: z.enum(['new', 'learning', 'weak', 'review', 'mastered']) }).strict()).default({}), parentExposure: z.record(z.string(), z.object({ count: z.number().int().nonnegative(), lastSeenAt: z.string().datetime().nullable() }).strict()).default({}), recentAssessmentIds: z.array(z.string()).default([]), recentQuestionIds: z.array(z.string()).default([]), recentPassageIds: z.array(z.string()).default([]), recentListeningActivityIds: z.array(z.string()).default([]) }).strict();
export const assessmentAnswerInputSchema = z.object({ questionId: z.string(), selectedOptionId: z.string().nullable(), timeUsedSeconds: z.number().int().nonnegative() }).strict();
export const readinessEstimateSchema = z.object({ label: z.enum(['Needs foundation', 'Developing', 'Approaching target', 'Likely ready', 'Strongly ready']), percentage: z.number().min(0).max(100), evidenceSufficient: z.boolean(), evidenceQuestionCount: z.number().int().nonnegative(), fullMockEquivalentCount: z.number().nonnegative(), majorDomainBelowThreshold: z.boolean(), explanation: z.string().min(1) }).strict();
export const assessmentAnswerResultSchema = z.object({ questionId: z.string(), selectedOptionId: z.string().nullable(), correctOptionId: z.string(), correct: z.boolean(), unanswered: z.boolean(), pointsEarned: z.number().nonnegative(), pointsAvailable: z.number().positive(), domain: assessmentDomainSchema, questionType: z.string(), difficultyRank: z.number().int().min(1).max(5), targetIds: z.array(z.string()), parentId: z.string().nullable(), supportingReferenceIds: z.array(z.string()), explanation: z.string().nullable(), reviewRecommendation: z.string(), lifecycle: z.enum(['development-only', 'release']) }).strict();
export const assessmentAggregateResultSchema = z.object({ key: z.string(), correct: z.number().int().nonnegative(), incorrect: z.number().int().nonnegative(), unanswered: z.number().int().nonnegative(), total: z.number().int().nonnegative(), rawScore: z.number().nonnegative(), weightedScore: z.number().nonnegative(), percentage: z.number().min(0).max(100) }).strict();
export const assessmentPlatformResultSchema = z.object({ schemaVersion: z.literal(1), id: z.string().regex(/^assessment-result-[a-z0-9-]+$/u), assessmentId: z.string(), rawScore: z.number().nonnegative(), weightedScore: z.number().nonnegative(), percentage: z.number().min(0).max(100), correctCount: z.number().int().nonnegative(), incorrectCount: z.number().int().nonnegative(), unansweredCount: z.number().int().nonnegative(), completionStatus: z.enum(['not-started', 'in-progress', 'completed', 'time-expired']), timeUsedSeconds: z.number().int().nonnegative(), sectionResults: z.array(assessmentAggregateResultSchema), domainResults: z.array(assessmentAggregateResultSchema), targetResults: z.array(assessmentAggregateResultSchema), answers: z.array(assessmentAnswerResultSchema), readiness: readinessEstimateSchema, label: z.literal('JapanGo assessment result'), checksum: z.string().regex(/^sha256:[a-f0-9]{64}$/u) }).strict();

export type AssessmentBlueprint = z.infer<typeof assessmentBlueprintSchema>;
export type AssessmentPreset = z.infer<typeof assessmentPresetSchema>;
export type AssessmentGenerationConfig = z.infer<typeof assessmentGenerationConfigSchema>;
export type AssessmentSnapshot = z.infer<typeof assessmentSnapshotSchema>;
export type AssessmentCollections = z.infer<typeof assessmentCollectionsSchema>;
export type AssessmentExposureInput = z.infer<typeof assessmentExposureInputSchema>;
export type AssessmentAnswerInput = z.infer<typeof assessmentAnswerInputSchema>;
export type ReadinessEstimate = z.infer<typeof readinessEstimateSchema>;
export type AssessmentPlatformResult = z.infer<typeof assessmentPlatformResultSchema>;
