import type { AssessmentQuestion } from '../../types/learning';
import { assessmentSeedSchema } from './schemas';

const rawQuestions: AssessmentQuestion[] = [
  { id: 'assessment-kana-01', position: 1, type: 'multiple-choice', category: 'reading', curriculumItemId: 'n5-reading-hiragana-a', prompt: 'Which sound does あ represent?', options: [{ id: 'a', label: 'a' }, { id: 'i', label: 'i' }, { id: 'u', label: 'u' }, { id: 'o', label: 'o' }], correctOptionId: 'a', explanation: 'あ is the hiragana character for the vowel sound “a”.' },
  { id: 'assessment-kana-02', position: 2, type: 'multiple-choice', category: 'reading', curriculumItemId: 'n5-reading-katakana-ko', prompt: 'Which katakana represents “ko”?', options: [{ id: 'ko', label: 'コ' }, { id: 'ni', label: 'ニ' }, { id: 'ro', label: 'ロ' }, { id: 'yo', label: 'ヨ' }], correctOptionId: 'ko', explanation: 'コ represents “ko”. Its two strokes are both angular.' },
  { id: 'assessment-kana-03', position: 3, type: 'multiple-choice', category: 'reading', curriculumItemId: 'n5-reading-hiragana-ki', prompt: 'What is the reading of き?', options: [{ id: 'sa', label: 'sa' }, { id: 'ki', label: 'ki' }, { id: 'chi', label: 'chi' }, { id: 'ke', label: 'ke' }], correctOptionId: 'ki', explanation: 'き is read “ki”.' },
  { id: 'assessment-kana-04', position: 4, type: 'multiple-choice', category: 'reading', curriculumItemId: 'n5-reading-katakana-me', prompt: 'What is the reading of メ?', options: [{ id: 'nu', label: 'nu' }, { id: 'no', label: 'no' }, { id: 'me', label: 'me' }, { id: 'ne', label: 'ne' }], correctOptionId: 'me', explanation: 'メ is the katakana character for “me”.' },

  { id: 'assessment-vocab-01', position: 5, type: 'multiple-choice', category: 'vocabulary', curriculumItemId: 'n5-vocab-gakkou', prompt: 'What does 学校 mean?', options: [{ id: 'hospital', label: 'hospital' }, { id: 'station', label: 'station' }, { id: 'school', label: 'school' }, { id: 'shop', label: 'shop' }], correctOptionId: 'school', explanation: '学校（がっこう）means “school”.' },
  { id: 'assessment-vocab-02', position: 6, type: 'multiple-choice', category: 'vocabulary', curriculumItemId: 'n5-vocab-tomodachi', prompt: 'Choose the meaning of 友達.', options: [{ id: 'teacher', label: 'teacher' }, { id: 'friend', label: 'friend' }, { id: 'family', label: 'family' }, { id: 'student', label: 'student' }], correctOptionId: 'friend', explanation: '友達（ともだち）means “friend”.' },
  { id: 'assessment-vocab-03', position: 7, type: 'multiple-choice', category: 'vocabulary', curriculumItemId: 'n5-vocab-ashita', prompt: 'Which word means “tomorrow”?', options: [{ id: 'kyou', label: '今日' }, { id: 'ashita', label: '明日' }, { id: 'kinou', label: '昨日' }, { id: 'asa', label: '朝' }], correctOptionId: 'ashita', explanation: '明日（あした）means “tomorrow”.' },
  { id: 'assessment-vocab-04', position: 8, type: 'multiple-choice', category: 'vocabulary', curriculumItemId: 'n5-vocab-nomimasu', prompt: 'What does 飲みます mean?', options: [{ id: 'eat', label: 'to eat' }, { id: 'read', label: 'to read' }, { id: 'drink', label: 'to drink' }, { id: 'buy', label: 'to buy' }], correctOptionId: 'drink', explanation: '飲みます（のみます）is the polite form of “to drink”.' },

  { id: 'assessment-kanji-01', position: 9, type: 'choose-reading', category: 'kanji', curriculumItemId: 'n5-kanji-yama', prompt: 'Choose the reading of 山 in 山です。', options: [{ id: 'kawa', label: 'かわ' }, { id: 'yama', label: 'やま' }, { id: 'mori', label: 'もり' }, { id: 'sora', label: 'そら' }], correctOptionId: 'yama', explanation: '山 is read やま when it means “mountain” on its own.' },
  { id: 'assessment-kanji-02', position: 10, type: 'choose-reading', category: 'kanji', curriculumItemId: 'n5-kanji-hito', prompt: 'How is 人 read in あの人?', options: [{ id: 'hito', label: 'ひと' }, { id: 'jin', label: 'じん' }, { id: 'nin', label: 'にん' }, { id: 'iri', label: 'いり' }], correctOptionId: 'hito', explanation: 'In あの人 (“that person”), 人 is read ひと.' },
  { id: 'assessment-kanji-03', position: 11, type: 'choose-reading', category: 'kanji', curriculumItemId: 'n5-kanji-mizu', prompt: 'Choose the reading and meaning of 水.', options: [{ id: 'mizu', label: 'みず — water' }, { id: 'hi', label: 'ひ — fire' }, { id: 'ki', label: 'き — tree' }, { id: 'tsuchi', label: 'つち — soil' }], correctOptionId: 'mizu', explanation: '水 is commonly read みず and means “water”.' },
  { id: 'assessment-kanji-04', position: 12, type: 'choose-reading', category: 'kanji', curriculumItemId: 'n5-kanji-kawa', prompt: '川（___）を見ます。', options: [{ id: 'yama', label: 'やま' }, { id: 'kawa', label: 'かわ' }, { id: 'mizu', label: 'みず' }, { id: 'tsuki', label: 'つき' }], correctOptionId: 'kawa', explanation: '川 is read かわ here: “I look at the river.”' },

  { id: 'assessment-grammar-01', position: 13, type: 'fill-blank', category: 'grammar', curriculumItemId: 'n5-grammar-wa', prompt: 'わたし ___ がくせいです。', options: [{ id: 'wa', label: 'は' }, { id: 'wo', label: 'を' }, { id: 'de', label: 'で' }, { id: 'ni', label: 'に' }], correctOptionId: 'wa', explanation: 'は marks わたし as the topic: “As for me, I am a student.”' },
  { id: 'assessment-grammar-02', position: 14, type: 'fill-blank', category: 'grammar', curriculumItemId: 'n5-grammar-wo', prompt: 'パン ___ 食べます。', options: [{ id: 'ga', label: 'が' }, { id: 'wo', label: 'を' }, { id: 'no', label: 'の' }, { id: 'mo', label: 'も' }], correctOptionId: 'wo', explanation: 'を marks パン as the object of 食べます.' },
  { id: 'assessment-grammar-03', position: 15, type: 'fill-blank', category: 'grammar', curriculumItemId: 'n5-grammar-de', prompt: '学校 ___ 日本語を勉強します。', options: [{ id: 'de', label: 'で' }, { id: 'ni', label: 'に' }, { id: 'wo', label: 'を' }, { id: 'no', label: 'の' }], correctOptionId: 'de', explanation: 'で marks the place where the action of studying happens.' },
  { id: 'assessment-grammar-04', position: 16, type: 'fill-blank', category: 'grammar', curriculumItemId: 'n5-grammar-no', prompt: 'これは田中さん ___ 本です。', options: [{ id: 'ga', label: 'が' }, { id: 'no', label: 'の' }, { id: 'ni', label: 'に' }, { id: 'de', label: 'で' }], correctOptionId: 'no', explanation: 'の links 田中さん and 本 to show possession: “Tanaka’s book.”' },
  { id: 'assessment-grammar-05', position: 17, type: 'multiple-choice', category: 'grammar', curriculumItemId: 'n5-grammar-masen', prompt: 'Which sentence politely means “I do not drink coffee”?', options: [{ id: 'a', label: 'コーヒーを飲みます。' }, { id: 'b', label: 'コーヒーを飲みません。' }, { id: 'c', label: 'コーヒーが飲みです。' }, { id: 'd', label: 'コーヒーを食べません。' }], correctOptionId: 'b', explanation: '飲みません is the polite negative form of 飲みます.' },

  { id: 'assessment-reading-01', position: 18, type: 'short-reading', category: 'reading', curriculumItemId: 'n5-vocab-kyou', passage: 'きょうは月曜日です。わたしは学校へ行きます。', prompt: 'Where is the speaker going today?', options: [{ id: 'home', label: 'Home' }, { id: 'school', label: 'School' }, { id: 'station', label: 'Station' }, { id: 'shop', label: 'Shop' }], correctOptionId: 'school', explanation: '学校へ行きます means “I go to school.”' },
  { id: 'assessment-reading-02', position: 19, type: 'short-reading', category: 'reading', curriculumItemId: 'n5-vocab-gohan', passage: '田中さんは七時にご飯を食べます。それから、水を飲みます。', prompt: 'What does Tanaka drink after eating?', options: [{ id: 'tea', label: 'Tea' }, { id: 'coffee', label: 'Coffee' }, { id: 'water', label: 'Water' }, { id: 'milk', label: 'Milk' }], correctOptionId: 'water', explanation: 'それから、水を飲みます means “After that, (Tanaka) drinks water.”' },
  { id: 'assessment-reading-03', position: 20, type: 'short-reading', category: 'reading', curriculumItemId: 'n5-vocab-tomodachi', passage: 'あした、友達と山へ行きます。九時に駅で会います。', prompt: 'When and where will they meet?', options: [{ id: 'a', label: 'At the mountain at 9' }, { id: 'b', label: 'At the station at 9' }, { id: 'c', label: 'At school tomorrow' }, { id: 'd', label: 'At the station today' }], correctOptionId: 'b', explanation: '九時に駅で会います says they will meet at the station at nine.' },
];

export const assessmentQuestionSeed = assessmentSeedSchema.parse(rawQuestions);
