/**
 * Readings for authored lesson examples that are deliberately not curriculum
 * targets. They remain tappable, but do not become vocabulary cards or affect
 * review scheduling. Dynamic curriculum words are resolved from SQLite.
 */
export interface LessonSupplementaryReading {
  title: string;
  reading: string;
  meaning?: string;
}

export const lessonSupplementaryReadings: readonly LessonSupplementaryReading[] = [
  { title: '田中', reading: 'たなか', meaning: 'Tanaka (a surname)' },
  { title: '蓮', reading: 'れん', meaning: 'Ren (a given name)' },
  { title: '本', reading: 'ほん', meaning: 'book' },
  { title: '新聞', reading: 'しんぶん', meaning: 'newspaper' },
  { title: '母', reading: 'はは', meaning: 'my mother' },
  { title: '先生', reading: 'せんせい', meaning: 'teacher' },
  { title: '学生', reading: 'がくせい', meaning: 'student' },
  { title: '友だち', reading: 'ともだち', meaning: 'friend' },
  { title: '日本語', reading: 'にほんご', meaning: 'Japanese language' },
  { title: '食べる', reading: 'たべる', meaning: 'to eat' },
  { title: '食べます', reading: 'たべます', meaning: 'eat (polite)' },
  { title: '食べて', reading: 'たべて', meaning: 'eat (te-form)' },
  { title: '食べない', reading: 'たべない', meaning: 'do not eat' },
  { title: '食べません', reading: 'たべません', meaning: 'do not eat (polite)' },
  { title: '食べました', reading: 'たべました', meaning: 'ate (polite)' },
  { title: '読んでいます', reading: 'よんでいます', meaning: 'is reading' },
  { title: '読みました', reading: 'よみました', meaning: 'read (past)' },
  { title: '読む', reading: 'よむ', meaning: 'to read' },
  { title: '見ています', reading: 'みています', meaning: 'is watching' },
  { title: '見る', reading: 'みる', meaning: 'to watch or see' },
  { title: '飲んでいます', reading: 'のんでいます', meaning: 'is drinking' },
  { title: '飲む', reading: 'のむ', meaning: 'to drink' },
  { title: 'ご飯', reading: 'ごはん', meaning: 'meal or rice' },
  { title: '学校', reading: 'がっこう', meaning: 'school' },
  { title: '行きます', reading: 'いきます', meaning: 'go (polite)' },
  { title: '行って', reading: 'いって', meaning: 'go (te-form)' },
  { title: '行く', reading: 'いく', meaning: 'to go' },
  { title: 'ドア', reading: 'どあ', meaning: 'door' },
  { title: '開けて', reading: 'あけて', meaning: 'open (te-form)' },
  { title: '開く', reading: 'あく', meaning: 'to open' },
  { title: '部屋', reading: 'へや', meaning: 'room' },
  { title: '入ります', reading: 'はいります', meaning: 'enter (polite)' },
  { title: '入る', reading: 'はいる', meaning: 'to enter' },
  { title: '高い', reading: 'たかい', meaning: 'high or expensive' },
  { title: '静か', reading: 'しずか', meaning: 'quiet' },
  { title: 'もう一度', reading: 'もういちど', meaning: 'once more' },
  { title: '聞いてください', reading: 'きいてください', meaning: 'please listen' },
  { title: '聞く', reading: 'きく', meaning: 'to listen or ask' },
  { title: '確認します', reading: 'かくにんします', meaning: 'confirm (polite)' },
  { title: '確認', reading: 'かくにん', meaning: 'confirmation' },
  { title: '勉強している', reading: 'べんきょうしている', meaning: 'is studying' },
  { title: '勉強', reading: 'べんきょう', meaning: 'study' },
  { title: '今日', reading: 'きょう', meaning: 'today' },
  { title: '場面', reading: 'ばめん', meaning: 'situation or scene' },
  { title: '話します', reading: 'はなします', meaning: 'speak (polite)' },
  { title: '朝', reading: 'あさ', meaning: 'morning' },
  { title: '駅', reading: 'えき', meaning: 'station' },
  { title: '近く', reading: 'ちかく', meaning: 'nearby' },
  { title: '待ちました', reading: 'まちました', meaning: 'waited' },
  { title: '二人', reading: 'ふたり', meaning: 'two people' },
  { title: '相談', reading: 'そうだん', meaning: 'consultation' },
  { title: '今', reading: 'いま', meaning: 'now' },
  { title: '何', reading: 'なに', meaning: 'what' },
  { title: '一番', reading: 'いちばん', meaning: 'most' },
  { title: '大切', reading: 'たいせつ', meaning: 'important' },
  { title: '急がずに', reading: 'いそがずに', meaning: 'without rushing' },
  { title: '理由', reading: 'りゆう', meaning: 'reason' },
  { title: '自分', reading: 'じぶん', meaning: 'oneself' },
  { title: '考え', reading: 'かんがえ', meaning: 'thought or idea' },
  { title: '短く', reading: 'みじかく', meaning: 'briefly' },
  { title: '説明しました', reading: 'せつめいしました', meaning: 'explained' },
  { title: '相手', reading: 'あいて', meaning: 'the other person' },
  { title: '分からない', reading: 'わからない', meaning: 'do not understand' },
  { title: '言葉', reading: 'ことば', meaning: 'word or language' },
  { title: '時', reading: 'とき', meaning: 'when or time' },
  { title: '言って', reading: 'いって', meaning: 'say (te-form)' },
  { title: '会話', reading: 'かいわ', meaning: 'conversation' },
  { title: '途中', reading: 'とちゅう', meaning: 'in the middle of' },
  { title: '予定', reading: 'よてい', meaning: 'plan or schedule' },
  { title: '変わりました', reading: 'かわりました', meaning: 'changed' },
  { title: '先', reading: 'さき', meaning: 'ahead or first' },
  { title: '決めれば', reading: 'きめれば', meaning: 'if (someone) decides' },
  { title: '大丈夫', reading: 'だいじょうぶ', meaning: 'all right' },
  { title: '開き', reading: 'ひらき', meaning: 'opened' },
  { title: '新しく', reading: 'あたらしく', meaning: 'newly' },
  { title: '覚えた', reading: 'おぼえた', meaning: 'learned or remembered' },
  { title: '言葉', reading: 'ことば', meaning: 'word or language' },
  { title: '例文', reading: 'れいぶん', meaning: 'example sentence' },
  { title: '一緒に', reading: 'いっしょに', meaning: 'together' },
  { title: '書きました', reading: 'かきました', meaning: 'wrote' },
  { title: '声', reading: 'こえ', meaning: 'voice' },
  { title: '出して', reading: 'だして', meaning: 'put out' },
  { title: '昼ごろ', reading: 'ひるごろ', meaning: 'around noon' },
  { title: '次', reading: 'つぎ', meaning: 'next' },
  { title: '行動', reading: 'こうどう', meaning: 'action' },
  { title: '比べました', reading: 'くらべました', meaning: 'compared' },
  { title: '一つ', reading: 'ひとつ', meaning: 'one' },
  { title: '早く', reading: 'はやく', meaning: 'quickly or early' },
  { title: '終わります', reading: 'おわります', meaning: 'finish (polite)' },
  { title: '分かりやすく', reading: 'わかりやすく', meaning: 'clearly' },
  { title: '都合', reading: 'つごう', meaning: 'convenience or circumstances' },
  { title: '無理', reading: 'むり', meaning: 'unreasonable or impossible' },
  { title: '方法', reading: 'ほうほう', meaning: 'method' },
  { title: '選ぶ', reading: 'えらぶ', meaning: 'to choose' },
  { title: '帰る', reading: 'かえる', meaning: 'to return home' },
  { title: '前', reading: 'まえ', meaning: 'before' },
  { title: '明日', reading: 'あした', meaning: 'tomorrow' },
  { title: '必要', reading: 'ひつよう', meaning: 'necessary' },
  { title: '物', reading: 'もの', meaning: 'thing' },
  { title: '連絡', reading: 'れんらく', meaning: 'contact' },
  { title: '時間', reading: 'じかん', meaning: 'time' },
  { title: '正しい', reading: 'ただしい', meaning: 'correct' },
  { title: '合う', reading: 'あう', meaning: 'to fit or suit' },
  { title: '言い方', reading: 'いいかた', meaning: 'way of saying' },
  { title: '感じました', reading: 'かんじました', meaning: 'felt' },
  { title: '家', reading: 'いえ', meaning: 'home' },
  { title: '着いた', reading: 'ついた', meaning: 'arrived' },
  { title: '短い', reading: 'みじかい', meaning: 'short' },
  { title: '翌日', reading: 'よくじつ', meaning: 'the next day' },
  { title: '返事', reading: 'へんじ', meaning: 'reply' },
  { title: '来ました', reading: 'きました', meaning: 'came' },
  { title: '内容', reading: 'ないよう', meaning: 'content' },
  { title: '使って', reading: 'つかって', meaning: 'use (te-form)' },
  { title: '自然', reading: 'しぜん', meaning: 'natural' },
  { title: '経験', reading: 'けいけん', meaning: 'experience' },
  { title: '通して', reading: 'とおして', meaning: 'through' },
  { title: '知る', reading: 'しる', meaning: 'to know' },
  { title: '練習', reading: 'れんしゅう', meaning: 'practice' },
  { title: '続けよう', reading: 'つづけよう', meaning: 'let us continue' },
  { title: '読んだ人', reading: 'よんだひと', meaning: 'the person who read' },
  { title: '最後', reading: 'さいご', meaning: 'last or finally' },
  { title: '学んだ', reading: 'まなんだ', meaning: 'learned' },
  { title: '質問', reading: 'しつもん', meaning: 'question' },
  { title: '伝える', reading: 'つたえる', meaning: 'to convey' },
  { title: '小さな', reading: 'ちいさな', meaning: 'small' },
  { title: '何度も', reading: 'なんども', meaning: 'many times' },
  { title: '実際', reading: 'じっさい', meaning: 'actually' },
  { title: '生活', reading: 'せいかつ', meaning: 'daily life' },
  { title: '使える', reading: 'つかえる', meaning: 'can use' },
  // Contextual readings used by the varied reading/listening situations.
  // These are support text, not additional review targets.
  { title: '図書館', reading: 'としょかん', meaning: 'library' },
  { title: '出る', reading: 'でる', meaning: 'to leave or depart' },
  { title: '聞こえなかった', reading: 'きこえなかった', meaning: 'could not hear' },
  { title: '教室', reading: 'きょうしつ', meaning: 'classroom' },
  { title: '始めます', reading: 'はじめます', meaning: 'start (polite)' },
  { title: '字', reading: 'じ', meaning: 'written character' },
  { title: '見せて', reading: 'みせて', meaning: 'show me' },
  { title: '値段', reading: 'ねだん', meaning: 'price' },
  { title: '比べます', reading: 'くらべます', meaning: 'compare (polite)' },
  { title: '公園', reading: 'こうえん', meaning: 'park' },
  { title: '会う場所', reading: 'あうばしょ', meaning: 'meeting place' },
  { title: '聞こえませんでした', reading: 'きこえませんでした', meaning: 'could not hear (polite)' },
  { title: '病院', reading: 'びょういん', meaning: 'hospital' },
  { title: '予約', reading: 'よやく', meaning: 'reservation' },
  { title: '電話', reading: 'でんわ', meaning: 'telephone' },
  { title: '市役所', reading: 'しやくしょ', meaning: 'city hall' },
  { title: '書く場所', reading: 'かくばしょ', meaning: 'place to write' },
  { title: '会社', reading: 'かいしゃ', meaning: 'company' },
  { title: '会議', reading: 'かいぎ', meaning: 'meeting' },
  { title: '買い物', reading: 'かいもの', meaning: 'shopping' },
  { title: '意味', reading: 'いみ', meaning: 'meaning' },
  { title: '案内所', reading: 'あんないじょ', meaning: 'information desk' },
  { title: '地図', reading: 'ちず', meaning: 'map' },
  { title: '道', reading: 'みち', meaning: 'road or route' },
  { title: '体育館', reading: 'たいいくかん', meaning: 'gymnasium' },
  { title: '入口', reading: 'いりぐち', meaning: 'entrance' },
  { title: '運動ぐつ', reading: 'うんどうぐつ', meaning: 'sports shoes' },
  { title: '郵便局', reading: 'ゆうびんきょく', meaning: 'post office' },
  { title: '住所', reading: 'じゅうしょ', meaning: 'address' },
  { title: '数字', reading: 'すうじ', meaning: 'number or numeral' },
  { title: '切手', reading: 'きって', meaning: 'stamp' },
  { title: '午後', reading: 'ごご', meaning: 'afternoon' },
  { title: '案内', reading: 'あんない', meaning: 'guidance or notice' },
  { title: '見つけました', reading: 'みつけました', meaning: 'found' },
  { title: '早口', reading: 'はやくち', meaning: 'fast speech' },
  { title: '伝えました', reading: 'つたえました', meaning: 'told or conveyed' },
  { title: '探しました', reading: 'さがしました', meaning: 'looked for' },
  { title: '聞き返す', reading: 'ききかえす', meaning: 'ask again' },
  { title: '用事', reading: 'ようじ', meaning: 'errand or matter to do' },
  { title: '出し合いました', reading: 'だしあいました', meaning: 'shared with each other' },
  { title: '選んだ', reading: 'えらんだ', meaning: 'chose' },
  { title: '頼みました', reading: 'たのみました', meaning: 'asked or requested' },
  { title: '言い直して', reading: 'いいなおして', meaning: 'said again' },
  { title: '並んでいました', reading: 'ならんでいました', meaning: 'were lined up' },
  { title: '休日', reading: 'きゅうじつ', meaning: 'day off' },
  { title: '持ってきた', reading: 'もってきた', meaning: 'brought' },
  { title: '役に立つ', reading: 'やくにたつ', meaning: 'be useful' },
  { title: '聞き取れない', reading: 'ききとれない', meaning: 'cannot catch what was said' },
  { title: '落ち着いて', reading: 'おちついて', meaning: 'calmly' },
  { title: '話し終わって', reading: 'はなしおわって', meaning: 'after finishing speaking' },
  { title: '一文', reading: 'いちぶん', meaning: 'one sentence' },
  { title: '書き直しました', reading: 'かきなおしました', meaning: 'rewrote' },
];
