import path from "node:path";

import type { LearningContentCollections, Question, QuestionOption, QuestionTargetRelationship } from "../../src/features/learning-content/schemas";
import { assessmentBlueprintSchema, assessmentPresetSchema, type AssessmentBlueprint, type AssessmentPreset } from "../../src/features/assessment/platform-schemas";
import { OUTPUT_ROOT, SOURCE_PATHS } from "./config";
import { isDirectExecution, runCli } from "./lib/cli";
import { readJson, writeJson } from "./lib/fs-utils";
import type { GrammarRecord } from "./schemas/content-schemas";

const SOURCE_ID = "japango-assessment-n5-grammar-bridge"; const ATTRIBUTION = ["Original JapanGo editorial assessment bridge content; JLPT-aligned, not official JLPT material."];
function compareStable(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
const difficulty = { jlptLevel: "N5" as const, rank: 2 };

function section(id: string, title: string, order: number, questionCount: number, recommendedMinutes: number, quotas: AssessmentBlueprint['sections'][number]['domainQuotas'], parents: AssessmentBlueprint['sections'][number]['parentQuotas'], distribution: AssessmentBlueprint['sections'][number]['difficultyDistribution']): AssessmentBlueprint['sections'][number] { return { id, title, order, domains: quotas.map(({ domain }) => domain), questionCount, recommendedMinutes, domainQuotas: quotas, parentQuotas: parents, difficultyDistribution: distribution }; }
function quota(domain: "vocabulary" | "kanji" | "grammar" | "reading" | "listening", count: number) { return { domain, minimum: count, preferred: count, maximum: count }; }

const BLUEPRINTS: AssessmentBlueprint[] = [
  assessmentBlueprintSchema.parse({ schemaVersion: 1, id: "assessment-blueprint-full-mock-n5", assessmentType: "full-mock", level: "N5", title: "JapanGo N5 full mock", intendedUse: "A complete five-domain N5-aligned development assessment.", defaultQuestionCount: 90, defaultTimeLimitMinutes: 90, sections: [section("assessment-section-blueprint-n5-language", "Vocabulary and Kanji", 1, 30, 25, [quota("vocabulary", 18), quota("kanji", 12)], [], { easy: .4, medium: .5, hard: .1 }), section("assessment-section-blueprint-n5-grammar-reading", "Grammar and Reading", 2, 35, 40, [quota("grammar", 18), quota("reading", 17)], [{ parentType: "reading-passage", format: "short", count: 3 }, { parentType: "reading-passage", format: "medium", count: 1 }, { parentType: "reading-passage", format: "practical", count: 1 }], { easy: .4, medium: .5, hard: .1 }), section("assessment-section-blueprint-n5-listening", "Listening", 3, 25, 25, [quota("listening", 25)], [{ parentType: "listening-activity", format: "short-monologue", count: 3 }, { parentType: "listening-activity", format: "dialogue", count: 3 }, { parentType: "listening-activity", format: "practical-information", count: 1 }, { parentType: "listening-activity", format: "appropriate-response", count: 3 }], { easy: .4, medium: .5, hard: .1 })], targetLimits: { grammar: 2, vocabulary: 2, kanji: 2 }, completionRule: "all-placed-questions-answered-or-time-expired", resultMode: "full", releaseReady: false }),
  assessmentBlueprintSchema.parse({ schemaVersion: 1, id: "assessment-blueprint-full-mock-n4", assessmentType: "full-mock", level: "N4", title: "JapanGo N4 full mock", intendedUse: "A complete five-domain N4-aligned development assessment with controlled N5 prerequisite review.", defaultQuestionCount: 112, defaultTimeLimitMinutes: 115, sections: [section("assessment-section-blueprint-n4-language", "Vocabulary and Kanji", 1, 35, 30, [quota("vocabulary", 22), quota("kanji", 13)], [], { easy: .25, medium: .55, hard: .2 }), section("assessment-section-blueprint-n4-grammar-reading", "Grammar and Reading", 2, 45, 55, [quota("grammar", 24), quota("reading", 21)], [{ parentType: "reading-passage", format: "short", count: 3 }, { parentType: "reading-passage", format: "medium", count: 2 }, { parentType: "reading-passage", format: "practical", count: 1 }], { easy: .25, medium: .55, hard: .2 }), section("assessment-section-blueprint-n4-listening", "Listening", 3, 32, 30, [quota("listening", 32)], [{ parentType: "listening-activity", format: "short-monologue", count: 4 }, { parentType: "listening-activity", format: "dialogue", count: 4 }, { parentType: "listening-activity", format: "practical-information", count: 1 }, { parentType: "listening-activity", format: "appropriate-response", count: 4 }], { easy: .25, medium: .55, hard: .2 })], targetLimits: { grammar: 2, vocabulary: 2, kanji: 2 }, completionRule: "all-placed-questions-answered-or-time-expired", resultMode: "full", releaseReady: false }),
];

const PRESET_CONFIG: Array<[AssessmentPreset['assessmentType'], string, number, number | null, AssessmentPreset['domains']]> = [
  ["full-mock", "Full mock exam", 90, 90, ["vocabulary","kanji","grammar","reading","listening"]], ["section-exam", "Section exam", 20, 25, ["vocabulary","kanji","grammar"]], ["quick-practice", "Quick practice", 10, 10, ["vocabulary","kanji","grammar"]], ["daily-challenge", "Daily challenge", 10, 10, ["vocabulary","kanji","grammar","reading","listening"]], ["weak-area", "Weak-area assessment", 15, 15, ["vocabulary","kanji","grammar","reading","listening"]], ["mixed-review", "Mixed review", 20, 20, ["vocabulary","kanji","grammar","reading","listening"]], ["curriculum-unit-test", "Curriculum-unit test", 15, 15, ["vocabulary","kanji","grammar"]], ["grammar-mastery", "Grammar mastery test", 15, 15, ["grammar"]], ["vocabulary-mastery", "Vocabulary mastery test", 15, 12, ["vocabulary"]], ["kanji-mastery", "Kanji mastery test", 15, 12, ["kanji"]], ["reading-practice", "Reading practice set", 12, 20, ["reading"]], ["listening-practice", "Listening practice set", 12, 20, ["listening"]],
];
const PRESETS: AssessmentPreset[] = PRESET_CONFIG.map(([assessmentType, title, defaultQuestionCount, defaultTimeLimitMinutes, domains]) => assessmentPresetSchema.parse({ schemaVersion: 1, id: `assessment-preset-${assessmentType}`, assessmentType, title, supportedLevels: ["N5", "N4"], defaultQuestionCount, defaultTimeLimitMinutes, domains, difficultyDistribution: assessmentType === "weak-area" ? { easy: .3, medium: .55, hard: .15 } : { easy: .4, medium: .5, hard: .1 }, selectionRules: ["deterministic-seed", "lifecycle-eligibility", "least-exposed-first", "coherent-parent-groups"], duplicateRules: ["unique-question", "unique-parent", "target-soft-limit-two", "duplicate-family-control"], releaseReady: false }));

export async function authorAssessmentContent(): Promise<void> {
  const [content, n5Grammar] = await Promise.all([readJson<LearningContentCollections>(path.join(OUTPUT_ROOT, "learning-content/index.json")), readJson<GrammarRecord[]>(path.join(OUTPUT_ROOT, "grammar/n5.json"))]);
  const focusViews = content.grammarExampleViews.filter(({ role }) => role === "focus"); const selected = n5Grammar.filter((grammar) => focusViews.some(({ grammarId }) => grammarId === grammar.id)).slice(0, 15); const sentenceById = new Map(content.sentences.map((sentence) => [sentence.id, sentence])); const questions: Question[] = []; const options: QuestionOption[] = []; const targets: QuestionTargetRelationship[] = []; const metadata: LearningContentCollections['learningItemMetadata'] = [];
  for (const [index, grammar] of selected.entries()) { const view = focusViews.find(({ grammarId }) => grammarId === grammar.id); const sentence = sentenceById.get(view?.sentenceId ?? ''); if (!sentence) throw new Error(`Missing N5 bridge sentence for ${grammar.id}`); const alternatives = selected.slice(index + 1).concat(selected.slice(0, index + 1)).map((candidate) => { const candidateView = focusViews.find(({ grammarId }) => grammarId === candidate.id); return sentenceById.get(candidateView?.sentenceId ?? ''); }).filter((value): value is NonNullable<typeof value> => Boolean(value)).slice(0, 3); const serial = String(index + 1).padStart(3, "0");
    const records = [{ suffix: "meaning", prompt: `Which meaning matches “${sentence.japanese}”?`, values: [sentence.english, ...alternatives.map(({ english }) => english)] }, { suffix: "recognition", prompt: `Which sentence uses the N5 pattern “${grammar.pattern}” in target ${serial}?`, values: [sentence.japanese, ...alternatives.map(({ japanese }) => japanese)] }];
    for (const record of records) { const id = `question-grammar-n5-bridge-${serial}-${record.suffix}`; const optionIds = record.values.map((_, optionIndex) => `question-option-grammar-n5-bridge-${serial}-${record.suffix}-${optionIndex + 1}`); questions.push({ schemaVersion: 1, id, domain: "grammar", presentation: "multiple-choice", responseType: "single-select", prompt: { text: record.prompt, language: "bilingual" }, stimulusReferences: [{ type: "sentence", id: sentence.id }], correctOptionIds: [optionIds[0] as string], explanation: `${grammar.pattern}: ${sentence.english} Each distractor is a valid canonical sentence but represents a different grammar target. Common mistake: choosing a grammatical sentence that does not use the named target.`, difficulty, examMetadata: { jlptLevel: "N5", section: "grammar", formatCode: `bridge-${record.suffix}`, recommendedSeconds: 35 }, usageContexts: ["assessment", "review"], tags: ["phase8-bridge", `type-${record.suffix}`].sort(compareStable), sourceIds: [SOURCE_ID], attribution: ATTRIBUTION, confidence: .96, needsReview: false, releaseReady: false }); options.push(...record.values.map((text, optionIndex) => ({ schemaVersion: 1 as const, id: optionIds[optionIndex] as string, questionId: id, position: optionIndex + 1, content: { type: "text" as const, text, language: record.suffix === "meaning" ? "en" as const : "ja" as const }, feedback: optionIndex === 0 ? "This matches the targeted canonical N5 grammar example." : "This belongs to another canonical grammar example.", confidence: .96, needsReview: false, releaseReady: false }))); targets.push({ schemaVersion: 1, id: `question-target-grammar-n5-bridge-${serial}-${record.suffix}`, questionId: id, targetType: "grammar", targetId: grammar.id, role: "primary", skill: record.suffix === "meaning" ? "meaning" : "form", confidence: .96, needsReview: false, releaseReady: false }); metadata.push({ schemaVersion: 1, id: `learning-item-question-grammar-n5-bridge-${serial}-${record.suffix}`, itemType: "question", itemId: id, reviewable: true, skills: [record.suffix === "meaning" ? "meaning-recognition" : "form-recognition"], availableModes: ["assessment", "quiz"], estimatedReviewSeconds: 35, tags: ["phase8-n5-grammar-bridge"], confidence: .96, needsReview: false, releaseReady: false }); }
  }
  const bridge = { schemaVersion: 1, questions: questions.sort((a,b)=>compareStable(a.id,b.id)), questionOptions: options.sort((a,b)=>compareStable(a.questionId,b.questionId)||a.position-b.position), questionTargetRelationships: targets.sort((a,b)=>compareStable(a.id,b.id)), learningItemMetadata: metadata.sort((a,b)=>compareStable(a.id,b.id)), editorialDecision: { requiredByAudit: true, reason: "The Phase 8 pre-implementation audit found zero standalone N5 grammar questions, preventing five-domain N5 mock assembly.", canonicalRecordsAdded: 0, bridgeQuestionsAdded: questions.length } };
  await Promise.all([writeJson(SOURCE_PATHS.assessmentBlueprints, BLUEPRINTS), writeJson(SOURCE_PATHS.assessmentPresets, PRESETS), writeJson(SOURCE_PATHS.assessmentBundledSeeds, { schemaVersion: 1, N5: Array.from({length:5},(_,index)=>({ id:`assessment-bundled-mock-n5-${index+1}`, seed:`japango-n5-mock-${String(index+1).padStart(3,"0")}-v1` })), N4: Array.from({length:5},(_,index)=>({ id:`assessment-bundled-mock-n4-${index+1}`, seed:`japango-n4-mock-${String(index+1).padStart(3,"0")}-v1` })) }), writeJson(SOURCE_PATHS.assessmentScoringModel, { schemaVersion: 1, label: "JapanGo raw score", ordinaryQuestionPoints: 1, unansweredPoints: 0, negativeMarking: false, sectionAndDomainBreakdowns: true }), writeJson(SOURCE_PATHS.assessmentReadinessModel, { schemaVersion: 1, labels: ["Needs foundation","Developing","Approaching target","Likely ready","Strongly ready"], strongEvidenceMinimumQuestions: 180, strongEvidenceMinimumFullMocks: 2, minimumMajorDomainPercentage: 50, officialScoreClaim: false }), writeJson(SOURCE_PATHS.assessmentEditorialDecisions, { schemaVersion: 1, decisions: [{ id: "phase8-development-lifecycle", decision: "All bundled assessments remain development-only until curriculum approval." }, { id: "phase8-n5-bridge", decision: "Add exactly 30 original N5 grammar bridge questions after the pre-implementation audit established a blocking zero-question gap." }, { id: "phase8-audio", decision: "Use future audio keys; generate no TTS files." }] }), writeJson(SOURCE_PATHS.assessmentN5GrammarBridge, bridge)]);
  console.log(`Authored ${BLUEPRINTS.length} blueprints, ${PRESETS.length} presets, and ${questions.length} audited N5 grammar bridge questions.`);
}

if (isDirectExecution(import.meta.url)) runCli(authorAssessmentContent);
