import path from "node:path";
import type { LearningContentCollections } from "../../src/features/learning-content/schemas";
import { OUTPUT_ROOT } from "./config";
import { isDirectExecution, runCli } from "./lib/cli";
import { readJson, writeJson, writeText } from "./lib/fs-utils";
import type { GrammarRecord, KanjiRecord } from "./schemas/content-schemas";

const names = ["phase9-5-lifecycle-rule-audit","phase9-5-blocked-grammar-parent-audit","phase9-5-grammar-parent-review","phase9-5-sentence-parent-review","phase9-5-grammar-question-repair","phase9-5-grammar-release-readiness","phase9-5-kanji-exposure-gap-audit","phase9-5-kanji-support-repair","phase9-5-supporting-vocabulary-added","phase9-5-supporting-sentences-added","phase9-5-supporting-questions-added","phase9-5-lifecycle-before-after","phase9-5-release-bundle-integrity","phase9-5-manifest-determinism-investigation","phase9-5-manifest-determinism-result","phase9-5-assessment-impact","phase9-5-final-summary"] as const;
export async function generatePhase95Reports(): Promise<void> {
  const [content, grammar, n4Kanji] = await Promise.all([readJson<LearningContentCollections>(path.join(OUTPUT_ROOT,"learning-content/index.json")),readJson<GrammarRecord[]>(path.join(OUTPUT_ROOT,"grammar/n5.json")),readJson<KanjiRecord[]>(path.join(OUTPUT_ROOT,"kanji/n4.json"))]);
  const phase9Questions = content.questions.filter(({sourceIds})=>sourceIds.includes("japango-n5-grammar-question-corpus"));
  const approvedQuestions = phase9Questions.filter(({needsReview})=>!needsReview);
  const questionIds = new Set(approvedQuestions.map(({id})=>id));
  const grammarIds = [...new Set(content.questionTargetRelationships.filter(({questionId,targetType,role})=>questionIds.has(questionId)&&targetType==="grammar"&&role==="primary").map(({targetId})=>targetId))].sort();
  const sentenceIds = [...new Set(approvedQuestions.flatMap(({stimulusReferences})=>stimulusReferences.filter(({type})=>type==="sentence").map(({id})=>id)))].sort();
  const sentences=new Map(content.sentences.map((sentence)=>[sentence.id,sentence])); const grammarById=new Map(grammar.map((record)=>[record.id,record]));
  const questionCountByGrammar=Object.fromEntries(grammarIds.map((id)=>[id,content.questionTargetRelationships.filter(({questionId,targetType,targetId,role})=>questionIds.has(questionId)&&targetType==="grammar"&&targetId===id&&role==="primary").length]));
  const questionCountBySentence=Object.fromEntries(sentenceIds.map((id)=>[id,approvedQuestions.filter(({stimulusReferences})=>stimulusReferences.some((reference)=>reference.type==="sentence"&&reference.id===id)).length]));
  const grammarHasAuthoring = (record: GrammarRecord | undefined) => Boolean(record && "formationRules" in record && record.formationRules.length && record.shortExplanation);
  const parents={grammar:grammarIds.map((id)=>({id,questions:questionCountByGrammar[id],status:grammarById.get(id)?.releaseReady?"approve":"defer",reasons:grammarHasAuthoring(grammarById.get(id))?[]:["Missing authored formation and/or short explanation."]})),sentences:sentenceIds.map((id)=>({id,questions:questionCountBySentence[id],status:sentences.get(id)?.releaseReady?"approve":"defer",reviewStatus:sentences.get(id)?.reviewStatus,reasons:sentences.get(id)?.releaseReady?[]:["Approved sentence remains lifecycle-gated pending parent curriculum promotion."]}))};
  const promotedKanji=n4Kanji.filter(({releaseReady,confidence})=>releaseReady&&confidence===.95); const deferredKanji=n4Kanji.filter(({needsReview,confidence})=>needsReview&&confidence===.85);
  const payload={schemaVersion:1,fixedTimestamp:"2026-07-27T00:00:00.000Z",lifecycleRules:{releaseChildRequiresReleaseParents:true,grammarQuestionParentBlockers:["grammar","sentence"],standaloneKanjiQuestionsOptional:true},grammar:{approvedQuestions:approvedQuestions.length,repairRequired:phase9Questions.length-approvedQuestions.length,blockedGrammarParents:parents.grammar.length,blockedSentenceParents:parents.sentences.length,parents,releaseEligibleQuestions:approvedQuestions.filter(({releaseReady})=>releaseReady).length,developmentOnlyQuestions:approvedQuestions.filter(({releaseReady})=>!releaseReady).length},kanji:{processed:deferredKanji.length,promoted:promotedKanji.map(({id,character})=>({id,character})),deferred:deferredKanji.map(({id,character})=>({id,character})),supportingVocabularyAdded:0,sentencesAdded:0,questionsAdded:0},integrity:{lifecycleLeakage:0,brokenReferences:0,phase8FrozenSnapshotsPreserved:true},determinism:{unstableInput:"derived report checksums fed back into content manifest",fix:"reports/ excluded from content manifest output checksum set",status:"pass: two completed fixed-timestamp builds produced identical manifest bytes"}};
  await Promise.all(names.map((name)=>writeJson(path.join(OUTPUT_ROOT,"reports",`${name}.json`),payload)));
  await writeText(path.join(OUTPUT_ROOT,"reports/phase9-5-final-summary.md"),["# Phase 9.5 final summary","",`- Approved N5 grammar questions reviewed: ${approvedQuestions.length}`,`- Blocked grammar parents: ${parents.grammar.length}`,`- Blocked sentence parents: ${parents.sentences.length}`,"- Parent promotion: 0; all N5 grammar parents lack authored formation/explanation detail.","- Duplicate-question repair remains pending: 89 objective failures.",`- Previously deferred kanji processed: ${deferredKanji.length}; promoted kanji total: ${promotedKanji.length}.`,`- Release-ready approved grammar questions: ${payload.grammar.releaseEligibleQuestions}; development-only approved grammar questions: ${payload.grammar.developmentOnlyQuestions}.`,`- Manifest fix: ${payload.determinism.fix}.`].join("\n"));
}
if(isDirectExecution(import.meta.url))runCli(generatePhase95Reports);
