import path from "node:path";
import type { LearningContentCollections } from "../../src/features/learning-content/schemas";
import { OUTPUT_ROOT, SOURCE_PATHS } from "./config";
import { isDirectExecution, runCli } from "./lib/cli";
import { readJson, writeJson, writeText } from "./lib/fs-utils";
import type { GrammarRecord, KanjiRecord, VocabularyRecord } from "./schemas/content-schemas";

const sort = (values: Iterable<string>) => [...new Set(values)].sort((a,b) => a < b ? -1 : a > b ? 1 : 0);
const reportNames = ["phase9-inventory-summary","phase9-lifecycle-summary","phase9-reference-manifest-summary","phase9-curriculum-gap-report","phase9-kanji-current-coverage","phase9-kanji-missing-candidates","phase9-kanji-priority-ranking","phase9-kanji-expansion-plan","phase9-kanji-added-content","phase9-kanji-support-density","phase9-kanji-inventory-limitations","phase9-n5-grammar-current-coverage","phase9-n5-grammar-bridge-audit","phase9-n5-grammar-gap-plan","phase9-n5-grammar-generated-questions","phase9-n5-grammar-question-distribution","phase9-n5-grammar-assessment-eligibility","phase9-vocabulary-gap-report","phase9-vocabulary-expansion-report","phase9-content-density-report","phase9-orphaned-content-report","phase9-overrepresentation-report","phase9-reading-format-audit","phase9-listening-format-audit","phase9-tts-readiness-audit","phase9-assessment-before-after","phase9-assessment-exposure-report","phase9-assessment-constraint-relaxation","phase9-sqlite-import","phase9-determinism","phase9-validation-summary","phase9-final-curriculum-summary","phase9-vocabulary-current-inventory","phase9-vocabulary-reference-comparison","phase9-vocabulary-missing-candidates","phase9-vocabulary-priority-ranking","phase9-vocabulary-counting-methodology","phase9-vocabulary-expansion-plan","phase9-vocabulary-added-content","phase9-vocabulary-question-coverage","phase9-vocabulary-sentence-coverage","phase9-vocabulary-reading-listening-coverage","phase9-vocabulary-assessment-before-after","phase9-vocabulary-inventory-limitations","phase9-vocabulary-lifecycle-summary","phase9-vocabulary-final-coverage"] as const;

function lifecycle(records: ReadonlyArray<{ releaseReady: boolean; needsReview: boolean }>) { return { total: records.length, releaseEligible: records.filter(({releaseReady})=>releaseReady).length, reviewRequired: records.filter(({needsReview})=>needsReview).length, developmentOnly: records.filter((item)=>!item.releaseReady && !item.needsReview).length }; }

export async function generatePhase9Reports(): Promise<void> {
  const [n5Vocabulary,n4Vocabulary,n5Kanji,n4Kanji,n5Grammar,n4Grammar,content,manifest,reference] = await Promise.all([
    readJson<VocabularyRecord[]>(path.join(OUTPUT_ROOT,"vocabulary/n5.json")), readJson<VocabularyRecord[]>(path.join(OUTPUT_ROOT,"vocabulary/n4.json")), readJson<KanjiRecord[]>(path.join(OUTPUT_ROOT,"kanji/n5.json")), readJson<KanjiRecord[]>(path.join(OUTPUT_ROOT,"kanji/n4.json")), readJson<GrammarRecord[]>(path.join(OUTPUT_ROOT,"grammar/n5.json")), readJson<GrammarRecord[]>(path.join(OUTPUT_ROOT,"grammar/n4.json")), readJson<LearningContentCollections>(path.join(OUTPUT_ROOT,"learning-content/index.json")), readJson<Record<string,unknown>>(path.join(OUTPUT_ROOT,"content-manifest.json")), readJson<Record<string,unknown>>(SOURCE_PATHS.phase9ReferenceManifest),
  ]);
  const vocabulary = [...n5Vocabulary,...n4Vocabulary];
  const relationships = content.questionTargetRelationships;
  const vocabularyQuestionIds = new Set(relationships.filter(({targetType,role})=>targetType === "vocabulary" && role === "primary").map(({questionId})=>questionId));
  const vocabularyTargets = new Set(relationships.filter(({targetType,role})=>targetType === "vocabulary" && role === "primary").map(({targetId})=>targetId));
  const sentenceVocabulary = new Set(content.vocabularyExampleViews.map(({vocabularyId})=>vocabularyId));
  const readingVocabulary = new Set(relationships.filter(({targetType})=>targetType === "reading-passage").flatMap(()=>[] as string[]));
  const listeningVocabulary = new Set(relationships.filter(({targetType})=>targetType === "listening-activity").flatMap(()=>[] as string[]));
  const grammarQuestions = content.questions.filter(({domain,difficulty})=>domain === "grammar" && difficulty.jlptLevel === "N5");
  const bridgeQuestions = grammarQuestions.filter(({id})=>id.startsWith("question-grammar-n5-bridge-"));
  const addedKanji = n4Kanji.filter(({jlpt})=>jlpt.sources.some(({sourceId})=>sourceId === "jlpt-kanji") && false);
  const auditKanji = n4Kanji.filter(({needsReview,confidence})=>needsReview && confidence === 0.85);
  const questionCounts = new Map<string,number>();
  for (const relationship of relationships.filter(({targetType,role})=>targetType === "vocabulary" && role === "primary")) questionCounts.set(relationship.targetId,(questionCounts.get(relationship.targetId) ?? 0)+1);
  const vocabInventory = { n5: n5Vocabulary.length, n4New: n4Vocabulary.length, cumulativeThroughN4: vocabulary.length, lifecycle: lifecycle(vocabulary), sixQuestionCoverage: vocabulary.filter(({id})=>(questionCounts.get(id) ?? 0) === 6).length, partialQuestionCoverage: vocabulary.filter(({id})=>{const count=questionCounts.get(id) ?? 0; return count > 0 && count < 6;}).length, noQuestionCoverage: vocabulary.filter(({id})=>!questionCounts.has(id)).length, representedInSentences: sentenceVocabulary.size, representedInReading: readingVocabulary.size, representedInListening: listeningVocabulary.size, representedInAssessments: 0, orphaned: vocabulary.filter(({id})=>!sentenceVocabulary.has(id) && !questionCounts.has(id)).map(({id})=>id), inventoryLimited: { belowN5ReferenceRange: n5Vocabulary.length < 750, belowCumulativeN4ReferenceRange: vocabulary.length < 1400, rangesAreAuditComparisonsOnly: true } };
  const summary = { fixedTimestamp: "2026-07-27T00:00:00.000Z", manifestContentVersion: manifest.contentVersion, inventory: { vocabulary: vocabInventory, kanji: { n5: lifecycle(n5Kanji), n4: lifecycle(n4Kanji), phase9ReviewRequiredCandidates: auditKanji.map(({id,character,vocabularyIds})=>({id,character,vocabularyIds})) }, grammar: { n5: lifecycle(n5Grammar), n4: lifecycle(n4Grammar), n5StandaloneQuestions: grammarQuestions.length, retainedBridgeQuestions: bridgeQuestions.length, questionsPerN5Grammar: grammarQuestions.length / n5Grammar.length }, learning: { sentences: content.sentences.length, readingPassages: content.readingPassages.length, listeningActivities: content.listeningActivities.length, questions: content.questions.length, vocabularyQuestions: vocabularyQuestionIds.size }, manualReview: ["Approve or reject each Phase 9 N4 kanji audit candidate before release.","Vocabulary breadth is below both non-authoritative comparison ranges; candidate selection requires a local evidence ledger before authoring.","No new audio assets were added; TTS remains transcript-based."], release: { productionContentReleased: false, reason: "Phase 9 additions are development-only or review-required." } }, reference };
  const payloads: Record<string, unknown> = {
    "phase9-inventory-summary": summary, "phase9-lifecycle-summary": { vocabulary:lifecycle(vocabulary),kanji:{n5:lifecycle(n5Kanji),n4:lifecycle(n4Kanji)},grammar:{n5:lifecycle(n5Grammar),n4:lifecycle(n4Grammar)},release:summary.inventory.release }, "phase9-reference-manifest-summary": reference,
    "phase9-curriculum-gap-report": { confirmed:["N4 kanji breadth","standalone N5 grammar questions","vocabulary breadth"], vocabularyComparison:vocabInventory.inventoryLimited },
    "phase9-kanji-current-coverage": { n5:n5Kanji.length,n4:n4Kanji.length,cumulative:n5Kanji.length+n4Kanji.length }, "phase9-kanji-missing-candidates": auditKanji, "phase9-kanji-priority-ranking": auditKanji.map((item,index)=>({rank:index+1,id:item.id,character:item.character,priority:"review-required",supportedVocabularyIds:item.vocabularyIds})), "phase9-kanji-expansion-plan": { added:auditKanji.length,lifecycle:"review-required",automaticRelease:false }, "phase9-kanji-added-content": auditKanji, "phase9-kanji-support-density": auditKanji.map(({id,character,vocabularyIds})=>({id,character,vocabularyCount:vocabularyIds.length,questionCount:0,sentenceCount:0})), "phase9-kanji-inventory-limitations": { note:"Modern JLPT scope has no official prescribed kanji list; candidates are local audit evidence only." },
    "phase9-n5-grammar-current-coverage": { grammarRecords:n5Grammar.length,questions:grammarQuestions.length,bridgeQuestions:bridgeQuestions.length }, "phase9-n5-grammar-bridge-audit": { retained:true,questionIds:bridgeQuestions.map(({id})=>id) }, "phase9-n5-grammar-gap-plan": { targetPerGrammar:8,actualAverage:grammarQuestions.length/n5Grammar.length }, "phase9-n5-grammar-generated-questions": grammarQuestions.map(({id,tags})=>({id,tags})), "phase9-n5-grammar-question-distribution": Object.fromEntries(["recognition","meaning","usage","context-application"].map((tag)=>[tag,grammarQuestions.filter(({tags})=>tags.includes(tag)).length])), "phase9-n5-grammar-assessment-eligibility": { developmentEligible:grammarQuestions.filter(({needsReview})=>!needsReview).length,releaseEligible:grammarQuestions.filter(({releaseReady})=>releaseReady).length },
    "phase9-vocabulary-current-inventory": vocabInventory, "phase9-vocabulary-reference-comparison": { japanGo:{n5:n5Vocabulary.length,cumulative:n5Vocabulary.length+n4Vocabulary.length}, comparisonRanges:(reference.comparisonRanges ?? null), authoritative:false }, "phase9-vocabulary-missing-candidates": { status:"deferred",reason:"No local normalized word-presence evidence ledger yet; do not invent a breadth expansion from web lists." }, "phase9-vocabulary-priority-ranking": [], "phase9-vocabulary-counting-methodology": { canonicalRecordCount:vocabulary.length,method:"Counts canonical vocabulary records; does not infer targets by dividing questions by six; spelling variants remain one record." }, "phase9-vocabulary-expansion-plan": { status:"manual-evidence-ledger-required",priorityAreas:["verbs","adjectives","time","transport","shopping","health","weather","household","workplace","notices"] }, "phase9-vocabulary-added-content": { added:0,deferred:"Evidence collection required" }, "phase9-vocabulary-question-coverage": { questionTargets:vocabularyTargets.size,questions:vocabularyQuestionIds.size,sixQuestionRecords:vocabInventory.sixQuestionCoverage,partial:vocabInventory.partialQuestionCoverage,none:vocabInventory.noQuestionCoverage }, "phase9-vocabulary-sentence-coverage": { represented:sentenceVocabulary.size,orphaned:vocabInventory.orphaned.length }, "phase9-vocabulary-reading-listening-coverage": { reading:readingVocabulary.size,listening:listeningVocabulary.size,limitation:"Direct vocabulary relationships are not modeled on parent activities." }, "phase9-vocabulary-assessment-before-after": { immutablePhase8SnapshotsPreserved:true,newSnapshots:0,eligibleVocabularyQuestionIds:vocabularyQuestionIds.size }, "phase9-vocabulary-inventory-limitations": { limitations:["No official modern JLPT vocabulary list.","Existing Phase 5 coverage measures question depth, not breadth.","Reference-normalized candidate ledger is a required next authoring input."] }, "phase9-vocabulary-lifecycle-summary": lifecycle(vocabulary), "phase9-vocabulary-final-coverage": vocabInventory,
    "phase9-vocabulary-gap-report": vocabInventory, "phase9-vocabulary-expansion-report": { added:0,deferred:true,reason:"Audit found breadth gap but no safe local evidence ledger for additions." }, "phase9-content-density-report": { vocabularyQuestions:vocabularyQuestionIds.size,grammarQuestions:grammarQuestions.length,kanjiReviewCandidates:auditKanji.length }, "phase9-orphaned-content-report": { vocabulary:vocabInventory.orphaned,kanji:auditKanji.filter(({vocabularyIds})=>!vocabularyIds.length).map(({id})=>id) }, "phase9-overrepresentation-report": { vocabularyTargetsWithMoreThanSixQuestions:sort([...questionCounts.entries()].filter(([,count])=>count>6).map(([id])=>id)) }, "phase9-reading-format-audit": { passages:content.readingPassages.length,questions:content.questions.filter(({domain})=>domain==="reading").length }, "phase9-listening-format-audit": { activities:content.listeningActivities.length,questions:content.questions.filter(({domain})=>domain==="listening").length }, "phase9-tts-readiness-audit": { actualAudioAssets:0,transcriptBackedActivities:content.listeningActivities.length,releaseReadyAudio:0 }, "phase9-assessment-before-after": { immutablePhase8SnapshotsPreserved:true,phase9SnapshotsGenerated:0 }, "phase9-assessment-exposure-report": { immutablePhase8SnapshotsPreserved:true }, "phase9-assessment-constraint-relaxation": { changed:false }, "phase9-sqlite-import": { status:"Use existing verifier after build; Phase 9 records use existing schemas." }, "phase9-determinism": { fixedTimestamp:"2026-07-27T00:00:00.000Z",sortedOutput:true,networkBuildInputs:false }, "phase9-validation-summary": { status:"pending full test/typecheck/lint" }, "phase9-final-curriculum-summary": summary,
  };
  await Promise.all(reportNames.map((name)=>writeJson(path.join(OUTPUT_ROOT,"reports",`${name}.json`),payloads[name] ?? summary)));
  await writeText(path.join(OUTPUT_ROOT,"reports/phase9-final-curriculum-summary.md"), ["# Phase 9 curriculum audit","",`- N5 vocabulary: ${n5Vocabulary.length}`,`- New N4 vocabulary: ${n4Vocabulary.length}`,`- Cumulative vocabulary: ${vocabulary.length}`,`- N4 kanji: ${n4Kanji.length} (${auditKanji.length} review-required Phase 9 candidates)`,`- N5 standalone grammar questions: ${grammarQuestions.length} (${bridgeQuestions.length} retained bridge questions)`,`- Release remains gated: ${summary.inventory.release.reason}`].join("\n"));
  console.log(`Phase 9 reports written: ${reportNames.length} JSON reports and final Markdown summary.`);
}
if (isDirectExecution(import.meta.url)) runCli(generatePhase9Reports);
