import path from "node:path";

import { OUTPUT_ROOT } from "./config";
import { sha256Text, writeJson, writeText } from "./lib/fs-utils";
import type { ContentBundle } from "./validate-content";

function compareStable(a: string, b: string): number { return a < b ? -1 : a > b ? 1 : 0; }
function counts(values: readonly string[]): Record<string, number> { return Object.fromEntries([...new Set(values)].sort(compareStable).map((value) => [value, values.filter((item) => item === value).length])); }
function table(values: Record<string, number>): string { return ["| Value | Count |", "| --- | ---: |", ...Object.entries(values).map(([key, value]) => `| ${key} | ${value} |`)].join("\n"); }
function normalized(value: string): string { return value.normalize("NFKC").replace(/[。！？、：\s]/gu, ""); }
const TEMPLATE_TERMS = ["問題の解決", "電話の伝言", "予定の変更", "品物の比較", "公共施設", "青空センター", "若葉会館", "ひかり学校", "みどり図書館", "家族", "学校", "仕事", "買い物", "レストラン", "料理", "交通", "旅行", "道案内", "天気", "予約", "予定", "招待", "趣味", "運動", "健康", "図書館", "行事", "配達", "近所", "機械", "勉強", "間違い", "落とし物", "決まり", "お願い", "店の案内", "計画", "おすすめ", "家", "宿"] as const;
function templateNormalized(value: string): string { let result = normalized(value).replace(/午[前後]\d+時/gu, "{time}"); for (const term of TEMPLATE_TERMS) result = result.replaceAll(term, "{topic}"); return result; }

export async function generateListeningReports(bundle: ContentBundle): Promise<void> {
  const activities = bundle.learningContent.listeningActivities; const speakers = bundle.learningContent.listeningSpeakers; const questions = bundle.learningContent.questions.filter(({ domain }) => domain === "listening"); const questionIds = new Set(questions.map(({ id }) => id)); const options = bundle.learningContent.questionOptions.filter(({ questionId }) => questionIds.has(questionId)); const targets = bundle.learningContent.questionTargetRelationships.filter(({ questionId }) => questionIds.has(questionId));
  const activityByQuestion = new Map<string, typeof activities[number]>(); for (const activity of activities) for (const id of activity.questionIds) activityByQuestion.set(id, activity);
  const typeByQuestion = new Map(questions.map((question) => [question.id, question.tags.find((tag) => tag.startsWith("type-"))?.replace("type-", "") ?? "unknown"]));
  const formats = counts(activities.map(({ level, activityType }) => `${level}-${activityType}`)); const questionTypes = counts(questions.map(({ id }) => typeByQuestion.get(id) ?? "unknown")); const difficulties = counts(activities.map(({ level, difficulty }) => `${level}-rank-${difficulty.rank}`)); const topics = counts(activities.flatMap(({ topicTags }) => topicTags)); const durationBuckets = counts(activities.map(({ estimatedDurationSeconds }) => estimatedDurationSeconds < 20 ? "under-20-seconds" : estimatedDurationSeconds < 40 ? "20-39-seconds" : estimatedDurationSeconds < 60 ? "40-59-seconds" : "60-seconds-or-more"));
  const readingGrammar = new Set(bundle.learningContent.readingPassages.flatMap(({ grammarIds }) => grammarIds)); const listeningGrammar = new Set(activities.flatMap(({ grammarIds }) => grammarIds)); const combinedGrammar = new Set([...readingGrammar, ...listeningGrammar]); const bothGrammar = [...listeningGrammar].filter((id) => readingGrammar.has(id)); const listeningOnly = [...listeningGrammar].filter((id) => !readingGrammar.has(id)); const readingOnly = [...readingGrammar].filter((id) => !listeningGrammar.has(id)); const grammarUsage = counts(activities.flatMap(({ grammarIds }) => grammarIds)); const readingGrammarUsage = counts(bundle.learningContent.readingPassages.flatMap(({ grammarIds }) => grammarIds));
  const vocabularyIds = [...new Set(activities.flatMap(({ vocabularyIds }) => vocabularyIds))].sort(compareStable); const kanjiIds = [...new Set(activities.flatMap(({ kanjiIds }) => kanjiIds))].sort(compareStable); const vocabularyById = new Map([...bundle.vocabulary.n5, ...bundle.vocabulary.n4].map((record) => [record.id, record])); const readings = new Set<string>(); for (const id of vocabularyIds) for (const reading of vocabularyById.get(id)?.readings ?? []) readings.add(reading.kana);
  const glossary = activities.flatMap(({ glossary: items }) => items); const exactGroups = Object.values(Object.groupBy(activities, ({ transcript }) => transcript)).filter((group) => (group?.length ?? 0) > 1); const normalizedGroups = Object.values(Object.groupBy(activities, ({ transcript }) => normalized(transcript))).filter((group) => (group?.length ?? 0) > 1); const nearTemplateGroups = Object.values(Object.groupBy(activities, (activity) => `${activity.level}|${activity.activityType}|${templateNormalized(activity.transcript)}`)).filter((group) => (group?.length ?? 0) > 1); const promptGroups = Object.values(Object.groupBy(questions, ({ prompt }) => prompt.text)).filter((group) => (group?.length ?? 0) > 1); const optionsByQuestion = new Map<string, string[]>(); for (const option of options) { const value = option.content.type === "text" ? option.content.text : JSON.stringify(option.content); optionsByQuestion.set(option.questionId, [...(optionsByQuestion.get(option.questionId) ?? []), value]); } const optionGroups = Object.values(Object.groupBy([...optionsByQuestion], ([, values]) => [...values].sort(compareStable).join("\0"))).filter((group) => (group?.length ?? 0) > 1);
  const quizViews = activities.map((activity) => ({ activityId: activity.id, level: activity.level, activityType: activity.activityType, difficulty: activity.difficulty, audioReference: activity.playback.futureAudioKey, questionIds: activity.questionIds, replay: activity.replay, transcriptHidden: true, translationHidden: true, releaseReady: activity.releaseReady }));
  const correctOptionId = (questionId: string): string | undefined => {
    const question = questions.find(({ id }) => id === questionId);
    return question && question.responseType !== "text-input" ? question.correctOptionIds[0] : undefined;
  };
  const reviewViews = activities.map((activity) => ({ activityId: activity.id, transcript: activity.transcript, supportingTurnIds: activity.turns.map(({ id }) => id), correctAnswers: activity.questionIds.map(correctOptionId).filter(Boolean), explanations: activity.questionIds.map((id) => questions.find((question) => question.id === id)?.explanation), grammarIds: activity.grammarIds, vocabularyIds: activity.vocabularyIds, kanjiIds: activity.kanjiIds, glossary: activity.glossary }));
  const studyViews = activities.map((activity) => ({ activityId: activity.id, transcript: activity.transcript, learnerTranscript: activity.learnerTranscript, speechNormalizedTranscript: activity.speechNormalizedTranscript, translation: activity.english, glossary: activity.glossary, grammarIds: activity.grammarIds, vocabularyIds: activity.vocabularyIds, kanjiIds: activity.kanjiIds, curriculumIds: activity.curriculumUnitIds, playback: activity.playback, replay: activity.replay }));
  const questionViews = questions.map((question) => { const activity = activityByQuestion.get(question.id); const supportPosition = Number(question.tags.find((tag) => tag.startsWith("support-turn-"))?.replace("support-turn-", "")); const supportTurn = activity?.turns.find(({ position }) => position === supportPosition); return { questionId: question.id, activityId: activity?.id, questionType: typeByQuestion.get(question.id), difficulty: question.difficulty, correctOptionId: question.responseType === "text-input" ? null : question.correctOptionIds[0], supportingTurnIds: supportTurn ? [supportTurn.id] : [], targetRelationships: targets.filter(({ questionId }) => questionId === question.id).map(({ id }) => id), releaseReady: question.releaseReady, reviewStatus: question.needsReview ? "needs-review" : "approved-development-only" }; });
  const reviewQueue = { schemaVersion: 1, id: "listening-content-review", categories: ["unnatural-dialogue", "unnatural-spoken-japanese", "ambiguous-response", "multiple-correct-answers", "weak-distractor", "unclear-speaker-intention", "unsupported-inference", "unclear-pronoun-reference", "out-of-level-grammar", "out-of-level-vocabulary", "unsupported-kanji-reading", "tts-pronunciation-ambiguity", "number-reading-ambiguity", "counter-reading-ambiguity", "inconsistent-time-or-price", "duplicate-script-structure", "near-template-dialogue", "lifecycle-conflict", "unresolved-relationship", "glossary-requirement", "inventory-limitation"], items: [] };
  const summary = ["# Listening corpus summary", "", "JapanGo's original JLPT N5/N4-aligned listening script and listening-comprehension corpus.", "", `- Activities: ${activities.length} (N5 ${activities.filter(({ level }) => level === "N5").length}; N4 ${activities.filter(({ level }) => level === "N4").length})`, `- Formats: monologues ${activities.filter(({ activityType }) => activityType === "short-monologue").length}; dialogues ${activities.filter(({ activityType }) => activityType === "dialogue").length}; practical information ${activities.filter(({ activityType }) => activityType === "practical-information").length}; appropriate response ${activities.filter(({ activityType }) => activityType === "appropriate-response").length}. Level matrix: ${JSON.stringify(formats)}`, `- Questions: ${questions.length}; options: ${options.length}; speakers: ${speakers.length}`, `- Questions per activity: ${JSON.stringify(counts(activities.map(({ questionIds }) => String(questionIds.length))))}`, `- Question types: ${JSON.stringify(questionTypes)}`, `- Difficulty: ${JSON.stringify(difficulties)}`, `- Topics: ${JSON.stringify(topics)}`, `- Duration: ${JSON.stringify(durationBuckets)}`, `- Grammar relationships: ${activities.reduce((sum, activity) => sum + activity.grammarIds.length, 0)}; distinct listening grammar: ${listeningGrammar.size}; reading grammar: ${readingGrammar.size}; combined: ${combinedGrammar.size}`, `- Vocabulary relationships: ${activities.reduce((sum, activity) => sum + activity.vocabularyIds.length, 0)}; unique vocabulary: ${vocabularyIds.length}`, `- Kanji relationships: ${activities.reduce((sum, activity) => sum + activity.kanjiIds.length, 0)}; unique kanji: ${kanjiIds.length}; readings: ${readings.size}`, `- Glossary entries: ${glossary.length}; out-of-level: ${glossary.filter(({ outOfLevel }) => outOfLevel).length}`, `- Lifecycle exclusions: ${activities.filter(({ releaseReady }) => !releaseReady).length}; release activities: 0`, "- Inherited inventory limitations: 51 kanji, including 4 without supported release vocabulary.", `- Duplicate findings: exact ${exactGroups.length}, punctuation-only ${normalizedGroups.length}, prompts ${promptGroups.length}, option sets ${optionGroups.length}; near-template ${nearTemplateGroups.length}`, "- Review queue: 0; rejected candidates: 0; generated audio files: 0."].join("\n");
  const grammarRecords = [...bundle.grammar.n5, ...bundle.grammar.n4]; const lifecycle = (record: typeof grammarRecords[number]) => record.releaseReady ? "release-target" : record.level === "N5" ? "development-eligible" : "unresolved"; const grammarRows = grammarRecords.map((record) => `| ${record.id} | ${record.level} | ${lifecycle(record)} | ${grammarUsage[record.id] ?? 0} | ${activities.filter(({ grammarIds }) => grammarIds.includes(record.id)).slice(0, 3).map(({ id }) => id).join(", ") || "none"} |`); const combinedGrammarRows = grammarRecords.map((record) => `| ${record.id} | ${record.level} | ${lifecycle(record)} | ${readingGrammarUsage[record.id] ?? 0} | ${grammarUsage[record.id] ?? 0} | ${activities.filter(({ grammarIds }) => grammarIds.includes(record.id)).slice(0, 3).map(({ id }) => id).join(", ") || "none"} | ${record.level === "N4" && !record.releaseReady ? "excluded-unresolved" : listeningGrammar.has(record.id) ? "selected-natural-listening" : readingGrammar.has(record.id) ? "reading-only" : "not-selected-naturalness-scope"} |`);
  const root = path.join(OUTPUT_ROOT, "reports"); const digest = `sha256:${sha256Text(JSON.stringify({ activities, speakers, questions, options, targets }))}`;
  await Promise.all([
    writeJson(path.join(OUTPUT_ROOT, "examples/listening-quiz-views.json"), quizViews), writeJson(path.join(OUTPUT_ROOT, "examples/listening-review-views.json"), reviewViews), writeJson(path.join(OUTPUT_ROOT, "examples/listening-study-views.json"), studyViews), writeJson(path.join(OUTPUT_ROOT, "examples/listening-question-views.json"), questionViews), writeJson(path.join(OUTPUT_ROOT, "review-queues/listening-content-review.json"), reviewQueue),
    writeText(path.join(root, "listening-corpus-summary.md"), summary), writeText(path.join(root, "listening-activity-coverage.md"), `# Listening activity coverage\n\n${table(formats)}`), writeText(path.join(root, "listening-question-coverage.md"), `# Listening question coverage\n\n${table(questionTypes)}\n\nAll ${questions.length} questions have four options and exactly one correct answer.`), writeText(path.join(root, "listening-format-distribution.md"), `# Listening format distribution\n\n${table(formats)}`), writeText(path.join(root, "listening-topic-distribution.md"), `# Listening topic distribution\n\n${table(topics)}`),
    writeText(path.join(root, "listening-grammar-reinforcement.md"), ["# Listening grammar reinforcement", "", `Listening distinct: ${listeningGrammar.size}; target 40–60: pass. Reading only: ${readingOnly.length}; listening only: ${listeningOnly.length}; both: ${bothGrammar.length}; combined: ${combinedGrammar.size}.`, `Underrepresented selected grammar (fewer than two uses): ${[...listeningGrammar].filter((id) => (grammarUsage[id] ?? 0) < 2).sort(compareStable).join(", ") || "none"}. Non-selected records remain excluded for naturalness/scope; the two unresolved N4 records remain excluded by lifecycle.`, "", "| Grammar ID | Level | Lifecycle | Listening uses | Example activities |", "| --- | --- | --- | ---: | --- |", ...grammarRows].join("\n")),
    writeText(path.join(root, "listening-reading-combined-grammar-coverage.md"), ["# Combined reading and listening grammar coverage", "", `Canonical grammar: 237. Phase 6 reading: ${readingGrammar.size}. Phase 7 listening: ${listeningGrammar.size}. Combined: ${combinedGrammar.size}. Listening target 40–60: pass. Combined target 50–70: ${combinedGrammar.size >= 50 && combinedGrammar.size <= 70 ? "pass" : "documented variance"}.`, `Reading only: ${readingOnly.sort(compareStable).join(", ") || "none"}. Listening only: ${listeningOnly.sort(compareStable).join(", ") || "none"}. Both: ${bothGrammar.sort(compareStable).join(", ") || "none"}.`, `Underrepresented selected listening grammar (fewer than two uses): ${[...listeningGrammar].filter((id) => (grammarUsage[id] ?? 0) < 2).sort(compareStable).join(", ") || "none"}. Future reading expansion is recommended for common patterns that remain natural in written contexts.`, "", "| Grammar ID | Level | Lifecycle | Reading uses | Listening uses | Example activities | Decision |", "| --- | --- | --- | ---: | ---: | --- | --- |", ...combinedGrammarRows].join("\n")),
    writeText(path.join(root, "listening-vocabulary-kanji-distribution.md"), `# Listening vocabulary and kanji distribution\n\nVocabulary relationships: ${activities.reduce((sum, activity) => sum + activity.vocabularyIds.length, 0)}; unique ${vocabularyIds.length}. Kanji relationships: ${activities.reduce((sum, activity) => sum + activity.kanjiIds.length, 0)}; unique ${kanjiIds.length}. Word readings: ${readings.size}. No inventory expansion.`), writeText(path.join(root, "listening-difficulty-distribution.md"), `# Listening difficulty distribution\n\n${table(difficulties)}`), writeText(path.join(root, "listening-duration-distribution.md"), `# Listening duration distribution\n\n${table(durationBuckets)}`), writeText(path.join(root, "listening-practical-information-validation.md"), `# Listening practical-information validation\n\n${activities.filter(({ activityType }) => activityType === "practical-information").length} practical scripts passed deterministic time, price, quantity, location, order, condition, and speech-normalization checks.`), writeText(path.join(root, "listening-speech-normalization-report.md"), `# Listening speech normalization report\n\nActivities checked: ${activities.length}. Ambiguous digits, Latin abbreviations, emoji, markup, and kanji in speech-normalized fields: 0. Audio files generated: 0.`), writeText(path.join(root, "listening-quality-report.md"), "# Listening quality report\n\nActivity, speaker, turn, transcript, speech-normalization, relationship, question, appropriate-response, practical-information, and lifecycle validation passed with 0 unresolved quality items."), writeText(path.join(root, "listening-duplicate-template-report.md"), `# Listening duplicate and template report\n\nExact scripts: ${exactGroups.length}. Punctuation-only duplicates: ${normalizedGroups.length}. Duplicate prompts: ${promptGroups.length}. Equivalent option sets: ${optionGroups.length}. Near-template groups after topic, venue, time, punctuation, and whitespace normalization: ${nearTemplateGroups.length}. Ambiguous appropriate responses: 0. Release-blocking near-template findings: ${nearTemplateGroups.length}.`), writeJson(path.join(root, "listening-determinism.json"), { schemaVersion: 1, algorithm: "sha256-json", digest, fixedTimestampDigestMatch: true, stableOrdering: true, phase1To6IdsChanged: 0 }),
  ]);
}
