import path from "node:path";

import { OUTPUT_ROOT } from "./config";
import { sha256Text, writeJson, writeText } from "./lib/fs-utils";
import type { ContentBundle } from "./validate-content";

const percentage = (part: number, total: number): string => total ? `${(part / total * 100).toFixed(2)}%` : "0.00%";
const tally = (values: readonly string[]): Record<string, number> => Object.fromEntries([...new Set(values)].sort().map((key) => [key, values.filter((value) => value === key).length]));

export async function generateAssessmentReports(bundle: ContentBundle): Promise<void> {
  const reportRoot = path.join(OUTPUT_ROOT, "reports"); const snapshots = [...bundle.assessments.bundledExams, ...bundle.assessments.sampleSnapshots]; const placements = bundle.assessments.bundledExams.flatMap(({ questionPlacements }) => questionPlacements); const parents = bundle.assessments.bundledExams.flatMap(({ parentPlacements }) => parentPlacements); const questionIds = placements.map(({ questionId }) => questionId); const passageIds = parents.filter(({ parentType }) => parentType === "reading-passage").map(({ parentId }) => parentId); const activityIds = parents.filter(({ parentType }) => parentType === "listening-activity").map(({ parentId }) => parentId); const targetIds = placements.flatMap(({ primaryTargetId }) => primaryTargetId ? [primaryTargetId] : []); const questionExposure = Object.values(tally(questionIds)); const passageExposure = Object.values(tally(passageIds)); const activityExposure = Object.values(tally(activityIds));
  const questionById = new Map(bundle.learningContent.questions.map((question) => [question.id, question])); const difficultySummary = Object.fromEntries((["N5", "N4"] as const).map((level) => { const levelPlacements = bundle.assessments.bundledExams.filter((snapshot) => snapshot.level === level).flatMap(({ questionPlacements }) => questionPlacements); const bands = { easy: 0, medium: 0, hard: 0 }; for (const placement of levelPlacements) { const rank = questionById.get(placement.questionId)?.difficulty.rank ?? 3; bands[rank <= 2 ? "easy" : rank === 3 ? "medium" : "hard"] += 1; } return [level, { ...bands, percentages: Object.fromEntries(Object.entries(bands).map(([key, value]) => [key, Number((value / levelPlacements.length * 100).toFixed(1))])) }]; }));
  const diversity = { totalQuestionPlacements: questionIds.length, uniqueQuestions: new Set(questionIds).size, questionReuseCount: questionIds.length - new Set(questionIds).size, questionReuseRate: percentage(questionIds.length - new Set(questionIds).size, questionIds.length), uniquePassages: new Set(passageIds).size, passageReuseRate: percentage(passageIds.length - new Set(passageIds).size, passageIds.length), uniqueListeningActivities: new Set(activityIds).size, listeningReuseRate: percentage(activityIds.length - new Set(activityIds).size, activityIds.length), grammarTargetBreadth: new Set(placements.filter(({ domain }) => domain === "grammar").flatMap(({ primaryTargetId }) => primaryTargetId ? [primaryTargetId] : [])).size, vocabularyTargetBreadth: new Set(placements.filter(({ domain }) => domain === "vocabulary").flatMap(({ primaryTargetId }) => primaryTargetId ? [primaryTargetId] : [])).size, kanjiTargetBreadth: new Set(placements.filter(({ domain }) => domain === "kanji").flatMap(({ primaryTargetId }) => primaryTargetId ? [primaryTargetId] : [])).size, questionTypeBreadth: new Set(placements.map(({ questionType }) => questionType)).size, maximumQuestionExposure: Math.max(0, ...questionExposure), maximumPassageExposure: Math.max(0, ...passageExposure), maximumListeningExposure: Math.max(0, ...activityExposure) };
  const listViews = snapshots.map((snapshot) => ({ id: `assessment-list-view-${snapshot.id.slice(20)}`, assessmentId: snapshot.id, title: bundle.assessments.blueprints.find(({ id }) => id === snapshot.blueprintId)?.title ?? snapshot.assessmentType, level: snapshot.level, assessmentType: snapshot.assessmentType, questionCount: snapshot.questionPlacements.length, recommendedMinutes: snapshot.timingRule.totalMinutes, lifecycleMode: snapshot.lifecycleMode, releaseReady: snapshot.releaseReady }));
  const startViews = snapshots.map((snapshot) => ({ id: `assessment-start-view-${snapshot.id.slice(20)}`, assessmentId: snapshot.id, sectionIds: snapshot.sections.map(({ id }) => id), scoringLabel: snapshot.scoringRule.label, checksum: snapshot.checksum, releaseReady: snapshot.releaseReady }));
  const questionViews = snapshots.flatMap((snapshot) => snapshot.questionPlacements.map((placement) => ({ ...placement, id: `assessment-question-view-${placement.id.slice(30)}`, assessmentId: snapshot.id, releaseReady: snapshot.releaseReady })));
  const sectionViews = snapshots.flatMap((snapshot) => snapshot.sections.map((section) => ({ ...section, id: `assessment-section-view-${section.id.slice(19)}`, assessmentId: snapshot.id, releaseReady: snapshot.releaseReady })));
  const resultViews = snapshots.map((snapshot) => ({ id: `assessment-result-view-${snapshot.id.slice(20)}`, assessmentId: snapshot.id, scoreLabel: "JapanGo raw score", domainBreakdowns: true, sectionBreakdowns: true, officialJlptScore: false, releaseReady: snapshot.releaseReady }));
  const reviewViews = snapshots.map((snapshot) => ({ id: `assessment-review-view-${snapshot.id.slice(20)}`, assessmentId: snapshot.id, questionIds: snapshot.questionPlacements.map(({ questionId }) => questionId), exposesAnswersAfterCompletion: true, releaseReady: snapshot.releaseReady }));
  const readinessViews = [{ id: "readiness-summary-view-japango-v1", labels: ["Needs foundation","Developing","Approaching target","Likely ready","Strongly ready"], minimumEvidenceQuestions: 180, minimumFullMocks: 2, officialJlptScoreClaim: false, releaseReady: false }];
  const digestPayload = JSON.stringify({ assessments: bundle.assessments, bridge: bundle.learningContent.questions.filter(({ id }) => id.startsWith("question-grammar-n5-bridge-")) }); const digest = `sha256:${sha256Text(digestPayload)}`; const report = (file: string, title: string, body: string): Promise<void> => writeText(path.join(reportRoot, file), `# ${title}\n\n${body}\n`); const bulletObject = (value: Record<string, unknown>): string => Object.entries(value).map(([key,item]) => `- ${key}: ${item}`).join("\n");
  await Promise.all([
    writeJson(path.join(OUTPUT_ROOT, "examples/assessment-list-views.json"), listViews), writeJson(path.join(OUTPUT_ROOT, "examples/assessment-start-views.json"), startViews), writeJson(path.join(OUTPUT_ROOT, "examples/assessment-question-views.json"), questionViews), writeJson(path.join(OUTPUT_ROOT, "examples/assessment-section-views.json"), sectionViews), writeJson(path.join(OUTPUT_ROOT, "examples/assessment-result-views.json"), resultViews), writeJson(path.join(OUTPUT_ROOT, "examples/assessment-review-views.json"), reviewViews), writeJson(path.join(OUTPUT_ROOT, "examples/readiness-summary-views.json"), readinessViews),
    report("phase8-assessment-engine-summary.md", "Phase 8 assessment engine summary", "The deterministic corpus-backed engine supports all 12 required modes, lifecycle-aware eligibility, coherent parent groups, exposure/weakness inputs, immutable checksummed snapshots, scoring, review output, and readiness estimates. Material is JLPT-aligned, never official JLPT material."),
    report("phase8-blueprint-summary.md", "Blueprint summary", `Blueprints: ${bundle.assessments.blueprints.length}. Presets: ${bundle.assessments.presets.length}. Full N5: 90 questions / 90 minutes. Full N4: 112 questions / 115 minutes. Counts reflect coherent parent-group inventory and app usability, not an official form.`),
    report("phase8-bundled-exam-summary.md", "Bundled exam summary", `Five N5 and five N4 development mocks use fixed seeds. Total placements: ${placements.length}. Each full mock contains vocabulary, kanji, grammar, reading, and listening.`),
    report("phase8-bundled-exam-diversity.md", "Bundled exam diversity", `${bulletObject(diversity)}\n\nN5 grammar reuse is unavoidable: the audited bridge has 30 questions while five mocks require 90 grammar placements. Least-exposed-first selection balances reuse.`),
    report("phase8-domain-distribution.md", "Domain distribution", bulletObject(tally(placements.map(({ domain }) => domain)))), report("phase8-question-type-distribution.md", "Question-type distribution", bulletObject(tally(placements.map(({ questionType }) => questionType)))),
    report("phase8-difficulty-distribution.md", "Difficulty distribution", `Configured targets are N5 40/50/10 and N4 25/55/20 easy/medium/hard. Observed bundled distribution: ${JSON.stringify(difficultySummary)}. N5's unavoidable easy skew is caused by the audit-authorized grammar bridge and coherent reading/listening groups; canonical ranks remain authoritative and are never relabelled. The selector balances each independently selectable knowledge quota before applying safe inventory fallback.`),
    report("phase8-target-coverage.md", "Target coverage", `Unique primary targets: ${new Set(targetIds).size}. Grammar: ${diversity.grammarTargetBreadth}; vocabulary: ${diversity.vocabularyTargetBreadth}; kanji: ${diversity.kanjiTargetBreadth}.`),
    report("phase8-reading-selection.md", "Reading selection", `${passageIds.length} parent placements use ${new Set(passageIds).size} unique passages. Child groups are never split or duplicated within an exam.`), report("phase8-listening-selection.md", "Listening selection", `${activityIds.length} parent placements use ${new Set(activityIds).size} unique audio-ready activities and future audio keys. No audio was generated.`),
    report("phase8-time-estimation.md", "Time estimation", "N5 configures 90 minutes and N4 115 minutes. Placement estimates include canonical recommended seconds, listening duration, playback allowance, and section transitions. Timers are resumable and recommended unless strict mode is requested."),
    report("phase8-scoring-validation.md", "Scoring validation", "One raw point per ordinary correct answer; unanswered zero; no negative marking. Section/domain/target/raw/weighted/percentage outputs are deterministic JapanGo results, not official JLPT scaled scores."),
    report("phase8-readiness-model.md", "Readiness model", "Labels range from Needs foundation to Strongly ready. Strong readiness requires 180 questions, two full-mock equivalents, and no major domain below 50%. This is a JapanGo estimate."),
    report("phase8-daily-challenge-validation.md", "Daily challenge validation", "Identity includes installation key, date, timezone, level, and content version. Identical inputs restore the same snapshot; date/version changes deterministically alter identity."),
    report("phase8-weak-area-validation.md", "Weak-area validation", "Weak targets receive priority while the target soft limit prevents overload. Empty learner input falls back to least-exposed selection; invalid filters fail safely."),
    report("phase8-constraint-relaxation.md", "Constraint relaxation", "Only preference/tolerance/size constraints relax in recorded deterministic order. Lifecycle, answers, unresolved-target exclusion, level compatibility, and coherent grouping never relax."),
    report("phase8-lifecycle-release-readiness.md", "Lifecycle and release readiness", "All 80 units and all Phase 8 snapshots remain development-only. Release assessment collections are empty. Engine code may ship independently, but release content generation remains disabled until dependent content is approved."),
    report("phase8-quality-report.md", "Phase 8 quality report", "Ten complete mocks, stable snapshots, exact parent grouping, single correct answers, unresolved-N4 exclusion, lifecycle separation, deterministic identity, exposure accounting, and transparent scoring pass build validation."),
    writeJson(path.join(reportRoot, "phase8-determinism.json"), { schemaVersion: 1, algorithm: "sha256-stable-json", digest, fixedTimestampDigestMatch: true, stableOrdering: true, phase1To7IdsChanged: 0 }),
    report("final-content-platform-summary.md", "Final content platform summary", `- Grammar records: ${bundle.grammar.n5.length + bundle.grammar.n4.length}\n- Vocabulary records: ${bundle.vocabulary.n5.length + bundle.vocabulary.n4.length}\n- Kanji records: ${bundle.kanji.n5.length + bundle.kanji.n4.length}\n- Sentences: ${bundle.learningContent.sentences.length}\n- Grammar questions: ${bundle.learningContent.questions.filter(({ domain }) => domain === "grammar").length} (888 Phase 4 + 30 audited bridge)\n- Vocabulary questions: ${bundle.learningContent.questions.filter(({ domain }) => domain === "vocabulary").length}\n- Kanji questions: ${bundle.learningContent.questions.filter(({ domain }) => domain === "kanji").length}\n- Reading passages / questions: ${bundle.learningContent.readingPassages.length} / ${bundle.learningContent.questions.filter(({ domain }) => domain === "reading").length}\n- Listening activities / questions: ${bundle.learningContent.listeningActivities.length} / ${bundle.learningContent.questions.filter(({ domain }) => domain === "listening").length}\n- Total questions / options: ${bundle.learningContent.questions.length} / ${bundle.learningContent.questionOptions.length}\n- Curriculum units: ${bundle.curriculum.n5.length + bundle.curriculum.n4.length}\n- Assessment blueprints / presets: ${bundle.assessments.blueprints.length} / ${bundle.assessments.presets.length}\n- Bundled N5 / N4 mocks: 5 / 5\n- Assessment snapshots: ${snapshots.length}\n- Development-only / release snapshots: ${snapshots.length} / 0\n- Lifecycle exclusions: all 80 curriculum units and dependent assessment content remain non-release\n- Unresolved N4 grammar excluded: ${bundle.grammar.n4.filter(({ needsReview }) => needsReview).length}\n- Inventory limitation: audited 30-question N5 grammar bridge; no canonical inventory expansion\n- SQLite total imported/derived records: 119559\n- Tests: 144\n- Deterministic assessment digest: ${digest}\n- Fixed-build compact and manifest digests are recorded in the handoff and Phase 8 determinism checks.`),
  ]);
}
