import { useCallback, useEffect, useRef, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams, type Href } from 'expo-router';

import { AppButton } from '@/components/common/app-button';
import { Card } from '@/components/common/card';
import { EmptyState } from '@/components/common/empty-state';
import { LoadingState } from '@/components/common/loading-state';
import { ProgressBar } from '@/components/common/progress-bar';
import { ScreenContainer } from '@/components/common/screen-container';
import { QuestionOption } from '@/components/quiz/question-option';
import { AiTeacherCard } from '@/components/lesson/ai-teacher-card';
import { ThemedText } from '@/components/themed-text';
import { Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { advancePracticeSession, answerPracticeQuestion, getPracticeSession, updatePracticeTimer } from '@/services/database/exam-repository';
import type { PracticeSession } from '@/types/exam';

function lessonRoute(domain: string, itemId: string): Href { return `/${domain}/${encodeURIComponent(itemId)}` as Href; }
function clock(seconds: number): string { return `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`; }

export default function ExamSessionScreen() {
  const theme = useTheme(); const { sessionId } = useLocalSearchParams<{ sessionId?: string }>(); const [session, setSession] = useState<PracticeSession>(); const [elapsed, setElapsed] = useState(0); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [selected, setSelected] = useState<string>(); const [saving, setSaving] = useState(false); const questionStartedAt = useRef<number | undefined>(undefined); const expiring = useRef(false);
  const load = useCallback(async () => { try { const found = sessionId ? await getPracticeSession(sessionId) : undefined; setSession(found); setElapsed(found?.elapsedSeconds ?? 0); questionStartedAt.current = Date.now(); } catch { setFailed(true); } finally { setLoading(false); } }, [sessionId]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const finishForTime = useCallback(async (seconds: number) => { if (!session || expiring.current) return; expiring.current = true; const updated = await advancePracticeSession(session.id, seconds, true); router.replace(`/exams/results?sessionId=${encodeURIComponent(updated.id)}` as Href); }, [session]);
  useEffect(() => { if (!session || session.status !== 'in-progress' || session.selection.timerMode === 'none') return; const timer = setInterval(() => { setElapsed((value) => { const next = value + 1; if (session.selection.timerMode === 'countdown' && session.selection.timeLimitSeconds && next >= session.selection.timeLimitSeconds) void finishForTime(next); return next; }); }, 1000); return () => clearInterval(timer); }, [finishForTime, session]);
  const question = session?.questions[session.currentIndex]; const answer = question ? session?.answers.find((item) => item.questionId === question.id) : undefined; const remaining = session?.selection.timerMode === 'countdown' && session.selection.timeLimitSeconds ? Math.max(0, session.selection.timeLimitSeconds - elapsed) : elapsed;
  const pause = async () => { if (!session) return; setSaving(true); try { setSession(await updatePracticeTimer(session.id, elapsed, session.status === 'in-progress')); } catch { setFailed(true); } finally { setSaving(false); } };
  const confirm = async () => { if (!session || !question || !selected) return; setSaving(true); try { setSession(await answerPracticeQuestion(session.id, selected, Date.now() - (questionStartedAt.current ?? Date.now()), elapsed)); } catch { setFailed(true); } finally { setSaving(false); } };
  const next = async () => { if (!session) return; setSaving(true); try { const updated = await advancePracticeSession(session.id, elapsed); if (updated.status === 'completed') { router.replace(`/exams/results?sessionId=${encodeURIComponent(updated.id)}` as Href); return; } questionStartedAt.current = Date.now(); setSelected(undefined); setSession(updated); } catch { setFailed(true); } finally { setSaving(false); } };
  if (loading) return <ScreenContainer scroll={false}><LoadingState label="Opening offline practice…" /></ScreenContainer>;
  if (!session || !question || failed) return <ScreenContainer contentStyle={styles.centered}><EmptyState title="Practice session unavailable" message="Any saved answers remain on this device." symbol="!" /><AppButton label="Back to practice" onPress={() => router.replace('/exams' as Href)} /></ScreenContainer>;
  if (session.status === 'paused') return <ScreenContainer contentStyle={styles.centered}><ThemedText type="title">Practice paused</ThemedText><ThemedText themeColor="textSecondary">Your time and answers are saved locally.</ThemedText><AppButton label="Resume" loading={saving} onPress={() => void pause()} /><AppButton label="Leave" variant="secondary" onPress={() => router.back()} /></ScreenContainer>;
  const resolved = answer?.selectedOptionId ?? selected; const progress = ((session.currentIndex + (answer ? 1 : 0)) / session.questions.length) * 100;
  return <ScreenContainer><View style={styles.top}><View><ThemedText type="smallBold">{session.selection.kind.replaceAll('-', ' ').toUpperCase()} · {session.selection.level}</ThemedText><ThemedText type="small" themeColor="textSecondary">Question {session.currentIndex + 1} of {session.questions.length}</ThemedText></View><AppButton label={session.selection.timerMode === 'none' ? 'Save & leave' : `${session.selection.timerMode === 'countdown' ? 'Left' : 'Time'} ${clock(remaining)}`} variant="quiet" loading={saving} onPress={() => void pause()} /></View><ProgressBar value={progress} accessibilityLabel="Practice progress" /><Card><ThemedText type="smallBold" themeColor="primary">{question.domain.toUpperCase()} · {question.presentation.replaceAll('-', ' ').toUpperCase()}</ThemedText><ThemedText type="heading">{question.prompt}</ThemedText></Card><View accessibilityRole="radiogroup" style={styles.options}>{question.options.map((option) => <QuestionOption key={option.id} label={option.label} selected={option.id === resolved} correctness={answer ? option.id === question.correctOptionId ? 'correct' : option.id === resolved ? 'incorrect' : undefined : undefined} disabled={Boolean(answer)} onPress={() => { questionStartedAt.current ||= Date.now(); setSelected(option.id); }} />)}</View>{answer ? <Card style={{ backgroundColor: answer.correct ? theme.successSoft : theme.errorSoft }}><ThemedText type="heading">{answer.correct ? 'Correct' : 'Review this one'}</ThemedText><ThemedText>{question.explanation ?? 'The correct answer is highlighted above.'}</ThemedText><AppButton label="Open lesson" variant="quiet" onPress={() => router.push(lessonRoute(question.domain, question.itemId))} /></Card> : null}{answer && !answer.correct ? <AiTeacherCard feature="explain_mistake" label="Explain my mistake" context={{ learnerLevel: question.level, item: { id: question.itemId, type: question.domain, title: question.prompt }, question: { prompt: question.prompt, userAnswer: answer.selectedOptionId, correctAnswer: question.correctOptionId, canonicalExplanation: question.explanation } }} /> : null}<AppButton label={answer ? session.currentIndex === session.questions.length - 1 ? 'See results' : 'Next question' : 'Confirm answer'} disabled={!answer && !selected} loading={saving} onPress={() => void (answer ? next() : confirm())} /></ScreenContainer>;
}
const styles = StyleSheet.create({ centered: { justifyContent: 'center' }, top: { flexDirection: 'row', justifyContent: 'space-between', gap: Spacing.two, alignItems: 'center' }, options: { gap: Spacing.two } });
