import type { AiTeacherRequest, AiTeacherResponse } from '@/types/ai';
import { createLocalId } from '@/utils/id';

import { getDatabase } from './database';

interface CacheRow { response_json: string; expires_at: string; }

export async function getAiCachedResponse(key: string): Promise<{ response: AiTeacherResponse; expiresAt: string } | undefined> { const database = await getDatabase(); const row = await database.getFirstAsync<CacheRow>('SELECT response_json, expires_at FROM ai_response_cache WHERE cache_key = ?', key); return row ? { response: JSON.parse(row.response_json) as AiTeacherResponse, expiresAt: row.expires_at } : undefined; }
export async function saveAiResponseCache(key: string, request: AiTeacherRequest, response: AiTeacherResponse): Promise<void> { const database = await getDatabase(); const now = new Date(); const expiresAt = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(); await database.runAsync(`INSERT INTO ai_response_cache (cache_key, feature_type, request_fingerprint, response_json, prompt_version, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(cache_key) DO UPDATE SET response_json = excluded.response_json, created_at = excluded.created_at, expires_at = excluded.expires_at`, key, request.feature, key, JSON.stringify(response), request.promptVersion, now.toISOString(), expiresAt); await database.runAsync(`DELETE FROM ai_response_cache WHERE expires_at < ? OR cache_key NOT IN (SELECT cache_key FROM ai_response_cache ORDER BY created_at DESC LIMIT 120)`, now.toISOString()); }
export async function saveAiInteraction(request: AiTeacherRequest, response: AiTeacherResponse, status: 'completed' | 'offline-fallback', cached: boolean, fallbackUsed: boolean): Promise<void> { const database = await getDatabase(); await database.runAsync(`INSERT INTO ai_interaction_history (id, feature_type, related_content_type, related_content_id, user_input, validated_response_json, prompt_version, status, cached, fallback_used, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, createLocalId('ai-history'), request.feature, request.context.item?.type ?? null, request.context.item?.id ?? null, request.userInput ?? null, JSON.stringify(response), request.promptVersion, status, cached ? 1 : 0, fallbackUsed ? 1 : 0, new Date().toISOString()); }
export async function saveFailedAiDraft(request: AiTeacherRequest, errorCode: string): Promise<void> { const database = await getDatabase(); await database.runAsync(`INSERT INTO ai_failed_request_drafts (id, feature_type, context_json, user_input, prompt_version, error_code, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`, createLocalId('ai-draft'), request.feature, JSON.stringify(request.context), request.userInput ?? null, request.promptVersion, errorCode, new Date().toISOString()); }
export async function clearAiHistoryAndCache(): Promise<void> { const database = await getDatabase(); await database.withTransactionAsync(async () => { await database.runAsync('DELETE FROM ai_interaction_history'); await database.runAsync('DELETE FROM ai_response_cache'); await database.runAsync('DELETE FROM ai_failed_request_drafts'); }); }
