import type { AudioLessonType } from './contracts';
import type { AudioPilotDefinition } from './pilots';

interface CurriculumUnit {
  slug: string;
  title: string;
  subtitle: string;
  level: 'N5' | 'N4';
  type: AudioLessonType;
  difficulty: number;
  objective: string;
  vocabularyJapanese: string;
  vocabularyEnglish: string;
  grammarJapanese: string;
  grammarEnglish: string;
  exampleJapanese: string;
  sceneJapanese: string;
  question: string;
  choices: readonly [string, string, string, string];
  correctIndex: number;
  evidence: string;
  trap: string;
}

const speakerPairs: readonly (readonly [string, string])[] = [
  ['Hana', 'Kota'], ['Mio', 'Shun'], ['Aoi', 'Daiki'], ['Sara', 'Yuma'], ['Nami', 'Itsuki'],
  ['Riku', 'Mei'], ['Yuna', 'Sota'], ['Fumi', 'Akira'], ['Chika', 'Taiga'], ['Kaori', 'Nobu'],
  ['Eri', 'Ryo'], ['Maki', 'Yuki'], ['Naoki', 'Mina'], ['Risa', 'Jun'], ['Ayaka', 'Toru'],
  ['Kenta', 'Misaki'], ['Yui', 'Shota'], ['Reina', 'Koji'], ['Sayuri', 'Hiro'], ['Mao', 'Kazu'],
  ['Yoko', 'Takeshi'], ['Natsumi', 'Gen'], ['Haruka', 'Leo'], ['Iori', 'Sena'], ['Tomoko', 'Koki'],
];

function unitToDefinition(unit: CurriculumUnit, index: number): AudioPilotDefinition {
  const [firstSpeaker, secondSpeaker] = speakerPairs[index % speakerPairs.length]!;
  return {
    slug: unit.slug,
    title: unit.title,
    subtitle: unit.subtitle,
    level: unit.level,
    type: unit.type,
    difficulty: unit.difficulty,
    objective: unit.objective,
    speakerNames: [firstSpeaker, secondSpeaker],
    japanese: [unit.vocabularyJapanese, unit.grammarJapanese, unit.exampleJapanese, unit.sceneJapanese],
    englishGoal: unit.objective,
    questionPrompt: unit.question,
    choices: unit.choices,
    correctIndex: unit.correctIndex,
    correctExplanation: unit.evidence,
    commonMistake: unit.trap,
    vocabularyNote: unit.vocabularyEnglish,
    grammarNote: unit.grammarEnglish,
  };
}

const units: readonly CurriculumUnit[] = [
  {
    slug: 'n5-umbrella-shelf-kore-sore', title: 'Which Umbrella Is Yours?', subtitle: 'Use これ・それ・あれ while finding a forgotten umbrella.',
    level: 'N5', type: 'dialogue_practice', difficulty: 1, objective: 'Identify an object by its distance from the speakers.',
    vocabularyJapanese: '今日の言葉は、かさ、棚、そして「これ・それ・あれ」です。近い物と遠い物を分けて聞きましょう。',
    vocabularyEnglish: 'Vocabulary: かさ means umbrella, and 棚 means shelf. これ is near the speaker, それ is near the listener, and あれ is away from both.',
    grammarJapanese: '「これはわたしのかさです。」のように、物を指して説明できます。',
    grammarEnglish: 'Use これ・それ・あれ before です to identify one specific thing. The location of the object changes the word, not its owner.',
    exampleJapanese: 'ハナ：わたしのかさは、青くて小さいです。',
    sceneJapanese: 'コウタ：入口の棚にある黒いかさですか。ハナ：いいえ、あれではなくて、その青いかさです。',
    question: 'Which umbrella belongs to Hana?', choices: ['The black umbrella by the entrance.', 'The small blue umbrella near Kota.', 'The large red umbrella outside.', 'The clear umbrella on the desk.'], correctIndex: 1,
    evidence: 'Hana rejects the black umbrella and identifies the blue one near Kota.', trap: 'Do not stop at あれ; Hana immediately corrects which umbrella she means.',
  },
  {
    slug: 'n5-post-office-place-ni', title: 'A Parcel at the Post Office', subtitle: 'Hear where to put something with に and へ.',
    level: 'N5', type: 'sentence_pattern_drill', difficulty: 2, objective: 'Follow a destination and a placement instruction.',
    vocabularyJapanese: '郵便局では、荷物、窓口、住所を聞きます。荷物は parcel、窓口は service counter です。',
    vocabularyEnglish: 'Vocabulary: 荷物 is a parcel or luggage, 窓口 is a service counter, and 住所 is an address.',
    grammarJapanese: '場所に物を置きます。行く場所には、に または へ を使えます。',
    grammarEnglish: 'Use に for where something is placed and に or へ for where a person goes. Listen for the noun just before the particle.',
    exampleJapanese: 'ミオ：この荷物を窓口に置いてください。',
    sceneJapanese: 'シュン：分かりました。そのあとで、二番の窓口へ行って住所を書きます。',
    question: 'What will Shun do after putting down the parcel?', choices: ['Write the address at counter two.', 'Take the parcel home.', 'Buy an umbrella.', 'Meet a teacher outside.'], correctIndex: 0,
    evidence: 'Shun says he will go to counter two and write the address.', trap: 'The parcel is placed first; the next action is writing the address.',
  },
  {
    slug: 'n5-neighbourhood-imasu', title: 'Who Lives Next Door?', subtitle: 'Listen for people and animals with います.',
    level: 'N5', type: 'vocabulary_review', difficulty: 1, objective: 'Distinguish a person from a pet in a neighbourhood conversation.',
    vocabularyJapanese: 'となり means next door、犬 means dog、家族 means family です。人や動物には います を使います。',
    vocabularyEnglish: 'Vocabulary: となり means next door, 犬 means dog, and 家族 means family. Use います for living things.',
    grammarJapanese: '「となりに犬がいます。」は、そこに犬がいるという意味です。',
    grammarEnglish: 'Use います for people and animals. For a chair or a shop, Japanese uses あります instead.',
    exampleJapanese: 'アオイ：となりの家に、元気な犬がいます。',
    sceneJapanese: 'ダイキ：そうですか。わたしは犬より、そこで働いているお姉さんに会ったことがあります。',
    question: 'Who has Daiki met?', choices: ['The woman who works there.', 'The dog next door.', 'A visiting doctor.', 'A student from his class.'], correctIndex: 0,
    evidence: 'Daiki says he has met the older sister who works at the neighbouring house.', trap: 'A dog is mentioned first, but Daiki says he met the woman, not the dog.',
  },
  {
    slug: 'n5-bakery-counters', title: 'Three Sweet Buns', subtitle: 'Practise counters while ordering at a bakery.',
    level: 'N5', type: 'vocabulary_review', difficulty: 2, objective: 'Hear the quantity and item in a bakery order.',
    vocabularyJapanese: 'パン屋では、あんパン、メロンパン、袋を聞きます。小さい物の数には、～つ が便利です。',
    vocabularyEnglish: 'Vocabulary: あんパン is a sweet bean-paste bun, メロンパン is a melon-shaped sweet bun, and 袋 is a bag.',
    grammarJapanese: '「あんパンを三つください。」のように、物のあとに数を付けて注文します。',
    grammarEnglish: 'For many everyday items, ～つ is a useful counter. Keep the item and its number together in your ear.',
    exampleJapanese: 'サラ：あんパンを三つと、メロンパンを一つください。',
    sceneJapanese: 'ユウマ：はい。袋は一枚でいいですか。サラ：はい、お願いします。',
    question: 'How many melon buns does Sara order?', choices: ['One.', 'Two.', 'Three.', 'None.'], correctIndex: 0,
    evidence: 'Sara orders メロンパンを一つ, one melon bun.', trap: 'Three belongs to the sweet bean buns, not to the melon buns.',
  },
  {
    slug: 'n5-weekend-tari', title: 'A Relaxed Saturday', subtitle: 'Hear several weekend activities with たり…たりします.',
    level: 'N5', type: 'short_story', difficulty: 2, objective: 'Understand a non-exhaustive list of activities.',
    vocabularyJapanese: '週末 means weekend、洗濯 means laundry、散歩 means a walk です。',
    vocabularyEnglish: 'Vocabulary: 週末 is weekend, 洗濯 is laundry, and 散歩 is a walk.',
    grammarJapanese: '動詞のた形に り を付けて、「読んだり、散歩したりします」と言えます。',
    grammarEnglish: 'たり…たりします lists representative activities, not every action someone does. It often sounds like “do things such as…”',
    exampleJapanese: 'ナミ：土曜日は本を読んだり、洗濯したりします。',
    sceneJapanese: 'イツキ：ぼくは午前中に散歩したり、午後は友だちとゲームをしたりします。',
    question: 'What does Itsuki do in the afternoon?', choices: ['Plays games with a friend.', 'Does the laundry.', 'Reads a book at work.', 'Takes a train to school.'], correctIndex: 0,
    evidence: 'Itsuki says he plays games with a friend in the afternoon.', trap: 'Laundry and reading belong to Nami’s Saturday, not Itsuki’s afternoon.',
  },
  {
    slug: 'n5-weather-adjectives', title: 'Is the Park Still Nice?', subtitle: 'Use い-adjectives to talk about weather and a place.',
    level: 'N5', type: 'dialogue_practice', difficulty: 2, objective: 'Recognise a positive and negative adjective description.',
    vocabularyJapanese: '暑い means hot、涼しい means cool、広い means spacious です。',
    vocabularyEnglish: 'Vocabulary: 暑い means hot, 涼しい means cool, and 広い means spacious.',
    grammarJapanese: 'い-adjectives can describe a noun: 「広い公園」「暑くない日」です。',
    grammarEnglish: 'An い-adjective can come before a noun, and 暑い becomes 暑くない for “not hot.”',
    exampleJapanese: 'リク：この公園は広いですね。でも、今日は暑いです。',
    sceneJapanese: 'メイ：夕方なら涼しいですよ。六時ごろに行きませんか。',
    question: 'Why does Mei suggest going at six?', choices: ['It should be cooler then.', 'The park closes at six.', 'She needs to buy a ticket.', 'Her class starts at six.'], correctIndex: 0,
    evidence: 'Mei says the evening will be cool and suggests around six.', trap: 'The park is spacious now; the changed detail is the temperature later.',
  },
  {
    slug: 'n5-bus-transfer-te-form', title: 'Changing Buses After Work', subtitle: 'Follow two actions linked with the て-form.',
    level: 'N5', type: 'sentence_pattern_drill', difficulty: 2, objective: 'Identify the first step in a travel sequence.',
    vocabularyJapanese: '乗り換え means transfer、次 means next、角 means corner. These help when you hear directions.',
    vocabularyEnglish: 'Vocabulary: 乗り換え means transfer, 次 means next, and 角 means a street corner.',
    grammarJapanese: '動詞のて形は、順番にする行動をつなげます。「バスを降りて、次のバスに乗ります。」',
    grammarEnglish: 'The て-form connects actions in sequence. Listen for the first verb before deciding what happens next.',
    exampleJapanese: 'ユナ：駅前でバスを降りて、青いバスに乗り換えます。',
    sceneJapanese: 'ソウタ：分かりました。次の角で降りたら、会社はすぐです。',
    question: 'Which bus should Yuna take after getting off?', choices: ['The blue bus.', 'The first train.', 'A red taxi.', 'No vehicle at all.'], correctIndex: 0,
    evidence: 'Yuna says she transfers to the blue bus.', trap: 'The next corner tells where to get off later; it is not the vehicle to take.',
  },
  {
    slug: 'n5-classroom-nai-de', title: 'Quietly Before the Test', subtitle: 'Listen to a classroom instruction with ないでください.',
    level: 'N5', type: 'grammar_explanation', difficulty: 2, objective: 'Understand what not to do during a test.',
    vocabularyJapanese: '試験 means test、辞書 means dictionary、机 means desk です。',
    vocabularyEnglish: 'Vocabulary: 試験 is a test, 辞書 is a dictionary, and 机 is a desk.',
    grammarJapanese: '「辞書を見ないでください」は、辞書を見ないようにお願いする言い方です。',
    grammarEnglish: 'Attach ないでください to the negative form to make a polite “please do not…” request.',
    exampleJapanese: 'フミ：試験の間、となりの人と話さないでください。',
    sceneJapanese: 'アキラ：辞書も見ないでください。分からない言葉は、そのままにしましょう。',
    question: 'What are students told not to use?', choices: ['A dictionary.', 'A pencil.', 'Their desk.', 'The classroom door.'], correctIndex: 0,
    evidence: 'Akira specifically says not to use a dictionary.', trap: 'Talking is also prohibited, but the question asks about an item students must not use.',
  },
  {
    slug: 'n5-hotel-checkin', title: 'Checking In After a Long Trip', subtitle: 'Catch a name, a night count, and a room detail.',
    level: 'N5', type: 'listening_comprehension', difficulty: 3, objective: 'Identify the requested room type in a short hotel exchange.',
    vocabularyJapanese: '予約 means reservation、禁煙 means non-smoking、二泊 means two nights です。',
    vocabularyEnglish: 'Vocabulary: 予約 is a reservation, 禁煙 means non-smoking, and 二泊 means two nights.',
    grammarJapanese: '「二泊したいです」は、泊まりたい日数を丁寧に言う文です。',
    grammarEnglish: 'Use a counter such as 二泊 before したいです to say how many nights you want to stay.',
    exampleJapanese: 'チカ：予約したチカです。金曜日から二泊したいです。',
    sceneJapanese: 'タイガ：はい。禁煙の部屋でよろしいですか。チカ：はい、お願いします。',
    question: 'What kind of room does Chika request?', choices: ['A non-smoking room.', 'A room for one night.', 'A room with breakfast only.', 'A room near the station.'], correctIndex: 0,
    evidence: 'Chika agrees to the non-smoking room.', trap: 'Two nights is the length of stay; it does not describe the room itself.',
  },
  {
    slug: 'n5-clinic-body-parts', title: 'At the Clinic: A Sore Throat', subtitle: 'Understand a simple health complaint and advice.',
    level: 'N5', type: 'listening_comprehension', difficulty: 3, objective: 'Identify the symptom that brings a patient to the clinic.',
    vocabularyJapanese: 'のど means throat、熱 means fever、薬 means medicine です。',
    vocabularyEnglish: 'Vocabulary: のど is throat, 熱 is a fever, and 薬 is medicine.',
    grammarJapanese: '「のどが痛いです」で、痛い場所を説明できます。',
    grammarEnglish: 'Use body part + が + 痛いです to say where something hurts.',
    exampleJapanese: 'カオリ：昨日から、のどが痛くて熱もあります。',
    sceneJapanese: 'ノブ：今日は薬を飲んで、早く寝てください。明日も熱があれば、もう一度来てください。',
    question: 'What hurts Kaori?', choices: ['Her throat.', 'Her leg.', 'Her eye.', 'Her hand.'], correctIndex: 0,
    evidence: 'Kaori says のどが痛い, meaning her throat hurts.', trap: 'Fever is another symptom; it is not the body part that hurts.',
  },
  {
    slug: 'n5-invitation-masenka', title: 'Would You Like to Join Us?', subtitle: 'Hear a friendly invitation and a natural reply.',
    level: 'N5', type: 'dialogue_practice', difficulty: 2, objective: 'Recognise an invitation with ませんか.',
    vocabularyJapanese: '映画 means movie、今晩 means tonight、予定 means plan です。',
    vocabularyEnglish: 'Vocabulary: 映画 is a movie, 今晩 means tonight, and 予定 is a plan.',
    grammarJapanese: '「映画を見ませんか」は、一緒に映画を見る誘いです。',
    grammarEnglish: 'The polite negative question ませんか is often a warm invitation: “Would you like to…?”',
    exampleJapanese: 'エリ：今晩、駅の近くで映画を見ませんか。',
    sceneJapanese: 'リョウ：いいですね。七時なら予定がありません。入口で会いましょう。',
    question: 'When can Ryo meet?', choices: ['At seven.', 'At noon.', 'Tomorrow morning.', 'After work next week.'], correctIndex: 0,
    evidence: 'Ryo says he has no plans at seven.', trap: 'Tonight is the broad time; seven is the specific meeting time.',
  },
  {
    slug: 'n5-map-where-is-it', title: 'Where Is the Bookstore?', subtitle: 'Follow a location question and a short direction.',
    level: 'N5', type: 'sentence_pattern_drill', difficulty: 2, objective: 'Identify a destination from a landmark-based direction.',
    vocabularyJapanese: '本屋 means bookstore、銀行 means bank、交差点 means intersection です。',
    vocabularyEnglish: 'Vocabulary: 本屋 is bookstore, 銀行 is bank, and 交差点 is an intersection.',
    grammarJapanese: '場所を聞く時は「本屋はどこですか」と言います。',
    grammarEnglish: 'Use はどこですか to ask where a place is. Answers often use の前, の後ろ, or のとなり.',
    exampleJapanese: 'リサ：すみません。本屋はどこですか。',
    sceneJapanese: 'ジュン：銀行のとなりです。この交差点を右に曲がってください。',
    question: 'Where is the bookstore?', choices: ['Next to the bank.', 'Behind the station.', 'Inside the library.', 'Across from the hospital.'], correctIndex: 0,
    evidence: 'Jun says the bookstore is next to the bank.', trap: 'Turning right is the route; the bank is the landmark that gives the final location.',
  },
  {
    slug: 'n5-supermarket-quantities', title: 'Enough Ingredients for Curry?', subtitle: 'Hear measures and quantities in a shopping list.',
    level: 'N5', type: 'vocabulary_review', difficulty: 3, objective: 'Identify the ingredient that still needs to be bought.',
    vocabularyJapanese: '牛肉 means beef、にんじん means carrot、一袋 means one bag です。',
    vocabularyEnglish: 'Vocabulary: 牛肉 is beef, にんじん is carrot, and 一袋 means one bag.',
    grammarJapanese: '「にんじんは一袋ありますが、牛肉がありません」で、ある物とない物を比べます。',
    grammarEnglish: 'あります says something is available; ありません says it is missing. The contrast が is the clue here.',
    exampleJapanese: 'アヤカ：たまねぎは二つあります。にんじんも一袋あります。',
    sceneJapanese: 'トオル：では、牛肉だけ買いましょう。カレーのために、三百グラムください。',
    question: 'What do they still need to buy?', choices: ['Beef.', 'Onions.', 'Carrots.', 'A bag.'], correctIndex: 0,
    evidence: 'They already have onions and carrots, so Toru says to buy only beef.', trap: 'Three hundred grams tells the amount of beef, not a different missing ingredient.',
  },
  {
    slug: 'n5-mail-from-until', title: 'Mail Before the Counter Closes', subtitle: 'Listen for opening hours with から and まで.',
    level: 'N5', type: 'jlpt_listening_practice', difficulty: 3, objective: 'Select the correct time window from a practical announcement.',
    vocabularyJapanese: '開きます means opens、閉まります means closes、午後 means afternoon です。',
    vocabularyEnglish: 'Vocabulary: 開きます is opens, 閉まります is closes, and 午後 is afternoon.',
    grammarJapanese: '時間の範囲は「九時から五時まで」です。',
    grammarEnglish: 'Use から for the starting time and まで for the ending time. Keep both numbers separate.',
    exampleJapanese: '郵便局は平日の九時から五時まで開いています。',
    sceneJapanese: 'マオ：四時半なら間に合いますね。カズ：はい。でも土曜日は午後一時に閉まります。',
    question: 'What time does the post office close on Saturday?', choices: ['1 p.m.', '4:30 p.m.', '5 p.m.', '9 a.m.'], correctIndex: 0,
    evidence: 'Kazu says that on Saturday it closes at one in the afternoon.', trap: 'Five is the weekday closing time, deliberately different from Saturday.',
  },
  {
    slug: 'n5-birthday-present', title: 'Choosing a Birthday Present', subtitle: 'Compare preferences while planning a small gift.',
    level: 'N5', type: 'dialogue_practice', difficulty: 2, objective: 'Identify the gift the friends decide to buy.',
    vocabularyJapanese: '誕生日 means birthday、花 means flowers、時計 means watch です。',
    vocabularyEnglish: 'Vocabulary: 誕生日 is birthday, 花 means flowers, and 時計 is a watch.',
    grammarJapanese: '「花より時計のほうがいいです」で、二つの物を比べられます。',
    grammarEnglish: 'Use AよりBのほうがいい to say B is better than A in a comparison.',
    exampleJapanese: 'ナツミ：ユキさんは花より、実用的な物が好きだと思います。',
    sceneJapanese: 'ゲン：では、小さい時計にしましょう。青い色なら、仕事にも使えます。',
    question: 'What do they decide to buy?', choices: ['A small blue watch.', 'A large flower basket.', 'A movie ticket.', 'A red umbrella.'], correctIndex: 0,
    evidence: 'Gen decides on a small blue watch.', trap: 'Flowers are the rejected comparison, not the final gift.',
  },
  {
    slug: 'n5-restaurant-order', title: 'One More Bowl of Rice', subtitle: 'Hear a polite restaurant request and a reason.',
    level: 'N5', type: 'dialogue_practice', difficulty: 2, objective: 'Identify what the customer asks for after the meal begins.',
    vocabularyJapanese: 'ご飯 means rice、みそ汁 means miso soup、おかわり means another serving です。',
    vocabularyEnglish: 'Vocabulary: ご飯 is rice, みそ汁 is miso soup, and おかわり means another serving.',
    grammarJapanese: '「ご飯をおかわりできますか」は、もう一杯ほしい時の丁寧な聞き方です。',
    grammarEnglish: 'できますか asks whether something is possible. It is a useful polite request in a restaurant.',
    exampleJapanese: 'ハルカ：すみません。ご飯をおかわりできますか。',
    sceneJapanese: 'レオ：もちろんです。みそ汁も温かくしますか。ハルカ：みそ汁は大丈夫です。',
    question: 'What does Haruka ask for?', choices: ['Another serving of rice.', 'Hotter miso soup.', 'A new table.', 'The bill.'], correctIndex: 0,
    evidence: 'Haruka asks whether she can have another serving of rice.', trap: 'The server offers warmer soup, but Haruka says she does not need it.',
  },
  {
    slug: 'n5-trip-photos-past', title: 'Photos from Nara', subtitle: 'Review past-tense actions in a travel memory.',
    level: 'N5', type: 'short_story', difficulty: 2, objective: 'Identify what someone did during a trip.',
    vocabularyJapanese: '鹿 means deer、写真 means photo、去年 means last year です。',
    vocabularyEnglish: 'Vocabulary: 鹿 is deer, 写真 is photo, and 去年 means last year.',
    grammarJapanese: 'ました is the polite past ending: 見ました、撮りました、食べました。',
    grammarEnglish: 'Use ました to describe a completed action. The past marker tells you the speaker is remembering, not planning.',
    exampleJapanese: 'ユイ：去年、奈良で鹿を見て、たくさん写真を撮りました。',
    sceneJapanese: 'ショウタ：ぼくはそこでお茶を飲みました。次は春に行きたいです。',
    question: 'What did Yui do in Nara?', choices: ['She took many photos.', 'She bought a watch.', 'She changed buses.', 'She wrote an address.'], correctIndex: 0,
    evidence: 'Yui says she saw deer and took many photos.', trap: 'Drinking tea belongs to Shota, not Yui.',
  },
  {
    slug: 'n5-cleaning-te-iru', title: 'The Room Is Being Cleaned', subtitle: 'Hear an ongoing action with ています.',
    level: 'N5', type: 'listening_comprehension', difficulty: 2, objective: 'Recognise what is happening right now.',
    vocabularyJapanese: '掃除 means cleaning、窓 means window、床 means floor です。',
    vocabularyEnglish: 'Vocabulary: 掃除 is cleaning, 窓 is window, and 床 is floor.',
    grammarJapanese: '「窓を開けています」は、今その状態や行動が続いている意味です。',
    grammarEnglish: 'The ています form can describe an action in progress or a current state. The surrounding words reveal which.',
    exampleJapanese: 'レイナ：今、床を掃除していますから、気をつけてください。',
    sceneJapanese: 'コウジ：分かりました。ぼくは窓を開けています。空気がきれいになりますね。',
    question: 'What is Reina doing?', choices: ['Cleaning the floor.', 'Opening the window.', 'Cooking dinner.', 'Writing a letter.'], correctIndex: 0,
    evidence: 'Reina says she is cleaning the floor.', trap: 'Opening the window is Koji’s action, not Reina’s.',
  },
  {
    slug: 'n5-work-schedule', title: 'A Shift Swap on Friday', subtitle: 'Listen for who works and who has the day off.',
    level: 'N5', type: 'jlpt_listening_practice', difficulty: 3, objective: 'Track a changed work schedule across two speakers.',
    vocabularyJapanese: '仕事 means work、休み means day off、金曜日 means Friday です。',
    vocabularyEnglish: 'Vocabulary: 仕事 is work, 休み is a day off, and 金曜日 is Friday.',
    grammarJapanese: '「金曜日は仕事です。でも土曜日は休みです」で、曜日ごとの予定を言えます。',
    grammarEnglish: 'Use は to set the day as the topic, then listen for whether the speaker says 仕事 or 休み.',
    exampleJapanese: 'サユリ：金曜日は休みでしたが、マリさんと仕事を替えました。',
    sceneJapanese: 'ヒロ：じゃあ、土曜日はサユリさんが休みですね。サユリ：はい、その日に病院へ行きます。',
    question: 'When is Sayuri off work now?', choices: ['Saturday.', 'Friday.', 'Monday.', 'Every day.'], correctIndex: 0,
    evidence: 'Sayuri swapped Friday and is now off on Saturday.', trap: 'Friday was originally her day off, but the schedule changed.',
  },
  {
    slug: 'n4-appointment-yotei', title: 'A Dentist Appointment Plan', subtitle: 'Use 予定 to discuss a planned appointment.',
    level: 'N4', type: 'grammar_explanation', difficulty: 3, objective: 'Identify a fixed plan and the reason it moves.',
    vocabularyJapanese: '予定 means plan or schedule、歯医者 means dentist、空いています means available です。',
    vocabularyEnglish: 'Vocabulary: 予定 is a plan or schedule, 歯医者 is dentist, and 空いています means available.',
    grammarJapanese: '「火曜日に歯医者へ行く予定です」で、前から決めている予定を言えます。',
    grammarEnglish: '予定です signals an arranged or expected plan. It is firmer than simply saying you want to do something.',
    exampleJapanese: 'ヨウコ：火曜日の午後は、歯医者へ行く予定です。',
    sceneJapanese: 'タケシ：その時間、会議が入りました。歯医者は水曜日に変えられますか。ヨウコ：電話してみます。',
    question: 'Why might Yoko change her dentist appointment?', choices: ['A meeting was added.', 'The dentist is closed for a year.', 'She lost her phone.', 'She wants to travel.'], correctIndex: 0,
    evidence: 'Takeshi says a meeting has been scheduled for that time.', trap: 'Tuesday is the original plan; the new meeting is the reason for considering a change.',
  },
  {
    slug: 'n4-commute-nagara', title: 'Podcasts on the Commute', subtitle: 'Hear two simultaneous actions with ながら.',
    level: 'N4', type: 'shadowing_practice', difficulty: 3, objective: 'Recognise the main action while another action happens alongside it.',
    vocabularyJapanese: '通勤 means commuting、番組 means programme、復習 means review です。',
    vocabularyEnglish: 'Vocabulary: 通勤 is commuting, 番組 is a programme, and 復習 is review.',
    grammarJapanese: '「電車に乗りながら、日本語の番組を聞きます」で、同時にする二つの行動を言います。',
    grammarEnglish: 'With ながら, the final verb is the main action. The earlier verb is what happens alongside it.',
    exampleJapanese: 'ナツミ：通勤しながら、日本語の番組を聞いています。',
    sceneJapanese: 'ゲン：ぼくは歩きながら聞くと危ないので、電車の中だけで復習しています。',
    question: 'Where does Gen review Japanese?', choices: ['Only on the train.', 'While crossing a road.', 'At the dentist.', 'During a meeting.'], correctIndex: 0,
    evidence: 'Gen says he reviews only inside the train because listening while walking is dangerous.', trap: 'Walking is the activity Gen avoids combining with listening.',
  },
  {
    slug: 'n4-repair-teshimau', title: 'The Broken Coffee Maker', subtitle: 'Understand regret or completion with てしまいました.',
    level: 'N4', type: 'short_story', difficulty: 3, objective: 'Identify the accidental result in a household problem.',
    vocabularyJapanese: '壊れます means breaks、修理 means repair、こぼします means spill です。',
    vocabularyEnglish: 'Vocabulary: 壊れます is breaks, 修理 is repair, and こぼします is spill.',
    grammarJapanese: '「水をこぼしてしまいました」は、残念な気持ちのある完了を表します。',
    grammarEnglish: 'てしまいました often marks an unwanted accident or something finished completely. Tone and context tell which.',
    exampleJapanese: 'ミナ：急いでいて、コーヒーを機械の中にこぼしてしまいました。',
    sceneJapanese: 'ナオキ：電源を入れないでください。明日、修理の人に見てもらいましょう。',
    question: 'What should Mina not do?', choices: ['Turn on the machine.', 'Call a repair person.', 'Clean the floor.', 'Make tea tomorrow.'], correctIndex: 0,
    evidence: 'Naoki tells Mina not to turn on the machine.', trap: 'Calling a repair person is the planned solution, not the action she must avoid.',
  },
  {
    slug: 'n4-city-guide-nara', title: 'If It Rains, Take the Museum Route', subtitle: 'Use なら to offer practical conditional advice.',
    level: 'N4', type: 'grammar_explanation', difficulty: 3, objective: 'Choose advice that fits a stated condition.',
    vocabularyJapanese: '雨なら means if it is rainy、案内所 means information desk、地下道 means underground passage です。',
    vocabularyEnglish: 'Vocabulary: 雨なら means if it is rainy, 案内所 is an information desk, and 地下道 is an underground passage.',
    grammarJapanese: '「雨なら、地下道を通ったほうがいいです」で、条件に合う助言をします。',
    grammarEnglish: 'なら takes the condition raised in the conversation and gives a response especially suited to it.',
    exampleJapanese: 'ケンタ：明日、雨なら美術館へ行こうと思います。',
    sceneJapanese: 'ミサキ：それなら、駅の案内所で地図をもらうといいですよ。地下道で行けます。',
    question: 'What does Misaki recommend getting?', choices: ['A map at the station information desk.', 'A new umbrella at the museum.', 'A train ticket for Friday.', 'Coffee before work.'], correctIndex: 0,
    evidence: 'Misaki recommends getting a map at the station information desk.', trap: 'The underground passage is the route, while the map is the thing she recommends getting.',
  },
  {
    slug: 'n4-cooking-youni', title: 'Cooking So Everyone Can Eat', subtitle: 'Hear a purpose and a careful cooking adjustment.',
    level: 'N4', type: 'dialogue_practice', difficulty: 3, objective: 'Identify the change made to suit another person.',
    vocabularyJapanese: '辛い means spicy、苦手 means not good with、子ども means child です。',
    vocabularyEnglish: 'Vocabulary: 辛い means spicy, 苦手 means not good with, and 子ども means child.',
    grammarJapanese: '「子どもも食べられるように、辛くしません」で、目的のための工夫を言えます。',
    grammarEnglish: 'ように can express doing something so that a desired result becomes possible.',
    exampleJapanese: 'ユイ：弟は辛い料理が苦手です。',
    sceneJapanese: 'ショウタ：じゃあ、子どもも食べられるように、唐辛子は最後に入れましょう。',
    question: 'Why will they add chili at the end?', choices: ['So the child can eat the dish.', 'So the meal cooks faster.', 'So they can leave early.', 'So the soup becomes colder.'], correctIndex: 0,
    evidence: 'They delay the chili so the child can eat the meal.', trap: 'The issue is the child’s tolerance for spicy food, not the cooking time.',
  },
  {
    slug: 'n4-school-advice-hou-ga-ii', title: 'Better Study Habits Before the Exam', subtitle: 'Compare two study choices with ほうがいい.',
    level: 'N4', type: 'grammar_explanation', difficulty: 3, objective: 'Identify the recommended study action.',
    vocabularyJapanese: '徹夜 means staying up all night、集中 means concentration、休憩 means break です。',
    vocabularyEnglish: 'Vocabulary: 徹夜 is staying up all night, 集中 is concentration, and 休憩 is a break.',
    grammarJapanese: '「徹夜しないで、少し寝たほうがいいです」は、相手への助言です。',
    grammarEnglish: 'たほうがいい gives positive advice; ないほうがいい advises against an action.',
    exampleJapanese: 'レイナ：明日の試験が心配で、今夜は徹夜しようかな。',
    sceneJapanese: 'コウジ：徹夜しないで、少し寝たほうがいいよ。朝のほうが集中できるから。',
    question: 'What does Koji recommend?', choices: ['Get some sleep.', 'Study all night.', 'Skip the exam.', 'Buy a new dictionary.'], correctIndex: 0,
    evidence: 'Koji says it is better not to stay up all night and to sleep a little.', trap: 'The exam is tomorrow, but Koji does not advise skipping it.',
  },
  {
    slug: 'n4-customer-call-ukeru', title: 'Taking a Customer Call', subtitle: 'Follow a polite office message and its next step.',
    level: 'N4', type: 'dialogue_practice', difficulty: 4, objective: 'Identify who should receive a returned call.',
    vocabularyJapanese: 'お客様 means customer、折り返し means call back、伝言 means message です。',
    vocabularyEnglish: 'Vocabulary: お客様 is a customer, 折り返し is a return call, and 伝言 is a message.',
    grammarJapanese: '「田中さんに折り返しお電話いただけますか」は、丁寧に依頼する表現です。',
    grammarEnglish: 'In business Japanese, お電話いただけますか politely asks another person to make a call.',
    exampleJapanese: 'マオ：田中様からお電話がありました。三時ごろ、もう一度かけるそうです。',
    sceneJapanese: 'カズ：分かりました。戻ったら、田中さんに折り返し電話します。伝言を机に置いてください。',
    question: 'Who will Kazu call back?', choices: ['Tanaka.', 'The teacher.', 'The dentist.', 'His neighbour.'], correctIndex: 0,
    evidence: 'Kazu says he will return Tanaka’s call.', trap: 'The message goes on the desk, but the person receiving the call is Tanaka.',
  },
  {
    slug: 'n4-weather-souda', title: 'A Storm Is Coming, Apparently', subtitle: 'Separate hearsay from a direct observation with そうです.',
    level: 'N4', type: 'listening_comprehension', difficulty: 3, objective: 'Identify the weather information reported by the forecast.',
    vocabularyJapanese: '予報 means forecast、嵐 means storm、降り出す means start to fall です。',
    vocabularyEnglish: 'Vocabulary: 予報 is a forecast, 嵐 is a storm, and 降り出す means begin to fall.',
    grammarJapanese: '「予報によると、夜は嵐になるそうです」は、人から聞いた情報です。',
    grammarEnglish: 'そうです can report information you heard. The phrase 予報によると makes the source especially clear.',
    exampleJapanese: 'ヨウコ：予報によると、今夜は強い雨になるそうです。',
    sceneJapanese: 'タケシ：じゃあ、洗濯物を中に入れましょう。もう雲が黒くなっています。',
    question: 'What will they do?', choices: ['Bring the laundry inside.', 'Go hiking tonight.', 'Open every window.', 'Wash the car outside.'], correctIndex: 0,
    evidence: 'Because rain is forecast, Takeshi says they should bring the laundry inside.', trap: 'The dark clouds confirm the concern; they do not mean the storm has already finished.',
  },
  {
    slug: 'n4-news-rashii', title: 'A New Bakery Is Opening, It Seems', subtitle: 'Hear uncertain information with らしい.',
    level: 'N4', type: 'vocabulary_review', difficulty: 3, objective: 'Distinguish a rumour from a confirmed personal plan.',
    vocabularyJapanese: '開店 means opening a shop、限定 means limited、行列 means queue です。',
    vocabularyEnglish: 'Vocabulary: 開店 is a shop opening, 限定 means limited, and 行列 is a queue.',
    grammarJapanese: '「駅前に新しいパン屋ができるらしいです」は、聞いた情報を少し不確かに伝えます。',
    grammarEnglish: 'らしい reports something that appears to be true from what you heard; it is less direct than a confirmed announcement.',
    exampleJapanese: 'ナツミ：駅前に新しいパン屋ができるらしいよ。',
    sceneJapanese: 'ゲン：開店の日は限定パンがあるらしいから、早めに行ってみよう。',
    question: 'Why does Gen want to go early?', choices: ['There may be limited breads.', 'He has a dentist appointment.', 'The station will close.', 'He needs to return a book.'], correctIndex: 0,
    evidence: 'Gen says there may be limited breads on opening day.', trap: 'Both statements use らしい, so treat them as reported information rather than a personal reservation.',
  },
  {
    slug: 'n4-borrowed-book-teoku', title: 'Return the Book Before the Weekend', subtitle: 'Use ておく for a useful preparation.',
    level: 'N4', type: 'grammar_explanation', difficulty: 3, objective: 'Identify the action done in advance.',
    vocabularyJapanese: '返却 means return、期限 means deadline、延長 means extension です。',
    vocabularyEnglish: 'Vocabulary: 返却 is return, 期限 is deadline, and 延長 is an extension.',
    grammarJapanese: '「金曜日までに返しておきます」は、あとで困らないように前もって返す意味です。',
    grammarEnglish: 'ておく means do something in advance as preparation for a later situation.',
    exampleJapanese: 'ハルカ：この本、返却期限は土曜日です。',
    sceneJapanese: 'レオ：週末は忙しいから、金曜日の帰りに返しておきます。延長しなくて大丈夫です。',
    question: 'When will Leo return the book?', choices: ['On Friday after work.', 'On Saturday night.', 'Next month.', 'After extending it.'], correctIndex: 0,
    evidence: 'Leo says he will return it on Friday on the way home.', trap: 'Saturday is the deadline, but Leo plans to return it earlier.',
  },
  {
    slug: 'n4-plan-tameni', title: 'Saving for a Cycling Trip', subtitle: 'Listen for a purpose with ために.',
    level: 'N4', type: 'short_story', difficulty: 3, objective: 'Identify why someone is changing a daily habit.',
    vocabularyJapanese: '貯金 means saving money、自転車 means bicycle、旅行 means trip です。',
    vocabularyEnglish: 'Vocabulary: 貯金 is saving money, 自転車 is bicycle, and 旅行 is a trip.',
    grammarJapanese: '「旅行のために、毎月少しずつ貯金しています」で、目的を言えます。',
    grammarEnglish: 'ために means “for the purpose of.” The action after it supports the goal named before it.',
    exampleJapanese: 'ユイ：秋に自転車で旅行するために、毎月少しずつ貯金しています。',
    sceneJapanese: 'ショウタ：だから最近は昼ごはんを作っているんですね。外で食べる回数を減らしたんですか。',
    question: 'Why is Yui saving money?', choices: ['For an autumn cycling trip.', 'To buy a new apartment.', 'To pay a dentist.', 'To open a bakery.'], correctIndex: 0,
    evidence: 'Yui says she is saving for a bicycle trip in autumn.', trap: 'Making lunch is the method for saving, not the ultimate goal.',
  },
  {
    slug: 'n4-checklist-beki', title: 'What Should Be Packed First?', subtitle: 'Hear a strong recommendation with べき.',
    level: 'N4', type: 'sentence_pattern_drill', difficulty: 4, objective: 'Identify the item considered essential for a trip.',
    vocabularyJapanese: '充電器 means charger、防寒着 means warm clothing、必要 means necessary です。',
    vocabularyEnglish: 'Vocabulary: 充電器 is charger, 防寒着 is warm clothing, and 必要 means necessary.',
    grammarJapanese: '「山へ行くなら、防寒着を持って行くべきです」は、強い助言です。',
    grammarEnglish: 'べき expresses “should” when the speaker sees an action as important or expected.',
    exampleJapanese: 'レイナ：明日は山の上が寒いそうです。',
    sceneJapanese: 'コウジ：では、防寒着を持って行くべきですね。充電器も忘れないようにしましょう。',
    question: 'What does Koji say they should take?', choices: ['Warm clothing.', 'A bakery menu.', 'A library card.', 'A second umbrella only.'], correctIndex: 0,
    evidence: 'Koji says they should bring warm clothing because the mountain will be cold.', trap: 'A charger is also mentioned, but べき directly modifies the warm clothing advice.',
  },
  {
    slug: 'n4-museum-aida', title: 'Lunch During the Museum Break', subtitle: 'Understand what happens while something continues with 間.',
    level: 'N4', type: 'dialogue_practice', difficulty: 3, objective: 'Identify when the group plans to eat lunch.',
    vocabularyJapanese: '展示 means exhibition、休憩 means break、閉館 means closing time です。',
    vocabularyEnglish: 'Vocabulary: 展示 is an exhibition, 休憩 is a break, and 閉館 is closing time.',
    grammarJapanese: '「休憩の間に昼ごはんを食べましょう」は、休憩している時間の中で食べる意味です。',
    grammarEnglish: '間 marks the time during which another action occurs. It answers “while what is happening?”',
    exampleJapanese: 'マオ：展示は十一時半まで見られます。',
    sceneJapanese: 'カズ：では、休憩の間に昼ごはんを食べて、午後は二階の展示を見ましょう。',
    question: 'When will they eat lunch?', choices: ['During the break.', 'After the museum closes.', 'Before arriving.', 'On the train home.'], correctIndex: 0,
    evidence: 'Kazu says they will eat lunch during the break.', trap: 'The afternoon plan is to see the second floor, not to eat lunch.',
  },
  {
    slug: 'n4-festival-temo', title: 'Even If It Is Crowded', subtitle: 'Follow a plan that continues despite a problem.',
    level: 'N4', type: 'short_story', difficulty: 3, objective: 'Identify what the speakers will do despite the crowd.',
    vocabularyJapanese: '混んでいます means is crowded、屋台 means food stall、待ちます means wait です。',
    vocabularyEnglish: 'Vocabulary: 混んでいます means crowded, 屋台 is a food stall, and 待ちます means wait.',
    grammarJapanese: '「混んでいても、この屋台で食べたいです」は、条件があっても気持ちが変わらない文です。',
    grammarEnglish: 'ても means “even if” or “although.” The following choice still happens despite the condition.',
    exampleJapanese: 'ヨウコ：この祭りは毎年混んでいますね。',
    sceneJapanese: 'タケシ：混んでいても、あそこの焼きそばは食べたいです。少し並びましょう。',
    question: 'What will Takeshi do?', choices: ['Wait for yakisoba.', 'Leave the festival immediately.', 'Cook at home.', 'Visit a dentist.'], correctIndex: 0,
    evidence: 'Takeshi wants the yakisoba even if it is crowded, so he suggests lining up.', trap: 'Crowded is the obstacle; it does not cancel the food plan.',
  },
  {
    slug: 'n4-lost-wallet-passive', title: 'A Wallet Was Found', subtitle: 'Hear the passive voice in a lost-property report.',
    level: 'N4', type: 'jlpt_listening_practice', difficulty: 4, objective: 'Identify where a lost item was found.',
    vocabularyJapanese: '財布 means wallet、届けられました means was handed in、改札 means ticket gate です。',
    vocabularyEnglish: 'Vocabulary: 財布 is wallet, 届けられました means was handed in, and 改札 is a ticket gate.',
    grammarJapanese: '「財布が駅に届けられました」は、誰かが財布を駅へ届けたという受け身の言い方です。',
    grammarEnglish: 'The passive form puts the affected item first: the wallet was handed in. Listen for the location after に.',
    exampleJapanese: '駅員：黒い財布が、今朝駅に届けられました。',
    sceneJapanese: 'サユリ：改札の近くでなくしました。駅員：では、事務室で名前を確認してください。',
    question: 'Where should Sayuri go next?', choices: ['The station office.', 'The bakery.', 'The ticket gate outside.', 'Her apartment.'], correctIndex: 0,
    evidence: 'The staff member directs Sayuri to the station office to confirm her name.', trap: 'The ticket gate is where she lost it, not where she should go next.',
  },
  {
    slug: 'n4-job-interview-preparation', title: 'Preparing for an Interview', subtitle: 'Hear advice about a condition and a likely outcome.',
    level: 'N4', type: 'dialogue_practice', difficulty: 4, objective: 'Identify the preparation that will make the interview easier.',
    vocabularyJapanese: '面接 means interview、練習 means practice、質問 means question です。',
    vocabularyEnglish: 'Vocabulary: 面接 is an interview, 練習 is practice, and 質問 is a question.',
    grammarJapanese: '「質問を練習しておけば、安心して話せます」で、前もってする準備の結果を言えます。',
    grammarEnglish: 'The ておけば pattern combines advance preparation with an expected benefit later.',
    exampleJapanese: 'ナツミ：面接で何を聞かれるか、少し心配です。',
    sceneJapanese: 'ゲン：よくある質問を練習しておけば、当日はもっと安心して話せますよ。',
    question: 'What does Gen advise Natsumi to practise?', choices: ['Common interview questions.', 'How to repair a machine.', 'A bakery order.', 'A train transfer.'], correctIndex: 0,
    evidence: 'Gen recommends practising common questions before the interview.', trap: 'The goal is to speak confidently on the day, not to memorise an unrelated topic.',
  },
  {
    slug: 'n4-sports-demo', title: 'Can You Play Even If You Are Tired?', subtitle: 'Recognise a contrasting condition with ても.',
    level: 'N4', type: 'shadowing_practice', difficulty: 3, objective: 'Identify the reason a player chooses to rest.',
    vocabularyJapanese: '疲れています means is tired、試合 means match、交代 means substitution です。',
    vocabularyEnglish: 'Vocabulary: 疲れています means is tired, 試合 is a match, and 交代 is a substitution.',
    grammarJapanese: '「少し疲れていても、試合には出られます」は、疲れがあっても可能だという意味です。',
    grammarEnglish: 'ても can show that a condition does not prevent something. The next sentence may still choose a different action.',
    exampleJapanese: 'ハルカ：少し疲れていても、最後の十分なら走れます。',
    sceneJapanese: 'レオ：無理しないでください。今日は控えの選手と交代しましょう。',
    question: 'What do they decide to do?', choices: ['Use a substitute player.', 'Cancel the whole season.', 'Run for another hour.', 'Go to the museum.'], correctIndex: 0,
    evidence: 'Leo says not to overdo it and suggests substituting a reserve player.', trap: 'Haruka says she could run, but Leo chooses the safer option.',
  },
  {
    slug: 'n4-service-causative', title: 'Let the Guest Rest First', subtitle: 'Hear a simple causative in a hospitality setting.',
    level: 'N4', type: 'grammar_explanation', difficulty: 4, objective: 'Identify who is allowed to do an action.',
    vocabularyJapanese: 'お客様 means guest、休ませます means let rest、荷物 means luggage です。',
    vocabularyEnglish: 'Vocabulary: お客様 is guest, 休ませます means let someone rest, and 荷物 is luggage.',
    grammarJapanese: '「お客様を先に休ませましょう」は、客が休めるようにする言い方です。',
    grammarEnglish: 'The causative can mean make or let someone do something. Here the context is considerate: let the guest rest.',
    exampleJapanese: 'ミナ：お客様は長い旅行のあとで、かなり疲れているようです。',
    sceneJapanese: 'ナオキ：では、荷物を部屋に運んでから、先に休ませましょう。',
    question: 'What will they do for the guest first?', choices: ['Let the guest rest.', 'Ask the guest to carry luggage.', 'Send the guest to work.', 'Close the hotel.'], correctIndex: 0,
    evidence: 'Naoki says they will carry the luggage and let the guest rest first.', trap: 'Carrying luggage is the staff action; resting is what they allow the guest to do.',
  },
  {
    slug: 'n4-train-transfer-tokoro', title: 'Just About to Change Trains', subtitle: 'Understand timing with ところ.',
    level: 'N4', type: 'listening_comprehension', difficulty: 4, objective: 'Identify what someone is about to do at the station.',
    vocabularyJapanese: 'ちょうど means just、乗り換える means transfer、ホーム means platform です。',
    vocabularyEnglish: 'Vocabulary: ちょうど means just, 乗り換える is transfer, and ホーム is platform.',
    grammarJapanese: '「今から乗り換えるところです」は、これからすぐに乗り換える意味です。',
    grammarEnglish: 'Verb dictionary form + ところです means someone is just about to do that action.',
    exampleJapanese: 'レイナ：今、どこにいますか。',
    sceneJapanese: 'コウジ：駅です。ちょうど大阪行きに乗り換えるところなので、あとで電話します。',
    question: 'What is Koji about to do?', choices: ['Transfer to the Osaka-bound train.', 'Leave Osaka by car.', 'Call immediately.', 'Meet Reina at home.'], correctIndex: 0,
    evidence: 'Koji says he is just about to transfer to the Osaka-bound train.', trap: 'He will call later, not at this exact moment.',
  },
  {
    slug: 'n4-roommate-hazuda', title: 'The Parcel Should Arrive Today', subtitle: 'Use はず to describe a reasonable expectation.',
    level: 'N4', type: 'dialogue_practice', difficulty: 3, objective: 'Identify why the speakers expect a delivery today.',
    vocabularyJapanese: '荷物 means parcel、追跡 means tracking、午前中 means morning です。',
    vocabularyEnglish: 'Vocabulary: 荷物 is parcel, 追跡 is tracking, and 午前中 means morning.',
    grammarJapanese: '「追跡を見ると、荷物は今日届くはずです」は、情報からの予想です。',
    grammarEnglish: 'はず expresses a strong expectation based on evidence, such as a schedule or tracking information.',
    exampleJapanese: 'マオ：荷物、まだ来ていませんね。',
    sceneJapanese: 'カズ：追跡を見ると、今朝配達中になっています。午後には届くはずです。',
    question: 'Why does Kazu expect the parcel today?', choices: ['The tracking says it is out for delivery.', 'He saw it at the bakery.', 'The dentist called.', 'It arrived last week.'], correctIndex: 0,
    evidence: 'Kazu bases the expectation on the tracking status showing it is being delivered.', trap: 'Afternoon is the expected time, but tracking is the reason for the expectation.',
  },
  {
    slug: 'n4-pharmacy-noni', title: 'Even Though the Medicine Should Help', subtitle: 'Hear a contrast with のに.',
    level: 'N4', type: 'listening_comprehension', difficulty: 4, objective: 'Identify the unexpected result after taking medicine.',
    vocabularyJapanese: '薬 means medicine、効きます means works or is effective、眠れません means cannot sleep です。',
    vocabularyEnglish: 'Vocabulary: 薬 is medicine, 効きます means works or is effective, and 眠れません means cannot sleep.',
    grammarJapanese: '「薬を飲んだのに、まだ眠れません」は、予想と違う結果を表します。',
    grammarEnglish: 'のに means “even though” and highlights a result that feels surprising or disappointing.',
    exampleJapanese: 'ヨウコ：薬を飲んだのに、のどの痛みがまだ強いです。',
    sceneJapanese: 'タケシ：今夜も眠れなかったら、明日もう一度先生に相談しましょう。',
    question: 'What is still strong?', choices: ['Yoko’s throat pain.', 'The wind outside.', 'Her desire to travel.', 'The coffee taste.'], correctIndex: 0,
    evidence: 'Yoko says her throat pain is still strong despite taking medicine.', trap: 'Not sleeping is a possible later problem, not the symptom she reports now.',
  },
  {
    slug: 'n4-travel-ka-douka', title: 'Deciding Whether to Go Hiking', subtitle: 'Use かどうか when a decision is still open.',
    level: 'N4', type: 'short_story', difficulty: 3, objective: 'Identify what information they will check before deciding.',
    vocabularyJapanese: '天気 means weather、確認 means check、参加 means participate です。',
    vocabularyEnglish: 'Vocabulary: 天気 is weather, 確認 is check, and 参加 is participate.',
    grammarJapanese: '「行くかどうか、朝の天気を見て決めます」で、するかしないかを考えます。',
    grammarEnglish: 'かどうか means whether or not. It is useful when the answer has not been decided yet.',
    exampleJapanese: 'サユリ：日曜日のハイキング、行くかどうか迷っています。',
    sceneJapanese: 'ヒロ：朝の天気を確認してから決めましょう。雨なら、駅の近くで朝ごはんにしませんか。',
    question: 'What will they check first?', choices: ['The morning weather.', 'A library deadline.', 'A hotel room.', 'The dentist schedule.'], correctIndex: 0,
    evidence: 'Hiro says they will check the morning weather before deciding.', trap: 'Breakfast is the rainy-day alternative, not the information they check.',
  },
  {
    slug: 'n4-neighbourhood-nodesu', title: 'Why the Street Is So Busy', subtitle: 'Listen for an explanatory のです.',
    level: 'N4', type: 'vocabulary_review', difficulty: 3, objective: 'Identify the event that explains the crowd.',
    vocabularyJapanese: '工事 means construction、迂回 means detour、通り means street です。',
    vocabularyEnglish: 'Vocabulary: 工事 is construction, 迂回 is a detour, and 通り is a street.',
    grammarJapanese: '「道で工事をしているんです」は、相手に理由を分かりやすく説明する言い方です。',
    grammarEnglish: 'のです or んです gives explanation or background. It often answers an unspoken “why?”',
    exampleJapanese: 'ナツミ：この通り、今日は車が多いですね。',
    sceneJapanese: 'ゲン：駅の前で工事をしているんです。みんな別の道を通っているらしいですよ。',
    question: 'Why is the street busy?', choices: ['Construction near the station.', 'A new bakery opening.', 'A school holiday.', 'A train delay.'], correctIndex: 0,
    evidence: 'Gen explains that construction in front of the station is causing a detour.', trap: 'The detour is the result; construction is the cause.',
  },
  {
    slug: 'n4-reading-club-youni', title: 'Reading More Smoothly', subtitle: 'Hear a goal with ように and a small routine.',
    level: 'N4', type: 'shadowing_practice', difficulty: 3, objective: 'Identify the habit chosen to improve reading.',
    vocabularyJapanese: '声に出す means read aloud、滑らか means smoothly、毎晩 means every night です。',
    vocabularyEnglish: 'Vocabulary: 声に出す is read aloud, 滑らか means smoothly, and 毎晩 means every night.',
    grammarJapanese: '「もっと滑らかに読めるように、毎晩十分練習しています」で、できるようになりたい目標を言います。',
    grammarEnglish: 'ように after a potential form marks a goal of becoming able to do something.',
    exampleJapanese: 'ハルカ：来月、読書会で短い話を読むことになりました。',
    sceneJapanese: 'レオ：もっと滑らかに読めるように、毎晩十分ずつ声に出して練習しているんです。',
    question: 'How does Leo practise?', choices: ['He reads aloud for ten minutes every night.', 'He watches movies all night.', 'He skips the reading club.', 'He buys a new bicycle.'], correctIndex: 0,
    evidence: 'Leo says he reads aloud for ten minutes each night.', trap: 'The reading club is next month; the nightly routine is the preparation.',
  },
  {
    slug: 'n4-hiking-nakute', title: 'No Need to Bring a Heavy Coat', subtitle: 'Understand a reason with なくて and a changed plan.',
    level: 'N4', type: 'dialogue_practice', difficulty: 3, objective: 'Identify why a heavy coat is unnecessary.',
    vocabularyJapanese: '厚い means thick、上着 means jacket、気温 means temperature です。',
    vocabularyEnglish: 'Vocabulary: 厚い is thick, 上着 is jacket, and 気温 is temperature.',
    grammarJapanese: '「今日は寒くなくて、気温も上がるそうです」で、理由やつながりを言えます。',
    grammarEnglish: 'The なくて form can connect a negative condition to the next idea: because it is not cold…',
    exampleJapanese: 'ミナ：山の上は寒いと思って、厚い上着を持ってきました。',
    sceneJapanese: 'ナオキ：今日は寒くなくて、午後は気温も上がるそうです。薄い上着で大丈夫ですよ。',
    question: 'What does Naoki say is enough?', choices: ['A light jacket.', 'A heavy coat.', 'No clothes at all.', 'A raincoat only.'], correctIndex: 0,
    evidence: 'Naoki says a light jacket will be enough because it is not cold and will get warmer.', trap: 'Mina brought a heavy coat, but Naoki recommends the lighter option.',
  },
  {
    slug: 'n4-school-announcement-ukeru', title: 'Taking the Make-Up Test', subtitle: 'Hear a passive-style school notice and the required action.',
    level: 'N4', type: 'jlpt_listening_practice', difficulty: 4, objective: 'Identify who must contact the teacher.',
    vocabularyJapanese: '追試 means make-up test、欠席 means absence、連絡 means contact です。',
    vocabularyEnglish: 'Vocabulary: 追試 is a make-up test, 欠席 is absence, and 連絡 is contact.',
    grammarJapanese: '「追試を受ける人は、先生に連絡してください」で、対象の人を説明します。',
    grammarEnglish: 'The noun-modifying phrase 受ける人 means “people who will take it.” Listen for who that group is.',
    exampleJapanese: '先生：昨日の試験を欠席した人は、来週追試を受けられます。',
    sceneJapanese: '先生：追試を受ける人は、金曜日までに私へ連絡してください。',
    question: 'Who must contact the teacher by Friday?', choices: ['Students taking the make-up test.', 'All students in the school.', 'Only students who passed.', 'Parents at the station.'], correctIndex: 0,
    evidence: 'The teacher addresses the students who will take the make-up test.', trap: 'Missing yesterday’s test makes someone eligible; the instruction is for those who choose to take the make-up test.',
  },
  {
    slug: 'n4-restaurant-reservation-you-ni', title: 'A Reservation That Works for Everyone', subtitle: 'Follow a request for a seating arrangement.',
    level: 'N4', type: 'dialogue_practice', difficulty: 3, objective: 'Identify the seating request made for an older guest.',
    vocabularyJapanese: '予約 means reservation、座敷 means tatami seating、椅子 means chair です。',
    vocabularyEnglish: 'Vocabulary: 予約 is a reservation, 座敷 is tatami floor seating, and 椅子 is a chair.',
    grammarJapanese: '「祖母が座りやすいように、椅子の席を予約しました」で、相手のための配慮を言います。',
    grammarEnglish: 'ように can describe arranging something so that another person can do it comfortably.',
    exampleJapanese: 'ヨウコ：祖母は長く床に座るのが大変なんです。',
    sceneJapanese: 'タケシ：それなら、座りやすいように椅子の席を予約しておきました。',
    question: 'What kind of seat did Takeshi reserve?', choices: ['A table with chairs.', 'Tatami floor seating.', 'A seat on the train.', 'A bench outside.'], correctIndex: 0,
    evidence: 'Takeshi says he reserved chairs so the grandmother can sit comfortably.', trap: 'Tatami seating is the kind they avoid for this guest.',
  },
  {
    slug: 'n4-library-extension-tekureru', title: 'Could You Extend My Loan?', subtitle: 'Hear a helpful favour with てくれる.',
    level: 'N4', type: 'dialogue_practice', difficulty: 3, objective: 'Identify the favour one friend offers.',
    vocabularyJapanese: '延長 means extension、返却日 means due date、代わりに means instead of です。',
    vocabularyEnglish: 'Vocabulary: 延長 is an extension, 返却日 is a due date, and 代わりに means instead of.',
    grammarJapanese: '「図書館に行くなら、延長してきてくれる？」は、相手が自分のためにしてくれる行為を頼む文です。',
    grammarEnglish: 'てくれる focuses on someone doing a helpful action for the speaker.',
    exampleJapanese: 'サユリ：返却日が今日なのに、仕事が終わりません。',
    sceneJapanese: 'ヒロ：ぼくが図書館の近くへ行くから、代わりに延長してきてあげようか。',
    question: 'What does Hiro offer to do?', choices: ['Extend Sayuri’s loan.', 'Write Sayuri’s report.', 'Buy a new book.', 'Cancel the library card.'], correctIndex: 0,
    evidence: 'Hiro offers to go near the library and extend the loan for Sayuri.', trap: 'The due date is today, but Hiro offers an extension rather than returning the book himself.',
  },
  {
    slug: 'n4-market-price-kureru', title: 'A Vendor Gives a Small Discount', subtitle: 'Follow a benefit received with てくれる.',
    level: 'N4', type: 'vocabulary_review', difficulty: 3, objective: 'Identify what the vendor does for a regular customer.',
    vocabularyJapanese: '値引き means discount、常連 means regular customer、半額 means half price です。',
    vocabularyEnglish: 'Vocabulary: 値引き is a discount, 常連 is a regular customer, and 半額 means half price.',
    grammarJapanese: '「店の人が少し値引きしてくれました」は、相手が自分のためにしてくれたことです。',
    grammarEnglish: 'てくれる highlights a benefit that comes toward the speaker or their group.',
    exampleJapanese: 'ナツミ：この店の人、いつも野菜をきれいに包んでくれます。',
    sceneJapanese: 'ゲン：今日は常連だからと、りんごを少し値引きしてくれました。半額ではないけど、うれしいですね。',
    question: 'What did the vendor do?', choices: ['Gave a small discount on apples.', 'Made the apples half price.', 'Packed vegetables for free forever.', 'Closed the market early.'], correctIndex: 0,
    evidence: 'Gen says the vendor gave a small discount on apples, not half price.', trap: 'Half price is explicitly denied, making it a tempting but wrong choice.',
  },
  {
    slug: 'n4-jlpt-station-change', title: 'JLPT Listening: The Platform Changed', subtitle: 'Keep the unchanged detail and replace the changed one.',
    level: 'N4', type: 'jlpt_listening_practice', difficulty: 4, objective: 'Identify the correct platform after an announcement changes one detail.',
    vocabularyJapanese: '発車 means departure、番線 means platform number、変更 means change です。',
    vocabularyEnglish: 'Vocabulary: 発車 is departure, 番線 is platform number, and 変更 is change.',
    grammarJapanese: '「時間は変わりませんが、番線が変更になりました」で、一つだけ変わった情報を聞き分けます。',
    grammarEnglish: 'JLPT listening often gives an original plan, then changes one detail. Preserve what stays the same and replace only what changes.',
    exampleJapanese: '案内：大阪行きは十時十五分発です。',
    sceneJapanese: '案内：時間は変わりませんが、三番線から五番線に変更になりました。',
    question: 'Which platform should the listener use?', choices: ['Platform five.', 'Platform three.', 'Platform ten.', 'Platform fifteen.'], correctIndex: 0,
    evidence: 'The departure time remains 10:15, but the platform changes from three to five.', trap: 'Platform three is the original detail included to test whether you hear the change.',
  },
  {
    slug: 'n4-jlpt-event-poster', title: 'JLPT Listening: The Poster Has One Important Change', subtitle: 'Resolve a date change in a short community announcement.',
    level: 'N4', type: 'jlpt_listening_practice', difficulty: 4, objective: 'Identify the final day of a community event.',
    vocabularyJapanese: '講演会 means talk or lecture、延期 means postponement、受付 means registration desk です。',
    vocabularyEnglish: 'Vocabulary: 講演会 is a talk or lecture, 延期 is postponement, and 受付 is a registration desk.',
    grammarJapanese: '「土曜日の講演会は、日曜日に延期されました」で、予定の変更を伝えます。',
    grammarEnglish: '延期されました means “was postponed.” Compare the original day with the replacement day carefully.',
    exampleJapanese: '案内：市民ホールの講演会は、土曜日の午後二時の予定でした。',
    sceneJapanese: '案内：大雨のため、日曜日の午前十時に延期されました。受付は九時半からです。',
    question: 'When is the lecture now?', choices: ['Sunday at 10 a.m.', 'Saturday at 2 p.m.', 'Sunday at 9:30 a.m.', 'Saturday morning.'], correctIndex: 0,
    evidence: 'The lecture moves to Sunday at 10 a.m.; 9:30 is when registration begins.', trap: 'The original Saturday time and the registration time are both plausible distractors.',
  },
];

/** Fifty curriculum-linked additions, giving the seeded catalogue sixty distinct lessons in total. */
export const expandedAudioPilotDefinitions: readonly AudioPilotDefinition[] = units.map(unitToDefinition);
